### ISSUE TITLE
ユーザー登録時に、属性を追加する

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#1]
## 改善詳細 / Details of Improvement
- 現状では、ユーザー登録時に氏名、ニックネーム、メールアドレス、パスワードしか取らないが、新たに、
  - 住所（必須）
  - 生年（必須）
  - 性別（男・女・その他・無回答） （必須）
  - 職業
をつけたい

## 期待する見せ方・挙動 / Expected behavior
- フォームに上記項目が含まれている

## 実装の方向
- そもそも、decidim は decidim-core などのコンポーネントに分かれている。
- 本家のバージョンアップに追随するため、できるだけ本家のコンポーネントを直接いじることは避けたい
- したがって、[module](https://docs.decidim.org/en/develop/how_to_create_a_module/) をつくるなどをしてカスタマイズができるのかを調査する
  - view については[この辺](https://docs.decidim.org/en/develop/view_hooks/)？
- 本来、管理画面から設定できたりすると美しいが、今回は時間は無いのでソースコード直書きで構わない。
- 多言語化もいまのところ必要なし

## 対象インスタンス / Instances

- 加古川市

**Comment by kken78** [comment]
https://github.com/codeforjapan/decidim-cfj/issues/21
との掛け合わせでいくと、
新たに、
- 本名
も、「表示はさせない属性情報として」取得したい
ということになりますかね。

- 氏名（＝ニックネームへ変更）
- ニックネーム（＝アカウントIDへ変更）

追加するのは、
- 本名（必須）
- 住所（必須）
- 生年（必須）
- 性別（男・女・その他・無回答） （必須）
- 職業

という理解

**Comment by halsk** [comment]
ありがとうございます。その理解で正しいです

**Comment by takahashim** [comment]
ユーザー登録に関するコードを見てみています。

ユーザー登録には普通にDeviseを使っていますが、Decidimでは[Rectify](https://github.com/andypike/rectify)のFormオブジェクトとCommandオブジェクトも使っていて、登録の際にはこれを呼んでいるようです。そのため、項目が追加されるとこの辺も修正する必要がありそうです。

* Decidim::RegistrationForm https://github.com/decidim/decidim/blob/develop/decidim-core/app/forms/decidim/registration_form.rb
* Decidim::CreateRegistrationコマンド https://github.com/decidim/decidim/blob/develop/decidim-core/app/commands/decidim/create_registration.rb

登録画面等の表示については、view_hook等は使っておらず、普通にDeviseのregistrations/new.html.erbで書かれているようです。なのでこれを上書きすることになりそうです。

* 登録画面のerbテンプレート https://github.com/decidim/decidim/blob/develop/decidim-core/app/views/decidim/devise/registrations/new.html.erb

他のインスタンスでも使い回すことを考えない（各インスタンスで項目が変わるかも）ということであれば、コンポーネントにはしないで各インスタンスのコードで上書きするのでも、あまり変わらないかもしれません。

**Comment by halsk** [comment]
@takahashim 
ありがとうございます！他のインスタンスで使い回さなくても大丈夫です。

* rails generate migration で項目を追加
* new.html.erb を修正
* locale を追加

という感じでしょうか？
decidim-core は、gem でインストールされていますが、これをこちらのリポジトリ配下で上書きするにはどうしたら良いのでしょうか。

**Comment by takahashim** [comment]
> decidim-core は、gem でインストールされていますが、これをこちらのリポジトリ配下で上書きするにはどうしたら良いのでしょうか。

このリポジトリ(decidim-cfj)のapp/views/以下にファイルを置けば良いです。decidim-cfj自体が普通のRailsアプリケーションになっているので、そのviewsを使う形になります。
decidim-coreはRailsエンジンとしてマウントされているのですが、ローカルにあるファイルの方が優先されます。

----

それはそれとして、大きな問題としては、データの持たせ方があります。

* Userモデルに項目を追加する（Userテーブルにカラムを追加する）
* Userモデルとone-to-one対応のUserPrivateInfoモデル（名前は仮）を追加して、Userモデルのテーブル自体は変更しない

最近の傾向では後者の方がおすすめ（Userテーブルを肥大化させるとろくなことにならない）と言われているのですが、今回のケースだとちょっと難しいかもしれません（まだ調査中です）。

**Comment by halsk** [comment]
なるほど。ローカルにファイルを置いたらそちらが優先されるのですね。ありがとうございます。
モデルについては後者の方が今後の本家のバージョンアップに対する影響が低そうですが、難しければ前者でも問題ないと思います。

**Comment by takahashim** [comment]
ちなみに入力項目の仕様(validation)ですが、

* 性別: ISO 5218の性別コード https://ja.wikipedia.org/wiki/ISO_5218
* 住所: 文字列（適当な長さの上限、255字くらい？）
* 職業: 文字列（適当な長さの上限、100字くらい？）
* 生年: 整数値

くらいの制限を想定しています。

**Comment by takahashim** [comment]
機能的にはできそうな雰囲気になってきました。
リリースにあたってはもうちょっと要件について詰めた方がよいかもしれません。

* 各属性項目について公開・非公開にするかどうか（全部非公開で良さそう？）
* 管理者画面での確認・変更は可能かどうか（そもそも現状管理者がどこまでできるのか把握してないです）
* 上の2つと合わせて、そもそもこれらの属性はどういう用途・ユースケースで使うのか
* いつ頃リリースする予定（希望）なのか
* リリースする際、既存のアカウントのデータはどうするか（「アカウント全削除・再登録」 or 「既存アカウントは動くけど更新するには各必須属性項目の登録が必要」くらいでしょうか）
* 公開後にdecidim本家のバージョンアップを行う際、「頑張って確認する」くらいの手順で良いか

**Comment by halsk** [comment]
> 各属性項目について公開・非公開にするかどうか（全部非公開で良さそう？）
@isaozz さん、確認よろしくおねがいします。以下で良いですか？

氏名（＝ニックネームへ変更）：公開
ニックネーム（＝アカウントIDへ変更）：公開
追加する属性

本名（必須）：非公開
住所（必須）：非公開
生年（必須）：非公開
性別（男・女・その他・無回答） （必須）：非公開
職業：非公開

つまり、追加属性は全て非公開

> 管理者画面での確認・変更は可能かどうか（そもそも現状管理者がどこまでできるのか把握してないです）
管理者側では変更不可で良いかと思います。(現状、管理画面ではユーザの名前等は変更できないです)

> 上の2つと合わせて、そもそもこれらの属性はどういう用途・ユースケースで使うのか
本名を聞いておくことで荒らしを防ぐ、住所から市民かどうかを判定する、利用者の属性を把握するといった使い方です。
管理画面で確認できるだけでOKです。

> いつ頃リリースする予定（希望）なのか
可能であれば今月30 日にリリースしたいと考えています。

> リリースする際、既存のアカウントのデータはどうするか（「アカウント全削除・再登録」 or 「既存アカウントは動くけど更新するには各必須属性項目の登録が必要」くらいでしょうか）

一旦今のデータは全部消してスタートします。

> 公開後にdecidim本家のバージョンアップを行う際、「頑張って確認する」くらいの手順で良いか
はい。それで考えています。

関

**Comment by isaozz** [comment]
@halsk 上記内容で問題ありません。
できれば、「頑張って確認する」のは避けたいですが。。。

**Comment by halsk** [comment]
> できれば、「頑張って確認する」のは避けたいですが。。。

本家に無いカスタマイズをする以上、ここは我々が確認するしか無いですね。
本家にこの機能を提案してみても良いかもしれませんが、グローバル対応にするには色々設定とかの追加が必要なので、それはそれで結構工数がかかりそう・・

**Comment by isaozz** [comment]
@halsk 大丈夫です！！！何とかします！！！

**Comment by takahashim** [comment]
@halsk @isaozz 回答ありがとうございます！

そして現在Decidim自体と他の既存インスタンスの調査中なのですが、もしかしたら今の #47 の修正から大幅に変更になるかもしれません…（独自の改造をしないで済ませられないかを検討してます）。
明日までには追加で連絡する予定なので、もう少しお待ち下さい。
