### ISSUE TITLE
オープンデータファイルがダウンロードできない

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#101]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- フッタにある「オープンデータファイルをダウンロード」しても、「オープンデータファイルはまだ利用できません。数分後にもう一度お試しください」となる

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/97588463-db556280-1a3f-11eb-8df4-4c3c113de66d.png)

![image](https://user-images.githubusercontent.com/16509/97588481-e14b4380-1a3f-11eb-8d75-a88749c0f2b7.png)

## 期待する見せ方・挙動 / Expected Behavior
- そもそも何がダウンロードできるのだろう。
- 最悪リンク自体を消してしまう

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by takahashim** [comment]
「オープンデータファイルをダウンロード」は `Decidim::OpenDataJob.perform_later`を実行してると思うのですが、私のローカルではdevelopment.logに、

> [ActiveJob] [Decidim::OpenDataJob] [1e57da92-b075-4751-8224-c060064e52e8] Error performing Decidim::OpenDataJob (Job ID: 1e57da92-b075-4751-8224-c060064e52e8) from Async(default) in 29.64ms: NameError (uninitialized constant Decidim::OpenDataExporter::Zip):

みたいなログを出して失敗しているようでした…。
要はZipの名前解決に失敗しているようなので、config/application.rbの`require 'rails/all'`の後ろあたり、

https://github.com/codeforjapan/decidim-cfj/blob/999641f809033910d48434ee1d63cab545797899/config/application.rb#L3

に `require 'zip'`という行を追加すると通りそうです。

中身としては、

```
localhost-open-data-meetings.csv
localhost-open-data-proposals.csv
localhost-open-data-results.csv
```

というファイルがzipで固められているものでした。カラムの見出し行はそれぞれ以下のようになっています（CSVなのに、なぜか区切りが `;` です）。

> id;category/id;category/name/en;category/name/ja;scope/id;scope/name/en;scope/name/ja;participatory_space/id;participatory_space/url;component/id;title/en;title/ja;description/en;description/ja;start_time;end_time;attendees;contributions;organizations;address;location/en;location/ja;reference;comments;attachments;followers;url;related_proposals;related_results

> id;category/id;category/name/en;category/name/ja;scope/id;scope/name/en;scope/name/ja;participatory_space/id;participatory_space/url;component/id;title/en;body/en;state;reference;answer/en;answer/ja;supports;endorsements/total_count;endorsements/user_endorsements;comments;attachments;followers;published_at;url;meeting_urls;related_proposals;is_amend;original_proposal/title/en;original_proposal/url

> id;category/id;category/name/en;category/name/ja;scope/id;scope/name/en;scope/name/ja;parent/id;title/en;title/ja;description/en;description/ja;start_date;end_date;status/id;status/key;status/name/en;status/name/ja;progress;created_at;url;component/id;proposal_urls

**Comment by halsk** [comment]
`require 'zip'` を追加してみたのですが、私の環境では下記のエラーが出て引き続きダウンロードできないですね・・・

```
app_1  | [ActiveJob] [Decidim::OpenDataJob] [cd0f05d5-7810-4f7d-881e-effb58390d95]   ↳ /usr/local/bundle/bundler/gems/decidim-912bb8b483fd/decidim-proposals/lib/decidim/proposals/proposal_serializer.rb:74
app_1  | [ActiveJob] [Decidim::OpenDataJob] [cd0f05d5-7810-4f7d-881e-effb58390d95] Scoped order is ignored, it's forced to be batch order.
app_1  | [ActiveJob] [Decidim::OpenDataJob] [cd0f05d5-7810-4f7d-881e-effb58390d95]   Decidim::Component Load (1.2ms)  SELECT  "decidim_components".* FROM "decidim_components" WHERE "decidim_components"."participatory_space_type" = $1 AND "decidim_components"."participatory_space_id" = $2 AND "decidim_components"."published_at" IS NOT NULL AND "decidim_components"."manifest_name" = $3 ORDER BY "decidim_components"."id" ASC LIMIT $4  [["participatory_space_type", "Decidim::ParticipatoryProcess"], ["participatory_space_id", 3], ["manifest_name", "accountability"], ["LIMIT", 1000]]
app_1  | [ActiveJob] [Decidim::OpenDataJob] [cd0f05d5-7810-4f7d-881e-effb58390d95]   ↳ /usr/local/bundle/bundler/gems/decidim-912bb8b483fd/decidim-coreservices/decidim/open_data_exporter.rb:40
app_1  | [ActiveJob] [Decidim::OpenDataJob] [cd0f05d5-7810-4f7d-881e-effb58390d95] Error performing Decidim::OpenDataJob (Job ID: cd0f05d5-7810-4f7d-881e-effb58390d95) from Async(default) in 288.09ms: CarrierWave::IntegrityError (ファイルはどの組織にも添付されていません):
app_1  | /app/app/uploaders/decidim/application_uploader.rb:33:in `validate_inside_organization'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/processing.rb:83:in `block (2 levels) in process!'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/processing.rb:75:in `each'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/processing.rb:75:in `block in process!'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/processing.rb:74:in `process!'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/callbacks.rb:14:in `each'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/callbacks.rb:14:in `with_callbacks'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/cache.rb:137:in `cache!'
app_1  | /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/store.rb:63:in `store!'
app_1  | /usr/local/bundle/bundler/gems/decidim-912bb8b483fd/decidim-core/app/jobs/decidim/open_data_job.rb:13:in `perform'
app_1  | /usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/execution.rb:39:in `block in perform_now'
app_1  | /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
```

**Comment by halsk** [comment]
解決するまで、一旦オープンデータダウンロードへのリンクを切っておきます。

**Comment by halsk** [comment]
> 「オープンデータファイルをダウンロード」は `Decidim::OpenDataJob.perform_later`を実行してると思うのですが、私のローカルではdevelopment.logに、
> 
> > [ActiveJob] [Decidim::OpenDataJob] [1e57da92-b075-4751-8224-c060064e52e8] Error performing Decidim::OpenDataJob (Job ID: 1e57da92-b075-4751-8224-c060064e52e8) from Async(default) in 29.64ms: NameError (uninitialized constant Decidim::OpenDataExporter::Zip):
> 
> みたいなログを出して失敗しているようでした…。
> 要はZipの名前解決に失敗しているようなので、config/application.rbの`require 'rails/all'`の後ろあたり、
> 
> https://github.com/codeforjapan/decidim-cfj/blob/999641f809033910d48434ee1d63cab545797899/config/application.rb#L3
> 
> に `require 'zip'`という行を追加すると通りそうです。
> 
> 中身としては、
> 
> ```
> localhost-open-data-meetings.csv
> localhost-open-data-proposals.csv
> localhost-open-data-results.csv
> ```
> 
> というファイルがzipで固められているものでした。カラムの見出し行はそれぞれ以下のようになっています（CSVなのに、なぜか区切りが `;` です）。
> 
> > id;category/id;category/name/en;category/name/ja;scope/id;scope/name/en;scope/name/ja;participatory_space/id;participatory_space/url;component/id;title/en;title/ja;description/en;description/ja;start_time;end_time;attendees;contributions;organizations;address;location/en;location/ja;reference;comments;attachments;followers;url;related_proposals;related_results
> 
> > id;category/id;category/name/en;category/name/ja;scope/id;scope/name/en;scope/name/ja;participatory_space/id;participatory_space/url;component/id;title/en;body/en;state;reference;answer/en;answer/ja;supports;endorsements/total_count;endorsements/user_endorsements;comments;attachments;followers;published_at;url;meeting_urls;related_proposals;is_amend;original_proposal/title/en;original_proposal/url
> 
> > id;category/id;category/name/en;category/name/ja;scope/id;scope/name/en;scope/name/ja;parent/id;title/en;title/ja;description/en;description/ja;start_date;end_date;status/id;status/key;status/name/en;status/name/ja;progress;created_at;url;component/id;proposal_urls

csv ファイルのセパレータは、[decidim.rb](https://github.com/codeforjapan/decidim-cfj/blob/80213f250b0567f77ecdf8b5bac4725dc22286fb/config/initializers/decidim.rb#L192) で定義できるようですね。

```
  # Sets Decidim::Exporters::CSV's default column separator
  # config.default_csv_col_sep = ";"
```

**Comment by takahashim** [comment]
> app_1  | [ActiveJob] [Decidim::OpenDataJob] [cd0f05d5-7810-4f7d-881e-effb58390d95] Error performing Decidim::OpenDataJob (Job ID: cd0f05d5-7810-4f7d-881e-effb58390d95) from Async(default) in 288.09ms: CarrierWave::IntegrityError (ファイルはどの組織にも添付されていません):

はCarrierWaveの問題でしょうか。
OpenDataJobはオープンデータをCSVにしたものを集めてzipに固めた(OpenDataExporter)上で、CarrierWaveでどこかにアップロード(OpenDataUploader)してからダウンロードさせるしくみのようで、その途中でエラーになっているようです。

ひょっとすると https://github.com/codeforjapan/decidim-cfj/issues/18 の修正の問題で、以下の部分の条件が足りてない（追加するべき？）なのかもしれません。

https://github.com/codeforjapan/decidim-cfj/blob/a6b9eeb114aa6c57008fe9c1f0120eb702743ec6/app/uploaders/decidim/application_uploader.rb#L28-L31

ちょっと見てもらえませんか？＞ @mcyph 

OpenDataJob
https://github.com/decidim/decidim/blob/develop/decidim-core/app/jobs/decidim/open_data_job.rb

OpenDataExporter
https://github.com/decidim/decidim/blob/develop/decidim-core/app/services/decidim/open_data_exporter.rb

OpenDataUploader
https://github.com/decidim/decidim/blob/develop/decidim-core/app/uploaders/decidim/open_data_uploader.rb

**Comment by mcyph** [comment]
@takahashim はい、open data exportをすると、modelは`nil`のようです。なので、例のファイルに`return if model == nil`を加えたら動けそうです。

`open_data_job.rb`は`ApplicationUploader`からサブクラスされた`OpenDataUploader`を使っています。
`ApplicationUploader`はCarrierWaveを使って'open_data/localhost-open-data'ファイルをアップロードフォルダーに保存するよう。`ApplicationUploader`は普段とあるモデルクラス（SQLテーブル）との関係があるけどエキスポートファイルですからどのモデルとは関係がないと思います。

ところで、open data jobを実行できるには、これもGemfileに加える必要がありました：

```
gem 'rubyzip', '>= 1.0.0'
gem 'zip-zip'
```

**Comment by takahashim** [comment]
@mcyph 修正ありがとうございます！

ところでrubyzipはもともと2.0.0が入っているはずですが、追加しないと動きませんでしたか？(おそらくGemfile.lockには2.0.0がありますよね）

あと、zip-zipはrubyzip 1.0以前のものを動かすためのadapterのようなので、おそらく不要なんではないかなあと思います。
なんで動かなかったんでしょうね…。

**Comment by mcyph** [comment]
@takahashim はい、不思議ですね。。理由はまだよく理解していないような気がしますが、`gem list`を実行したら`rubyzip (2.0.0) ... zip (2.0.2) ... zip-zip (0.3)`が表示されるので最新バージョンがインストールされるみたいです。でもGemfileに>=2.0.0に変更するのはより良いので修正するPRを送るのがいいかもしれませんね。

`rubyzip`をインストールしたままにして、`zip-zip`をアンインストールしてGemfileから取り除いたら、下のトレースバックが出ます。`rubyzip>=2.0.0`を再インストールしたら、エラーがまだ表示されるので、これらのパッケージとのファイル競合ではないかなって思っています。

```
  ↳ /mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/decidim-912bb8b483fd/decidim-assemblies/app/cells/decidim/assemblies/content_blocks/highlighted_assemblies/show.erb:7
[ActiveJob] [Decidim::OpenDataJob] [e48389be-c856-4727-96b5-b65a30ea8345] Error performing Decidim::OpenDataJob (Job ID: e48389be-c856-4727-96b5-b65a30ea8345) from Async(default) in 171.52ms: NameError (uninitialized constant Decidim::OpenDataExporter::Zip):
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/decidim-912bb8b483fd/decidim-core/app/services/decidim/open_data_exporter.rb:28:in `data'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/decidim-912bb8b483fd/decidim-core/app/services/decidim/open_data_exporter.rb:22:in `block in export'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/decidim-912bb8b483fd/decidim-core/app/services/decidim/open_data_exporter.rb:22:in `open'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/decidim-912bb8b483fd/decidim-core/app/services/decidim/open_data_exporter.rb:22:in `export'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/decidim-912bb8b483fd/decidim-core/app/jobs/decidim/open_data_job.rb:11:in `perform'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activejob-5.2.4.4/lib/active_job/execution.rb:39:in `block in perform_now'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/i18n-1.8.5/lib/i18n.rb:313:in `with_locale'
/mnt/evo860/david/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activejob-5.2.4.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
...
```

**Comment by mcyph** [comment]
ところで、すでにこのようにしているかどうかわかりませんけど、念の為 https://docs.decidim.org/en/develop/open-data/ によるとシステムリソースを浪費すぎるのでon-the-fluエキスポートができなくて、たまには`cron`などで`bundle exec rake decidim:open_data:export`コマンドをスケジュールしなければならないとのことです。

**Comment by halsk** [comment]
なるほどー。cron で予めファイルを作っておくのですね。やってみます！

**Comment by halsk** [comment]
解決していないので復活させておきます。

**Comment by mcyph** [comment]
（すみません最近は大学やCode for Australiaのプロジェクトに注目していてこのバグを十分に確認していませんでした。）

自分のローカルなコピーでは、この機能は正常に動いているようなので、サーバーでのログファイルをチェックしないと問題の起源が見つからないような気がします。

念の為、自分のろーかるなコピーはDockerを使っていなくて、Ubuntu 18.04.5 LTSというOSを使っていて、rubyenvでのruby 2.6.6p146でdecidimを使っています。助けるかどうかわかりませんけど、以下はrubyでのインストールされたパッケージの一部です:

> carrierwave (2.1.0, 1.3.1); html_tokenizer (0.0.7); htmlentities (4.3.4); json (2.3.1, default: 2.1.0); mini_magick (4.10.1); orm_adapter (0.5.0); pg (1.2.3, 1.1.4); rails (6.0.3.4, 5.2.4.4); rails-controller-testing (1.0.5); rails-dom-testing (2.0.3); rails-html-sanitizer (1.3.0); rails-i18n (6.0.0, 5.1.3); railties (6.0.3.4, 5.2.4.4); rubyzip (2.0.0); sass (3.7.4); sass-listen (4.0.0); sassc (2.4.0, 2.3.0); sassc-rails (2.1.2); sprockets (4.0.2, 3.7.2); sprockets-es6 (0.9.2); sprockets-rails (3.2.2); zip (2.0.2); zip-zip (0.3); zlib (1.1.0, default: 1.0.0)

**Comment by halsk** [comment]
とりあえず staging のみリンク復活させて見てみました。
https://stagingtest.diycities.jp/

下記のURLを叩く
https://stagingtest.diycities.jp/open-data/download
→Sidekiq に Decidim::OpenDataJob を投げる
→staging では Sidekiq が走っていないので終了

そして、`bundle exec rake decidim:open_data:export` を Docker コンテナに入って実行しても何も起きません。

という感じになってますね。本番では sidekiq は走っているので、そちらでも確認してみます。

**Comment by halsk** [comment]
本番以外でも、queue_adapter は sidekiq になっていますね。
ちなみに、本番環境にログインして `bundle exec rake decidim:open_data:export` を実行し、sidekiq のログを見ると
```
2020-11-14T08:28:19.277Z 22638 TID-18yxl6 Decidim::OpenDataJob JID-41d11526fc8c0a05128d1496 INFO: done: 0.375 sec
```
と書かれており、`/tmp/kakogawa.diycities.jp-open-data.zip` のタイムスタンプが更新されたので、実行自体はされているようでした。
ただし、解凍してみても中身が存在しません。

**Comment by halsk** [comment]
どうも、オープンデータとして公開されるコンポーネントの種類は、このバージョンでは
```
meetings
proposals
results
```
の3つのようです。

https://github.com/decidim/decidim/blob/ce75b42adc19cf99d4efd85048ab76b02c623fb2/decidim-core/app/services/decidim/open_data_exporter.rb#L50

で、
```
  Decidim.component_manifests.flat_map(&:export_manifests).select(&:include_in_open_data?).each do |export_manifest|
```
という行で選ばれている模様。

加古川市では `debates` コンポーネントを使っているので、オープンデータ対象が無い、ということになりますね。バグではないようです。
