### ISSUE TITLE
アカウント削除ができない

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#105]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- アカウント削除を行うとスクリーンショットのようなエラーが出る。
- 結果、アカウントの削除もできていない。
- ただ、アカウントを削除できるケース（ユーザーによって異なる？）もある。
- 削除できないユーザーは、管理者の招待メールを送付し、その招待メールを削除している。

## スクリーンショット / Screenshot

![エラー](https://user-images.githubusercontent.com/40754081/97688423-73edf000-1add-11eb-8539-1464fa2e7bd5.png)

## 期待する見せ方・挙動 / Expected Behavior
- アカウントを削除したい。

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- Windows
- Chrome / Internet Explorer

**Comment by takahashim** [comment]
この画面は普通にinternal server error(response code: 500)が出た画面ですよね。
エラーログが分かれば原因がわかるかもしれません。

**Comment by isaozz** [comment]
アカウントを削除できなかった件ですが、どうやら属性情報を入力していなかったからだったようです。
属性情報の入力後削除できました。お騒がせしました。
