### ISSUE TITLE
ブログの表示がおかしい

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#107]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- ブログ（１枚目のスクリーンショット）を開き、詳細をクリックすると文字がすべて左によってしまっている（２枚目）。

## スクリーンショット / Screenshot

![スクリーンショット 2020-10-30 20 41 24](https://user-images.githubusercontent.com/40754081/97701335-9806fc80-1af0-11eb-9d77-d0f09ae292ae.png)
![スクリーンショット 2020-10-30 20 43 28](https://user-images.githubusercontent.com/40754081/97701354-9d644700-1af0-11eb-90bc-95afa6602ce2.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正常な位置で表示させたい

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by halsk** [comment]
支持を有効にすると、正常に表示される。

<img width="1232" alt="Screen Shot 2020-10-30 at 22 28 59" src="https://user-images.githubusercontent.com/16509/97710648-5fbaea80-1aff-11eb-8fd6-9d80d8de7d47.png">

ローカル環境でも、支持を無効にしたブログコンポーネントを作成するとデザインを崩せます。

支持を有効にしても、しなくても正常に表示されるような style を書かなくてはいけない。

**Comment by isaozz** [comment]
ありがとうございます。
一旦、「支持を有効」という形で運用しておきます。
