### ISSUE TITLE
HTMLタグの使用について

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#11]
## 改善詳細 / Details of Improvement
- 管理画面などにおいて、HTMLタグを使用できるようにしたい

## 期待する見せ方・挙動 / Expected behavior
- 管理者側で画像の貼り付けなどを行いたい

## 対象インスタンス / Instances

- 加古川市

**Comment by halsk** [comment]
https://github.com/decidim/decidim/issues/5451

ここで議論されているように、リッチテキストエディタは `Quill` を使っているようだ。
このエディタのオプションを変更すればHTMLも有効になる？
ただし、このエディタを使ってユーザ側も投稿ができるので、変な画像をアップしたりできないように機能が制限されている。
`管理画面でのみHTMLソース編集や画像埋め込みを有効にする` ということができればベスト。

**Comment by mcyph** [comment]
サーバー側ではHTMLのタグがサニタイズされるので、ブラウザ側では充分HTML入力がサポートできる（例えば https://github.com/benwinding/quill-html-edit-button 、それとも自分たちのHTMLエディターを作れる）。
しかし、どうやって添付したファイル（画像など）をアップロードして保存するのを考える必要があると思う。

色々なrailsコントローラは[`uploaders/decidim/attachment_uploader.rb`](https://github.com/decidim/decidim/blob/develop/decidim-core/app/uploaders/decidim/attachment_uploader.rb)からサブクラスされて下の画像のコンテンツのように、ルートを作っているので、私たちもこのように`ApplicationUploader`からサブクラスして新しい`EditorAttachments`か何らかのクラスを作るのがいいのかな。

![image](https://user-images.githubusercontent.com/20507948/97162250-10a94880-17d3-11eb-8542-d6acea4d7c6d.png)

**Comment by mcyph** [comment]
decidimにある [https://github.com/decidim/decidim/blob/develop/decidim-core/app/assets/javascripts/decidim/editor.js.es6](editor.js.es6) で可能性を探る際、WYSYWIGエディターでなくても、Markdownは実にかなり普及になっているので、Quillの代わりにインプレース交換してGitHubでのインターフェースみたいに「Write」、「Preview」のタブに分けてもわかりやすくできると思います。

たとえば、「[showdownjs](https://github.com/showdownjs/showdown)」などbidirectional/lossless Markdownエンジン使っていたら、ブラウザで編集する時にはMarkdownに変換できたり、サーバに送るときはHTMLに変換できたりします。

どう思いますか？？弱点と言えば、初心者ならMarkdownになれるの少し時間かかるけど、GitHubと同じようなツールバー表示できるなら、難易度それだけ高くないように考えてます。それに、メンテナンス的にはより複雑になりますが、とにかくHTMLの編集を許容してエディターのインタフェース変更するとしたら、メンテナンス的にはそれだけ違わないような気がします！

**Comment by halsk** [comment]
確かに、Markdown 良いですね！その方が良いと思いました！

**Comment by takahashim** [comment]
Markdownといえば、PlatoniqのDecidim::DecidimAwesomeが一部Markdownエディター機能もサポートしているようです（READMEを読んだだけで試してないです）。
https://github.com/Platoniq/decidim-module-decidim_awesome

**Comment by mcyph** [comment]
> Markdownといえば、PlatoniqのDecidim::DecidimAwesomeが一部Markdownエディター機能もサポートしているようです（READMEを読んだだけで試してないです）。
> https://github.com/Platoniq/decidim-module-decidim_awesome

知らせてくれてありがとうございます、試してみます！！ https://github.com/Platoniq/quill-image-upload にもイメージアップロード機能があるそうなので、可能であれば既存のプラグインを使うのがいいと思います！

**Comment by mcyph** [comment]
試してみましたけどdecidimの安定ブランチとdecidim_awesome使ったら色々とパッチをしないと動かないみたいです。

デフォルトの"Markdownなし"編集モードを選択したら、file picker dialogを使って画像を選択できるけどHTMLソースを編集できません。

Markdown編集モード選択したら、file picker dialogを使えなくてコピペ・ドラッグドロップでしか画像を貼れません。しかも、Markdownモードはサーバー側で変換され、ただ「experimental」のステータスがついているみたいので、将来では提案などのコンテンツをレンダリングできるとは保証されないような気がします。

でも https://github.com/Platoniq/decidim-module-decidim_awesome/blob/master/app/controllers/decidim/decidim_awesome/editor_images_controller.rb ではエディターに添付する画像を保存できるコードがあるので、そこから始めるといいかもしれません。できれば依存関係を削減するほうがいいと思っています、そうするとより安定にできるように感じます。

**Comment by takahashim** [comment]
うーん、そのまま動かないのは残念ですね（ちゃんと確認できてなくてすみません）
とはいえDecidim::DecidimAwesomeは大きそうなので、不要な部分が多そうであれば小さく切り出して使った方が扱いやすいかもしれません。

**Comment by mcyph** [comment]
いえいえ、下の画像が示すように、DecidimAwesomeは既に必要な（ブラウザ側にも、サーバー側にも）機能の多くがあるので、実はそこから始められたら多くの時間を節約できそうと思います！

![image](https://user-images.githubusercontent.com/20507948/97298144-1ec89900-18a7-11eb-987f-08d3e638259c.png)

DecidimAwesomeアドミンにはとある"Compatibility Check"は失敗しているので、多分バージョンはミスマッチしています。でもやっぱり他の機能が必要じゃないとしたらフォークするのがメインテナンス的にはもっといいって思っています。

![image](https://user-images.githubusercontent.com/20507948/97298077-08224200-18a7-11eb-967e-04dcb7df93a2.png)

**Comment by halsk** [comment]
なるほど。とりあえず、多少乱暴でも良いので、加古川市のスタートに向けて、ディベートコンポーネント内でHTMLを使いたい(最悪画像アップロードは管理画面から出来なくても良い)のですが、どうするのが良いと思いますか？

**Comment by halsk** [comment]
とりあえずQuillベースで最短でやりたいことを実現するならば、

HTMLを書き込めるようにする
https://github.com/benwinding/quill-html-edit-button

を実装するのが早そう。（画像はどっか別のところに置く）

**Comment by mcyph** [comment]
@halsk はい、あまりよく取り組んでいないけど例のライブラリーを使って基本機能を加えました！長い間試したことがありませんけど、大まかなテストでは動けそうですので、PRを作りました。

画像などを入れるMarkdownエディタはほぼ半分書いていますけど、完了までは4日間ぐらいかかるそうですし、このパッチではいますぐリリースできますし、とりあえずこれでいいかもしれませんね。

**Comment by halsk** [comment]
ありがとうございます！！確認します

**Comment by halsk** [comment]
@mcyph うまく動いたので、本番に適用しました！ありがとうございます！
暫定対応ということで、Issue はこのままオープンにしておきます。

**Comment by halsk** [comment]
@isaozz とりあえず、ディベートコンポーネントで HTMLタグを使えるようになりました。
編集時に、`<>` というアイコンが増えていますので、そこでHTMLタグを直接入れてください。
画像を貼り付けたい場合
`<img alt="画像の名前" src="画像URL"/>`
 でいけます。
例（画像の内容が違うのはすみません）
https://kakogawa.diycities.jp/processes/smartcity/f/5/debates/5

ただし、現状以下の制約があります。
* 管理画面から画像アップロードはできない
* 2回めに編集しようとするとimg

**Comment by halsk** [comment]
@mcyph さん
現状↑のような感じです。提案コンポーネントでは、HTMLタグがサニタイズされました。（ディベートではOK）
また、提案コンポーネントでもディベートコンポーネントでも、2回めに編集しようとするとタグの内容が消えますね。
とりあえず暫定対応版なので、Markdown対応で修正されるなら対応する必要は無いかと思います。

**Comment by mcyph** [comment]
@halsk はい、伝えてくれてありがとう！すみません、どうして気づかなかった分からないけど2回めのバグを直すPRを送りました。原因はQuillの`formats`がHTMLタグをストリップするということです。

**Comment by halsk** [comment]
なるほど！了解しました
