### ISSUE TITLE
動作検証用アプリサーバがあると便利？

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/decidim-cfj#110]
## 改善詳細 / Details of Improvement

加古川市さんのサーバが本運用に入ってしまったので、検証用に好きなデータを突っ込めて、管理画面も確認できるサーバがあった方がよいかも、と思いました。
現状では、挙動を試せるのは手元で開発サーバを動かせるひとだけ、ということになってしまっているため、ちょっとハードルが高そうです。

#56 のCDとも関連しそうです。masterブランチの最新が反映されると良いでしょうか。

## 期待する見せ方・挙動 / Expected behavior
検証用のデータが登録されていて、普通に動いている状態です。

管理権限のアカウントの管理は要検討かもしれません（そうでもない？）。

## 対象インスタンス / Instances
- 全て

**Comment by halsk** [comment]
そうですね。
日本版のデモサーバーを用意したいですね。
本家のはこちら
https://demo.decidim.org/

- 1日に1回最新のmasterをdeploy
- db:seed を実施して、db も毎回クリアする

でいけますかね。EC2 に環境作って capistrano で更新？
メールの設定とかは別途必要か。

あと、今のfogを使って生成されるランダムデータが不穏すぎるので、変えたいところ。

**Comment by takahashim** [comment]
https://github.com/AjuntamentDeTerrassa/decidim-terrassa はHeroku Deployボタンがついているので、似たような作りをすればherokuにpushするのがお手軽かもしれません。
また #56 でコンテナ化できればそれを使うのも良さそうです。

**Comment by takahashim** [comment]
Fakerは2.x系にアップデートできればもう少し穏当な文言に変わってるみたいなのですが、引数のbreaking changeがあるのでちょっと適用が難しそう。
最新の

**Comment by komtaki** [comment]
ちょうど、デプロイまわりを見るためにも、Elastic beanstalkにコンテナ動作環境が欲しかったところです。

https://github.com/codeforjapan/decidim-cfj/pull/68

軽く触った感じ、問題なさそうな気がするのですが。decidimの本家のrspecを上手く使えば、ある程度は検証できると思うので、試行錯誤してます。:thinking:

**Comment by komtaki** [comment]
どのくらいちゃんと動くかわからないですが、上記コンテナでGithubActionsでビルドして、Elastic beanstalkデプロイするテスト環境作成しちゃってもいいですか？

**Comment by halsk** [comment]
@komtaki はい。お願いします！

**Comment by komtaki** [comment]
@halsk 

こんな感じで、ECRのレポジトリにgithub Acitonsからpush したいので、Github settingsに下記のSecretを登録してほしいです。
https://dev.classmethod.jp/articles/github-action-ecr-push/

私の権限だとみれなそうなので。お手数ですが、よろしくお願いします。

- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_ECR_REPO_NAME -> 887442827229.dkr.ecr.ap-northeast-1.amazonaws.com/decidim-cfj

**Comment by halsk** [comment]
設定しました！

![image](https://user-images.githubusercontent.com/16509/97794504-6a2fce00-1c3e-11eb-9377-42eaff01f92c.png)

**Comment by komtaki** [comment]
ありがとうございます。 👏

**Comment by komtaki** [comment]
上記、私の書き方が間違ってました。設定が見えないので、念の為訂正させてください。

AWS_ECR_REPO_NAME -> 普通にレポジトリ名でした。decidim-cfjですかね。

それと、デプロイで2点確認させてください。

- 定時実行なら、staging デプロイは、何時がいいでしょう。毎日18時とか？
- デプロイ完了通知はslackでもいいですか？

Githubでは、ecrにpushするところまでやります。後ろで、ecrのpushに反応して、codepiplineが自動でデプロイするイメージです。その結果をボットがslackに流します。

これが一番楽そうです。

**Comment by halsk** [comment]
AWS_ECR_REPO_NAME を修正したつもりが別のSecretを修正した？
18時に action が kick されましたが、失敗してしまいました。
もう一度流してみます。

**Comment by komtaki** [comment]
> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

AES のSECRTS KEYが間違っているかもと言われてますね。:thinking:

**Comment by halsk** [comment]
お、なるほど。了解しました。ちゃんと設定しなおしたので、大丈夫なのではないかと思います。よろしくおねがいします。

**Comment by komtaki** [comment]
CD確認用に適当に作ったstagingサーバーを、準本番用にちゃんと作り直そうとしてます。

動作ランタイムが違うと環境が複製できないみたいなので、ちょっと確認させてください。

root直下にある、このファイル群 `./ebextensions`は最新のものであってますか？
設定だと、インスタンスタイプがt2.microになっているのですが、production環境はt2.smallぽいので、よくわからず。 🤔
 
https://github.com/codeforjapan/decidim-cfj/blob/master/.ebextensions/00_options.config#L5

そこまでElastic Beanstalkは詳しくないので、勘違いしていたらすみません。

大味、本番と変更する箇所は、下記ですかね。

- インスタンスのt2.microへのダウン
- 起動時のmigrationの実行
- オートスケールの無効化

**Comment by halsk** [comment]
./ebextensions は最新ではないですね。。

これでdeployしたあとに、Elastic Beanstalk 上で設定変更していることがいくつかあります。
例えば・・・

## 4. Secret Key Base を設定

```
eb setenv SECRET_KEY_BASE=$(bin/rails secret)
```

## 5. Postgres データベースを作成する

EB コンソールの該当環境から、Configuration を選択、Database を選択し、Edit をする

必要な設定を行い、DBを立ち上げる

その後`eb deploy`を再度実行

## 6. Healthcheck の条件を変更

`/` が301を返すので、一旦 301 でもOKにする

Elastic Beanstalk の Configuration 画面で、Health Check を選び、Process の条件を 80 から 301 にする
![](https://i.imgur.com/VNZDQxA.png)
![](https://i.imgur.com/j595JQF.png)


## 7. CNAME 設定とSSL設定

Elastic Beanstalk のインスタンスをAレコードとして割り当てる

ロードバランサの設定をする（手順[6.2 Configure SSL](https://platoniq.github.io/decidim-install/decidim-aws/#62-configure-ssl)）

## 8. 最初のユーザを作る

[6.3 Create the first admin user](https://platoniq.github.io/decidim-install/decidim-aws/#63-create-the-first-admin-user)
に従う(root で)

## 9. SES の設定をする

[6.4 Setup email](https://platoniq.github.io/decidim-install/decidim-aws/#64-setup-email)

## 10. REDIS の設定をする

[6.5 Configure the job system with Sidekiq and Redis](https://platoniq.github.io/decidim-install/decidim-aws/#65-configure-the-job-system-with-sidekiq-and-redis)


## 11. S3 の設定をする

[6.6 File storage](https://platoniq.github.io/decidim-install/decidim-aws/#66-file-storage)

**Comment by komtaki** [comment]
ありがとうございます。:bow:

手順があるんですね。確認します。

**Comment by halsk** [comment]
手順8の、ユーザーを作るというのは db:seed をやるなら必要無いです。
その他の設定は、一度実施してしまえば、eb deploy などを使ってアップデートする分には必要無い作業です。

**Comment by komtaki** [comment]
ALBも入ってるので、他も結構変わってますね。
Cloud Formerで設定をまるごと引き抜いて、調整してます。

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/cfn-using-cloudformer.html

**Comment by komtaki** [comment]
ドメインは適当にstaging.diycities.jpで作成しました。変えて下さい。

本番モードだと、Fakerが入ってなかったので、db:seedが実行できませんでした。そうしたんでした。
管理ユーザーのID, パスワード管理とかどうしましょう？

https://staging.diycities.jp/system/admins/sign_in

基本、リソースをスケールダウンしてます。あとで設定を上げます。

**Comment by halsk** [comment]
@komtaki ありがとうございます！！
staging.diycities.jp で、良いと思います。
mailcather 入れたいですね。

**Comment by komtaki** [comment]
sesの設定しました。現状mailcatcher上手く入れられなさそうだったので。:bow:
