### ISSUE TITLE
メッセージのリンクに「_（アンダーバー）」がある場合省略される

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#129]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- メッセージのリンクに「_（アンダーバー）」がある場合省略されてしまい、ページがない状態となる。
- 「https://www.mext.go.jp/content/20191225-mxt_syoto01_000003278_03.pdf」を貼り付けると
- 「https://www.mext.go.jp/content/20191225-mxtsyoto01000003278_03.pdf」となってしまっている。

## 期待する見せ方・挙動 / Expected Behavior
- 貼り付けたとおりのリンクとしたい。

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takahashim** [comment]
これは現象が確認できていないのですが（すみません）、`https://www.mext.go.jp/content/20191225-mxt_syoto01_000003278_03.pdf`の文字列をMarkdownで解釈してしまって、`_syoto01_`が強調のマークアップだと誤解されてしまっているのではないかと思われます。

この推測が正しければ、対応策は以下の2点になりそうです。

* Markdownエディタが記法を解釈するタイミングをなんとかする修正を行う
* 現状での回避策として、 `[https://www.mext.go.jp/content/20191225-mxt_syoto01_000003278_03.pdf](https://www.mext.go.jp/content/20191225-mxt_syoto01_000003278_03.pdf)`といったMarkdownのリンク記法を使う

**Comment by halsk** [comment]
@isaozz 
上にあるように、リンクを貼る際に、

```
[https://www.mext.go.jp/content/20191225-mxt_syoto01_000003278_03.pdf](https://www.mext.go.jp/content/20191225-mxt_syoto01_000003278_03.pdf)
```

と記述してみてもらえますか？
