### ISSUE TITLE
最新の master を本番に適用すると JavaScript error が発生

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#130]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- 最新の master を使い `eb deploy` をしたところ、JavaScript のエラーが出て、コメントが表示されない、管理画面の動作がおかしいなどの不具合が発生したため、切り戻しを行った
- ちなみに、ローカル環境では問題が無い

切り戻しを行う際、Beanstalk の version を消せば実現できるかと思ったが、以下のような問題が発生したため、古いバージョンを codecommit の master に設定したのち新たに production2 という環境を作り DNS を変更することで対応した。

### エラーが発生してバージョンが戻せなかった

```
Failed Environment update activity. Reason: Configuration validation exception: RDS DB Engine Version option setting is not allowed to changed
```
AWS Console から RDB のサイズを t2.minimum から t2.small に変更していたからかと思われる

### eb deploy ができなくなった

以下のエラーが出て eb deploy が失敗するようになってしまった

```
No Application Version named 'app-a6b9e-201107_012429' found.
```
Console から version を消したから？

## production2 を作った手順

- `eb create production2` で環境を作る
- `eb deploy`
- 生成された環境の environment に、production の環境変数をコピー
- 既存のDBの snapshot を利用して新しい RDB を作成（Beanstalk の設定から作った）
- DNSを変更
- Loadbalancer で HTTPS を有効に

## スクリーンショット / Screenshot

<img width="1552" alt="Screen Shot 2020-11-06 at 21 49 00" src="https://user-images.githubusercontent.com/16509/98421956-e9edea80-20cd-11eb-828a-e7ec4d737347.png">

## 期待する見せ方・挙動 / Expected Behavior
- 正しく表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. staging でも発生するかどうか確認したい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
staging.diycityes.jp からサイト作成してみました。

stagingtest.diycities.jp でも同じエラーがでますね。どなたか心当たりある方いますか？

![image](https://user-images.githubusercontent.com/16509/98436807-d2405180-2121-11eb-89ce-5cb7d684f438.png)

**Comment by takahashim** [comment]
諸般の事情でただいま開発環境が吹っ飛んでしまって動かせないのですが、jQueryが読み込まれるよりも先にjQueryを使おうとしているように見えます。asset pipelineの扱いを変更されたりしました？

**Comment by halsk** [comment]
@takahashim 
特にそういう記憶は無いのですが、もう一つ環境作って、どのコミットでおかしくなるのか確認してみます。

**Comment by komtaki** [comment]
素人意見ですが、 @takahashim さんのこれが怪しそうです。stagingでjsエラーになっている箇所をよく見ると下記ぽいです。

![キャプチャ](https://user-images.githubusercontent.com/39375566/98459506-cebed000-21de-11eb-8da1-381a9a03e39a.JPG)


https://github.com/codeforjapan/decidim-cfj/pull/86

**Comment by komtaki** [comment]
私の方で、上記MRを除外してstagingにデプロイしたら、エラーが消えました。

https://stagingtest.diycities.jp/

ブランチはこれです。
https://github.com/komtaki/decidim-cfj/runs/1369791965?check_suite_focus=true

**Comment by halsk** [comment]
@komtaki 確認ありがとうございます！
#131 で修正してみましたので、今の master で staging 更新してみていただけますか？

**Comment by komtaki** [comment]
承知しました。しばしおまちを。

**Comment by komtaki** [comment]
デプロイされました。エラーは出てないです。　👏 

https://stagingtest.diycities.jp/

ブランチ
https://github.com/codeforjapan/decidim-cfj/compare/master...komtaki:staging

Pipeline
https://github.com/komtaki/decidim-cfj/runs/1369960374?check_suite_focus=true

**Comment by halsk** [comment]
本番に適用しました！無事エラーがなくなりました。
