### ISSUE TITLE
本番の管理画面で、ユーザ情報を表示しようとするとJS Error

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#132]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
管理画面で、新規追加したユーザ情報の表示をしようとすると、表示はされるが画面遷移してしまう
JavaScript Error が出現

#130 と似たような原因だと思われる

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/98463361-12750200-21fe-11eb-84f0-e3ad00a64b76.png)

![image](https://user-images.githubusercontent.com/16509/98463438-99c27580-21fe-11eb-88e4-66d920c684b8.png)

## 期待する見せ方・挙動 / Expected Behavior

- 画面がモーダルウインドウで表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 管理画面にいく
2. 参加者一覧を表示する
3. ユーザーアイコンを表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
あ、でもよく考えたら、 JS Error がでちゃってるのは、本来ポップアップウィンドウで出るはずの情報が、単独画面で表示されてしまっているからですね。直接の原因ではないかも

**Comment by takahashim** [comment]
確認が遅くなってしまってすみません。こちらも #130 と同様、 #86 の問題のようです。
開発環境ではassetは統合しないで動かすので特に問題は起きなかったのですが、`config.assets.debug = false` にすると再現しました。
