### ISSUE TITLE
Facebook 経由で登録すると、詳細情報を入力しなくても済んでしまう？

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#134]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- Facebook 経由で登録をした場合、詳細情報（氏名、住所等）を入力しなくても済んでしまう

## 期待する見せ方・挙動 / Expected Behavior
- Facebook 経由で登録した場合も、詳細情報入力を必須とする

## 起こっている問題の再現手段 / Steps to Reproduce
1. Facebook 経由で登録する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takahashim** [comment]
この件については、

* [ ] Facebook経由で新規登録する際に、どこかのタイミングで追加の属性情報を入力してもらう（入力しない場合は登録が完了しない）
* [ ] 追加の属性情報を登録していない人がいた場合、ログインのタイミング等で属性情報を入力するページに遷移させる（入寮しない場合はログインが完了しない）

といった変更を追加する必要があるかと思います（そしてどちらもちょっと厄介）。まずは前者の対応が必要そう。

**Comment by takahashim** [comment]
related to: #79

**Comment by halsk** [comment]
失礼しました。既にIssue上がってましたね・・

**Comment by halsk** [comment]
#139 で解消されているのでクローズします。
