### ISSUE TITLE
翻訳に関するIssue「コメントメール」

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#141]
## 改善詳細 / Details of Improvement
- フォローしているプロセスに対してコメントがあった際にメールが届くが、その時のメールの翻訳がおかしい
-  （１）（２）メールタイトル
-  （３）（４）メール本文 

## スクリーンショットなど / Screenshot
![スクリーンショット 2020-11-16 21 11 30](https://user-images.githubusercontent.com/40754081/99251660-0c5fd080-2851-11eb-94d7-539b0ca6fd71.png)

## 期待する見せ方・挙動 / Expected behavior
- （１）（２）「電子太郎 に 2.安全・安心のまちづくり から新しいコメントがあります」　を　「電子太郎 から 2.安全・安心のまちづくり に対して新しいコメントがあります」
- （３）「2.安全・安心のまちづくり はコメントされました」　を　「2.安全・安心のまちづくり にコメントがありました」 
- （４）「"2.安全・安心のまちづくり"またはその著者をフォローしているため、」　を　「2.安全・安心のまちづくり をまたは参加者をふぉろーしているため、」

## 対象インスタンス / Instances

- 全て

**Comment by halsk** [comment]
修正完了。
