### ISSUE TITLE
翻訳に関するIssue（通知メール）

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#146]
## 改善詳細 / Details of Improvement
- Decidimからの通知メールの翻訳について、
-「3 のバッジがレベル ディベート に達しました！」これはどういった意味なのか不明。おそらくディベートのバッジレベルが3になったという意味なんでしょうね。
- メールタイトルは「バッジ」ですが、本文は「バッヂ」となってます。 
- 「当社のウェブサイトでアクティビティを行ったため」とありますが、加古川市の事例であれば、「加古川市 市民参加型合意形成プラットフォームでアクティビティを行ったため」ぐらいの表現のほうがわかりやすいかもしれません。

## スクリーンショットなど / Screenshot
![スクリーンショット 2020-12-12 8 58 36](https://user-images.githubusercontent.com/40754081/101966350-c6810700-3c5a-11eb-97af-6218b13724d3.png)

## 対象インスタンス / Instances
- 全て

**Comment by halsk** [comment]
#141 と一緒に修正してきました。
