### ISSUE TITLE
本名、住所、性別、職業の入力を必須にするか、インスタンスごとに選べるようにする

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#150]
## 改善詳細 / Details of Improvement
- #1 で加古川仕様に導入した、追加の属性情報だが、インスタンスによっては必要ないので、設定画面で表示・非表示を選べるようにしたい
- 各インスタンスの管理画面ではなく、メイン管理者が組織を作成する際に項目を追加する

## スクリーンショットなど / Screenshot

この画面の下の方にチェックボックスの項目を追加したい

![image](https://user-images.githubusercontent.com/16509/104669561-9f1bcf00-571d-11eb-95ae-f18d0e1906cb.png)

## 期待する見せ方・挙動 / Expected behavior
- 組織作成/編集画面の、`Force authentication` と `Users registration mode` の間くらいに、
- `氏名、住所等の追加属性を利用可能にする` というチェックボックスを追加する（項目ごとにカスタマイズできると更に良いが、大変そうなら一括でOK）

## 対象インスタンス / Instances

- 全て

**Comment by takahashim** [comment]
どちらかというと、追加の属性情報部分をgemに切り出した上で、必要なインスタンスにはGemfileにそのgemを追加する、という対応方法が簡単・確実そうに思えるのですが、ひょっとして[マルチテナント](https://github.com/decidim/decidim/tree/develop/decidim-system#multi-tenancy-in-decidim)で運用する（1つのRailsアプリケーションで複数のインスタンスをホストする）予定でしょうか？

### 参考情報: 画面について

上記の画面生成については、  [decidim-system/app/views/decidim/system/organizations/new.html.erb](https://github.com/decidim/decidim/blob/develop/decidim-system/app/views/decidim/system/organizations/new.html.erb) のファイルがビューになっているはずです。

そのため、画面上で有効・無効を設定できるようにするには、

* app/overides/ 以下に差分のファイルのみ追加してdefaceで何とかする
* app/vies/decidim/system/organizations/new.html.erb を追加（decidim-systemを上書き）してファイル全体を差し替える

のどちらかになりそうです。

それに加えて、インスタンスごとの設定情報をどこに保存するかを考えておく必要があります。

**Comment by halsk** [comment]
> ひょっとしてマルチテナントで運用する（1つのRailsアプリケーションで複数のインスタンスをホストする）予定でしょうか？
はい。Decidim はそういう思想ですよね。既に、加古川市以外でも利用を想定しています。

要件を実現する方法として、この機能を無効にしたインスタンスを別に立てて、属性を取りたくない場合はそちらを使う、という方法があるわけですね。

**Comment by takahashim** [comment]
こちらの件ですが、別サーバ（別インスタンス）を用意しなくても、システム管理画面の「組織」の編集画面で「Available authorizations」のところにチェックを入れる／入れないによって、そのインスタンスで入力必須にする／しないを設定できるように修正できるかもしれません。

<img width="1101" alt="スクリーンショット 2021-01-31 19 39 47" src="https://user-images.githubusercontent.com/10401/106381519-a836bc80-63fc-11eb-8a98-901c0315948f.png">

（この画面、翻訳が抜けてるところがありますね…。上の「ユーザー追加属性登録」は仮に訳出してYAMLに追加したものです。）
