### ISSUE TITLE
提案コンポーネントで画像貼り付けて投稿できるようにした

### ISSUE THREAD

**Issue by kken78** [codeforjapan/decidim-cfj#162]
## 改善詳細 / Details of Improvement
- 提案コンポーネントで新しい提案を作成する際、本文に画像を貼り付けられたら内容がわかりやすい
- 画像エディタからCtrl+A→Copy&Pasteで貼り付けると、blobになるので文字数上限エラーとなって投稿できない

## スクリーンショットなど / Screenshot
貼り付けることはできるが、「残り-210935文字」というすごい数字に
![image](https://user-images.githubusercontent.com/35302518/108715407-2e5aa480-755e-11eb-92a8-c59735ae8353.png)

HTMLソース上は、imgタグにblobが入力されている
![image](https://user-images.githubusercontent.com/35302518/108715487-49c5af80-755e-11eb-99b2-10dd4d9701a2.png)

## 期待する見せ方・挙動 / Expected behavior
- 画像を貼り付けたい

## 対象インスタンス / Instances

- 全て

**Comment by takahashim** [comment]
これも
