### ISSUE TITLE
翻訳に関するIsuue（退会者の表示）

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#165]
## 改善詳細 / Details of Improvement
- コメントを行った参加者が退会した際に、コメントは残るもののユーザー名が「参加者を削除しました」となっており、管理者側が削除したように見える

## スクリーンショットなど / Screenshot
![スクリーンショット 2021-02-24 22 20 01](https://user-images.githubusercontent.com/40754081/109006783-bf608580-76ee-11eb-9b22-2dca1197b6f2.png)

## 期待する見せ方・挙動 / Expected behavior
- 「退会した参加者」などの文字に変更する

## 対象インスタンス / Instances

- 全て

**Comment by takahashim** [comment]
こちらについては、 #97 で修正していたようですが、これに問題があったようなので #164 の修正と合わせて対応してみます（別のpull requestに分けるとconflictしそうだったので…）
