### ISSUE TITLE
masterブランチをデフォルトブランチにしdevelopブランチを削除する

### ISSUE THREAD

**Issue by doyaaaaaken** [codeforjapan/decidim-cfj#17]
背景理解していない上での提案となります。（的外れでしたらすみません...）

こちらのIssueにて https://github.com/codeforjapan/decidim-cfj/issues/2#issue-723999399

> master ブランチが最新。develop ブランチは生成時から使っていない

と記載されており、今developブランチがデフォルトブランチになっているようなので、消しても良さそうに感じました。

※ デフォルトブランチはここから変えられます
![image](https://user-images.githubusercontent.com/5428401/96604386-05b46b00-1330-11eb-818a-e15ecded7397.png)

**Comment by halsk** [comment]
対応しました。
