### ISSUE TITLE
新規登録時の必須項目欄に「*」が表示されていない

### ISSUE THREAD

**Issue by kken78** [codeforjapan/decidim-cfj#170]
## 対象ドメイン/ The domain
- 全て

## 起こっている問題 / The Problem
- 新規登録画面に遷移した際、「本名」「住所」「生年（西暦）」「性別」「職業」に「*」がついていない
- 空欄のまま登録しようとすると本名〜性別、までは必須ですって怒られる
- 職業は「*」がないまま

## スクリーンショット / Screenshot

<img width="772" alt="スクリーンショット 2021-02-26 9 55 44" src="https://user-images.githubusercontent.com/35302518/109246249-3730cc00-7825-11eb-8d64-bedc081c8e8f.png">
<img width="971" alt="スクリーンショット 2021-02-26 9 56 00" src="https://user-images.githubusercontent.com/35302518/109246264-3d26ad00-7825-11eb-9356-34a1e845cfe3.png">

## 期待する見せ方・挙動 / Expected Behavior
- 新規登録時の入力必須項目（「本名」「住所」「生年（西暦）」「性別」「職業」）に*をつける
- 未入力時のエラー表示も同様

## 起こっている問題の再現手段 / Steps to Reproduce
1. 新規登録画面にアクセスする
2. 「本名」「住所」「生年（西暦）」「性別」「職業」を未入力のまま新規登録ボタンを押下

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari

**Comment by takahashim** [comment]
これはJavaScript側でうまく検出できてないということのようですね。なんとか直してみます…

**Comment by halsk** [comment]
#171 を修正したらこちらも修正された模様です

**Comment by takahashim** [comment]
#175 で追加の修正を行っております
