### ISSUE TITLE
Facebookログインができない

### ISSUE THREAD

**Issue by kken78** [codeforjapan/decidim-cfj#177]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- Facebookログインを有効にした上で、新規登録でFacebookログインしようとすると「サーバーに問題が発生しました」となって登録できない 

## スクリーンショット / Screenshot

![IMG_2388](https://user-images.githubusercontent.com/35302518/109927976-4a053e00-7d08-11eb-8c02-5783c43f016a.PNG)

## 期待する見せ方・挙動 / Expected Behavior
- Facebookログインで新規登録ができるようになる

## 起こっている問題の再現手段 / Steps to Reproduce
1. Facebookログインを有効にする（アプリID、シークレットの入力：ここの設定問題なのか切り分けはできていない）
2. 新規登録画面で、Facebookログインを選択
3. Facebookへ遷移し、FBアカウントでログインをする
4. Decidimへ遷移するが、スクリーンショットのようなメッセージが出る

## 動作環境・ブラウザ / Environment
- macOS / iOS
- Chrome / Safari

**Comment by kken78** [comment]
ちなみに、当該サイトでは現在はFacebookログインは無効化している

**Comment by takahashim** [comment]
確認してみたところ、ユーザー拡張属性について、ソーシャルログイン周りの修正が足りていないようでした。

関連しそうなファイル一覧(decidim-core):

- [ ] app/commands/decidim/create_omniauth_registration.rb
- [ ] app/controllers/decidim/devise/omniauth_registrations_controller.rb
- [ ] app/forms/decidim/omniauth_registration_form.rb
- [ ] app/helpers/decidim/omniauth_helper.rb
- [ ] app/models/decidim/omniauth_provider.rb
- [ ] app/views/decidim/devise/omniauth_registrations/new.html.erb
- [ ] app/views/decidim/devise/shared/_omniauth_buttons.html.erb
- [ ] app/views/decidim/devise/shared/_omniauth_buttons_mini.html.erb
