### ISSUE TITLE
ヒーロー画像が更新されない

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#18]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- 設定→ホームページ→ヒーロー画像からアップロードした画像が反映されない

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/96659084-0fb28a00-1381-11eb-9290-e4b012c08a59.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正しくヒーロー画像がアップロードされる

## 起こっている問題の再現手段 / Steps to Reproduce
1. Decidim で組織を作る
2. その組織の管理画面で、設定→ホームページ→ヒーロー画像から画像をアップロードする
3. 反映されない

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
ちなみに、以前（2週間くらい前）のバージョンでは反映されていた

**Comment by halsk** [comment]
release/0.22-stable  にしたところ、機能が復活しました。どうしようかな。日本語訳が古いんだよな

**Comment by halsk** [comment]
とりあえず本家にも報告済

**Comment by halsk** [comment]
一旦画像アップロードしたので、この状態でバージョンを戻します。他のIssueを優先。

**Comment by doyaaaaaken** [comment]
本家への報告Issueリンク
https://github.com/decidim/decidim/issues/6720#issue-726453384

**Comment by halsk** [comment]
#57 で修正された。
@mcyph さん、本家にもパッチ送ってあげると喜ばれると思います！
