### ISSUE TITLE
フロント側にWAFを置きたい

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#180]
## 改善詳細 / Details of Improvement
- フロント側のセキュリティ向上のためにWAFを置きたい
- ほかの手段も要検討

## 期待する見せ方・挙動 / Expected behavior
- WAF にこだわるものではないが、不正アクセスの監査やブロックを行うことを検討したい

## 対象インスタンス / Instances

- 全て

**Comment by komtaki** [comment]
@ayuki-joto

Cloud Frontの導入が済んだので、こちら検討しようかと思います。

AWS WAFは安く、カスタマイズ性が高い、また導入が簡単です。
そのためstagingでカウントモードでルールを組んでみようと思いますが、問題ないでしょうか？

その後、ルールをチューニングしつつ本番に入れられるか検証する流れを考えています。:+1:

**Comment by ayuki-joto** [comment]
@komtaki 
ぜひ！お願いします！

**Comment by komtaki** [comment]
@ayuki-joto 

上記4ルールプラス下記で、全部盛りにしてみました。

- AWSManagedRulesAmazonIpReputationList

stagingで普通にざっと触って全て正常リクエストでした。またSQLインジェクションぽいURLを叩き、AWSManagedRulesSQLiRuleSetで検知されましたがブロックはされずカウントのみになっていることは確認しました。

ただ予想以上にアクセスがないので、本番にもカウントモードで入れたいです。
本番用のwafを作成したので、確認をお願いします。

**Comment by komtaki** [comment]
問題なさそうなので、本番にカウントモードでアタッチしました。 👍

**Comment by ayuki-joto** [comment]
@komtaki 
対応ありがとうございます！
ちなみにWAFで特定のURLのみアクセスをブロックするようなことは可能でしょうか？
#254 ここで問題になっていたURLに対して，robots.txtを無視してクローリングしてくるbotがいるので一旦WAFで手間がかからず対応可能なら止めてしまいたいと思っています！

**Comment by komtaki** [comment]
> ちなみにWAFで特定のURLのみアクセスをブロックするようなことは可能でしょうか？

可能です。ただ現状のWAFルール「NoUserAgent_HEADER」でも、悪質と判定されているボットアクセスが数百あるので、まずはそちらを有効化したいです。カスタマイズしなくても除去できるかもしれないので。

https://docs.aws.amazon.com/ja_jp/waf/latest/developerguide/aws-managed-rule-groups-list.html

**Comment by ayuki-joto** [comment]
@komtaki 
なるほどそちらも別途対応した方が良さそうですね．
ただ現状問題となっている部分に関しては，海外の検索エンジンからのbotというのはuser-agentからわかっているので，こちらの対応も必要かと思っています！

**Comment by komtaki** [comment]
@ayuki-joto 

- AWSManagedRulesKnownBadInputsRuleSet
- AWSManagedRulesLinuxRuleSet
- AWSManagedRulesSQLiRuleSet
- AWSManagedRulesAmazonIpReputationList

ご検知がなさそうな上記4ルールを本番でブロックモードにしました。

下記はしばらく様子見て調整します。また海外の検索エンジンからのbotの件を確認するので、Botのユーザーエージェントを教えてもらえると助かります。

- AWSManagedRulesCommonRuleSet

**Comment by komtaki** [comment]
本番もAWSManagedRulesCommonRuleSetを有効化しました。

**Comment by komtaki** [comment]
本番導入後、問題なさそうなのでクローズします。

Botの件もインスタンススケールアップ&wafの導入で現状大丈夫そうです。

また何かあれば別途issueをたててください。:bow:
