### ISSUE TITLE
「参加者の設定 - 権限」ページがエラーで表示されない

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#187]
## 対象ドメイン/ The domain
- shibuyatest.diycities.jp

## 起こっている問題 / The Problem
- /authorizations で500エラーが発生する

## スクリーンショット / Screenshot
![スクリーンショット 2021-03-17 22 31 55](https://user-images.githubusercontent.com/3460170/111476353-6f1a9780-8771-11eb-859c-f5fb19050e0a.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正しい画面の表示

## 起こっている問題の再現手段 / Steps to Reproduce
1. 参加者としてログイン
2. 上記ページを表示

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by takahashim** [comment]
こちらについて、現状でも  `/authorizations` にアクセスするとエラーが出ることがあるようでした。

開発環境で確認したところでは、`Decidim::Verifications.workflows`の値が`["id_documents", "postal_letter", "csv_census", "user_extension_authorization_handler"]`となるのですが、最後の要素は本来は`"user_extension"`になるべきのようです。

実際、user_extensionの`authorization.name`は`"user_extension`になっており、この値と`Decidim::Verifications.workflows`の値が異なることがエラーになる表層的な原因のようでした。
