### ISSUE TITLE
調査コンポーネントの管理ページがエラーで表示されない

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#188]
## 対象ドメイン/ The domain
- shibuyatest.diycities.jp

## 起こっている問題 / The Problem
- /admin/participatory_processes/{process_slug}/components/{id}/manage/ で500エラーが発生する

## スクリーンショット / Screenshot
![スクリーンショット 2021-03-17 22 31 55](https://user-images.githubusercontent.com/3460170/111476353-6f1a9780-8771-11eb-859c-f5fb19050e0a.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正しい画面の表示

## 起こっている問題の再現手段 / Steps to Reproduce
1. 管理者としてログイン
2. 任意の参加型プロセスにコンポーネント（調査）を作成
3. 管理をクリック

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by takahashim** [comment]
開発環境では `translation missing: ja.decidim.templates.admin.questionnaire_templates.form.title` というエラーが出るようでした。
どうもdecidim-templatesの読み込みがうまくいってない（？）ようです。
