### ISSUE TITLE
参加型プロセスの添付ファイルに画像をアップした際のフォルダ分け

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#192]
## 改善詳細 / Details of Improvement
- 参加型プロセスの添付ファイルとして画像をアップしフォルダに入れた場合、プロセストップページのフォルダ内ではなく関連画像のセクションに表示されていしまい、ユーザからすると少し分かりづらい
- 画像が別セクションに移動するため、フォルダ名の横に表示されるドキュメント数とフォルダ内のファイル数が不整合となる

## スクリーンショットなど / Screenshot
![スクリーンショット 2021-03-19 18 38 50](https://user-images.githubusercontent.com/3460170/111760849-875df400-88e2-11eb-94cc-613d58663575.png)

## 期待する見せ方・挙動 / Expected behavior
- フォルダに収めた画像ファイルはフォルダ内に表示されると明快
- フォルダ分けされていない画像のみ関連画像に表示する、もしくは、フォルダ内と関連画像に重複表示する

## 対象インスタンス / Instances

- 全て

**Comment by takahashim** [comment]
確認してみましたが、現状の画面構成ではドキュメント or 画像の分類が先に来ているため、素朴に修正すると「関連画像」の下位に画像用の各フォルダを配置するような形になってしまいそうです。あまり分かりやすくならないでしょうか……。

それはさておき、「フォルダ名の横に表示されるドキュメント数とフォルダ内のファイル数が不整合となる」というのはDecidimのバグのようです。こちらは普通に修正できるかと思います。

**Comment by takahashim** [comment]
……と思いきや、Decidim最新版ではつい最近（18日前）、添付ドキュメント数の表示には修正が入っていますね。ざっと見たところでは正しく表示されていそうです。

https://github.com/decidim/decidim/pull/7440/commits/1801780abb22a98968c5c2bcef3152d340dcc843#diff-61edaf31056cf5cbe7ded4be30e7faba766c28217fadcca396a6d900875112d9

**Comment by yusukesaitoh** [comment]
ご確認とご対応ありがとうございます。

アップロード時に画像とドキュメントの区別がないことを考えると、全て1セクションにまとめてフォルダ分けもそのまま表示する形が直観的で分かりやすいと思いますが、Decidim本体の実装に関わってきそうですよね。

> 「関連画像」の下位に画像用の各フォルダを配置するような形
この形でも現状より分かりやすくなっていると思います。
画像を分けている元々の意図が見えづらいため、何が適切な対応か難しいところはありますが……。

**Comment by takahashim** [comment]
@yusukesaitoh さん：

> Decidim本体の実装に関わってきそうですよね。

まさにその通りなのでした…。

正直なところ、現状のDecidimの設計思想のもと、画像をフォルダ分けしてうれしい（サイトが使いやすくなる）かどうかというところではありますが、#194 のような形でもフォルダ分けをした方がよいでしょうか？
場合によっては、画像についてはフォルダ分けしない前提で、ただしドキュメント数がおかしくなるバグだけ修正する、という対応も考えられるかと思いますが、どうでしょうか。

あるいは、積極的にフォルダ分けするべきユースケースがあれば、それを元にDecidim本家に対して交渉してみるという方向性もあるかもしれません。

**Comment by yusukesaitoh** [comment]
現在、Decidimの各機能がどのように利用できるか確認を進めているところでして、実運用ですぐに対応必須という状態ではありません。

想定したユースケースとしては、フェーズごとに頭出しの資料などをプロジェクトの分かりやすいところにアップロードできると便利かなと思いまして、zipは不可だったためフォルダ分けを使用してみた、という経緯になります。
ブログコンポーネントにもファイル添付ができるため、資料配布用にコンポーネントを作ることで同様の機能を実現できるのですが、やや大げさかなとも思います。

現状だと「参加型プロセストップ階層へのファイル添付」は管理者ユーザが適切な使い方をイメージしづらい機能になっている印象があるので、一度、本家Decidimがをどのような想定でこの機能を作っているか確認できると良いのかもしれません。
