### ISSUE TITLE
DEPLOYMENT.mdにNEW_RELIC_LICENSE_KEYなどの環境変数の情報を追加する

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/decidim-cfj#193]
## 改善詳細 / Details of Improvement

#186 でnew relicのgemが追加されましたが、これを実際に動かすには環境変数 `NEW_RELIC_LICENSE_KEY` と `NEW_RELIC_APP_NAME` の設定が必要なはずです（config/newrelic.ymlで参照してるみたいです）。

これはDecidim本家のサイトのデプロイ設定・手順等を見ても分からないことなので、設定が必要な情報はどこかに記しておきたいです。現状では `DEPLOYMENT.md` に書くのが良いかと思うのですが、どうでしょうか（他にも必要な項目がありそうなのでまとめて書いておきたい）。

## 対象インスタンス / Instances
- 全て

**Comment by halsk** [comment]
そうですね。各種設定値がどこにどう設定されているかは、DEPLOYMENT.md に記載するようにしましょうか。

**Comment by komtaki** [comment]
基本的には、ソースコードに落とした方がいいと思います。:eyes:

ただ、eb configで環境変数が、秘密鍵等がパラメーターストアで隠蔽できないんですよね。パスワードとか丸見えなのはまずいので、一旦`DEPLOYMENT.md`ですかね。 💦 

https://docs.aws.amazon.com/ja_jp/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkapplicationenvironment

ちょうどコンテナ化でかわるので、ざっと私が追記しておきます。

**Comment by komtaki** [comment]
こちらコードに落とされ、完了したのでクローズします。
