### ISSUE TITLE
管理者招待メールで「誰かから」の招待と表示されている

### ISSUE THREAD

**Issue by kken78** [codeforjapan/decidim-cfj#195]
## 改善詳細 / Details of Improvement
- 管理者招待メールの送信者が「誰か」となって、一瞬ぎょっとする
## スクリーンショットなど / Screenshot
<img width="874" alt="スクリーンショット 2021-03-22 10 06 40" src="https://user-images.githubusercontent.com/35302518/111928972-75ee3500-8af8-11eb-96bd-06d210492e87.png">

## 期待する見せ方・挙動 / Expected behavior
- すでに管理者がいる場合は、そのアカウント名で表示されるので、それはそのままでいい
- 完全に初めての場合は「管理者から」といった汎用的な表示にする（上記の場合もそれに統一するのもよいかと思う）

## 対象インスタンス / Instances
- 全て

**Comment by takahashim** [comment]
こちらですが、現状は以下のような文言があるようです。

```
        someone_invited_you: 誰かが %{application}にあなたを招待しました。以下のリンクから受け入れることができます。
        someone_invited_you_as_admin: 誰かが %{application}の管理者としてあなたを招待しました。以下のリンクから承認できます。
        someone_invited_you_as_private_user: '%{application}の非公開参加者としてあなたを招待しました。以下のリンクから承認できます。'
```

英文では以下のとおりで、その直訳になっています。

```
        someone_invited_you: Someone has invited you to %{application}. You can accept it through the link below.
        someone_invited_you_as_admin: Someone has invited you as an admin of %{application}, you can accept it through the link below.
        someone_invited_you_as_private_user: Someone has invited you as private participant of %{application}, you can accept it through the link below.
```

`someone_invited_you_as_private_user` に揃える形で、単純に `誰かが` を削除するのがいいでしょうか？

**Comment by kken78** [comment]
そうですね。英語独特の表現ですね。
日本語から直訳するならYou have been invited as ...みたいな言い方なんでしょう。
ということで、「誰かが」を削除する方法論がバランスよさそうです。
