### ISSUE TITLE
セットアップドキュメントを書く

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#2]
## 改善詳細 / Details of Improvement
- 開発者向けのドキュメントが必要！
- ローカルの開発環境づくりを試してみてほしい

## 期待する見せ方・挙動 / Expected behavior
- この環境は、[decidim コマンド](https://docs.decidim.org/en/install/manual/)を利用して生成されたものである
- master ブランチが最新。develop ブランチは生成時から使っていない
- master ブランチをチェックアウトして、[Configure the database](https://docs.decidim.org/en/install/manual/#_configure_the_database)あたりから進めるとインストールできるのではないかと思う
  - ちなみに、関は osx で bundle install 中にエラーが出たので Ubuntu 環境で開発をしている
- その手順を、DEVLOPMENT.md としてコミットし、pull request を送ってもらえると助かる

## 対象インスタンス / Instances

- 全て

**Comment by smellman** [comment]
https://github.com/codeforjapan/decidim-cfj/pull/6 これを適応した状態での開発環境作成

事前作業:
- rbenvのインストール
- PostgreSQLのインストール(postgresql 13にてテスト)

```
rbenv install 2.6.6
git clone git@github.com:codeforjapan/decidim-cfj.git
cd decidim-cfj
git checkout -b master origin/master
gem install bundler:1.17.3
export DATABASE_USERNAME=yourname
export DATABASE_PASSWORD=yourpassword
bundle install
bin/rails db:create db:migrate
vim config/initializers/decidim.rb
# 一旦default_localeを`:en`にセットする
bin/rails db:seed
vim config/initializers/decidim.rb
# default_localeを`:ja`に戻す
bin/rails -s -b 0.0.0.0
```
