### ISSUE TITLE
参加型プロセスのプライベート参加者をcsv経由でインポートした際、招待メールが届かないユーザがいる

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#202]
## 対象ドメイン/ The domain
- shibuyatest.diycities.jp

## 起こっている問題 / The Problem
- 参加型プロセスのプライベート参加者をcsv経由でインポートした際、招待メールが届かないユーザがいる
### 追記
- BOMありCSVをアップロードすると１行目のアドレスに不可視のバイトが付与されて不正なあどれすになってしまうことが原因か？

## 期待する見せ方・挙動 / Expected Behavior
- 全員に招待メールが届く
 
## 起こっている問題の再現手段 / Steps to Reproduce
1. 非公開の参加型プロセスにプライベート参加者をcsv経由でインポート
2. おそらく1行目のユーザのみ、管理画面の参加者リストには表示されるがメールが届かない（同一ドメイン[gmail.com]の複数メールアドレスを使用し再現を確認）
3. 管理画面の「招待を再送信する」ボタンを押しても問題のユーザのみメールが再送されない
4. 招待を削除し「新しい 参加スペースプライベート参加者」ボタンから手動追加すると招待メールが送信される

使用したCSVの例、この場合user_name_01のみメールが届かない。
```
user01@example.com,user_name_01
user02@example.com,user_name_02
user03@example.com,user_name_03
```

## 動作環境・ブラウザ / Environment
- macOS
- Chrome
- Mail

**Comment by takahashim** [comment]
試しにローカルの開発環境で確認したところでは、最初の配信はうまくいかなかったのですが（これは開発環境の問題かもしれません）、再送した際には全員分配信できたようでした。
`shibuyatest.diycities.jp` のメールのログも確認した方が良いかもしれません…。

**Comment by yusukesaitoh** [comment]
すみません、こちら再確認したところファイルの方に原因がありました！
アップロードしたcsvがBOM付きutf-8だったため、1行目のレコードのみ「不可視のBOM+メールアドレス」が登録されてしまったようです。
システムに詳しく無いユーザが操作する可能性がある画面なので、
- BOMがあった場合削除する処理の追加
- BOM無しのみアップロード許可

のいずれか対応できると良いのではと思います。

**Comment by yusukesaitoh** [comment]
また、これら不正なメールアドレスでも招待時にユーザが作成されるため、
- メール認証できない＝永久にログインできないユーザのプロフィールページが作成される
- 参加者一覧画面（/admin/officializations）からこれらのユーザを削除する方法がない（削除っぽい×ボタンはあるが無効）

という状態になります。
この2点は、新規登録や招待の際にメールアドレスを間違えた場合も問題になるかもしれません。
招待メールに期限がるため、もしかすると一定期間で未承認ユーザを自動削除する機能があるかも？とは考えています。

**Comment by takahashim** [comment]
とりあえず、BOMの不具合報告と、BOMを無視する修正を本家の方に投げておきました
https://github.com/decidim/decidim/issues/7780
https://github.com/decidim/decidim/issues/7781

参加者一覧の方はいろいろ機能が足りてなさそうですよね…。どうしたものか。
