### ISSUE TITLE
住所など追加のユーザ情報を非表示したドメインで、トップとヘルプ以外の全ページがエラーで表示できない

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#206]
## 対象ドメイン/ The domain
- shibuyatest.diycities.jp
- shibuya-goodtalk.diycities.jp

## 起こっている問題 / The Problem
- トップとヘルプ以外の全ページが「登録されていないユーザー属性情報が見つかりました。」というエラーで表示できない

## 期待する見せ方・挙動 / Expected Behavior
- ページの正常な表示

## 起こっている問題の再現手段 / Steps to Reproduce
1. 新規のサブドメインを本名、住所、生年、性別などを必須にした状態で開始
2. 後からこれらの入力項目を非表示にする。変更後の項目は、表示名、アカウントID、メールアドレス、パスワード
3. 変更後に新規登録したユーザは変更前の必須項目を持っていない

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari

**Comment by takahashim** [comment]
@yusukesaitoh ちょっと状況が分からないのですが、「起こっている問題の再現手段」について、もう少し具体的な手順は書けますか？（システム管理者として組織(organization)の編集画面で`User extension authorization handler (Direct)` のチェックボックスにチェックを入れたり外したりされている、というのであってますか？）

また「変更後に新規登録したユーザは変更前の必須項目を持っていない」というのはどうやって確認されたものでしょうか？

**Comment by kken78** [comment]
@takahashim 横からですみません。
・当初構築時は、User extension authorization handler (Direct)のチェックボックをON
・依頼により、当方で今回OFFにした
という流れです。

**Comment by yusukesaitoh** [comment]
@takahashim 
> 「変更後に新規登録したユーザは変更前の必須項目を持っていない」というのはどうやって確認されたものでしょうか？
変更前に登録したユーザではこのエラーが発生しないことから、ユーザ情報として保持する項目の差分が原因と推測しました。

エラー内容・現象としては #171 が近いため、類似の原因かもしれません。

**Comment by takahashim** [comment]
@kken78 @yusukesaitoh フィードバックありがとうございます！

まとめますと、

* ユーザーの拡張属性を取得する設定（User extension authorization handlerあり）で開始した
* あるタイミングで上記設定を変更（User extension authorization handlerなし）し、ユーザーの拡張属性を取得しないようにした
    * 変更後、住所等を取らずに登録ができるようになった
* その後、さらに設定を再変更（User extension authorization handlerあり）した
    * 変更後、住所等を取らずに登録した人は、トップとヘルプ以外のページが見られなくなった

という状況で合っているでしょうか？

そのようになるのが概ね正常ではありますが、ただログインすると自分のユーザー情報を更新するページに飛ばされて、そのページは閲覧できてほしい（そして記入すると通常通り全ページ閲覧できるようになってほしい）、というところです。そうなるようにしたつもりだったのですが、何か間違えていたのかもしれません（すみません…）。

細かい確認と修正は後ほど行いますので、少々お待ち下さい。

**Comment by yusukesaitoh** [comment]
@takahashim 
- ユーザーの拡張属性を取得する設定（User extension authorization handlerあり）で開始した
- あるタイミングで上記設定を変更（User extension authorization handlerなし）し、ユーザーの拡張属性を取得しないようにした
  - 変更後、住所等を取らずに登録ができるようになった

まではあっていて、
- その後、`User extension authorization handlerなし` の状態で新規登録したユーザのみ、トップとヘルプ以外のページが見られなくなった

という状態です。

確認された状況は、
- さらに`User extension authorization handlerあり` に変更するとエラーが解消する

ということになるかなと思います。

**Comment by takahashim** [comment]
@yusukesaitoh ちょっと追加で確認したいのですが、

> その後、`User extension authorization handlerなし` の状態で新規登録したユーザのみ、トップとヘルプ以外のページが見られなくなった

という状況について、「その後」というのは再度 `User extension authorization handlerあり` に変更した後でしょうか？　それとも何も変更していない（`User extension authorization handlerあり`のまま）状態でしょうか？

また、

> さらに`User extension authorization handlerあり` に変更するとエラーが解消する

というところですが、「エラーが解消する」というのは、「トップとヘルプ以外のページが見られるようになる」ということでしょうか？
（`User extension authorization handlerなし`（=新規登録ページで住所欄が表示されない）で登録した人が`User extension authorization handlerあり`（=新規登録ページで住所欄が表示される）の状態で全ページ見られる状態は何かおかしいはずなのです。）

**Comment by yusukesaitoh** [comment]
@takahashim 
- `User extension authorization handlerあり`で開始
- ユーザAが新規登録（拡張属性あり）
- `User extension authorization handlerなし` に変更
- ユーザBが新規登録（拡張属性なし）
- ユーザBのみ、トップとヘルプ以外のページが見られなくなった

という流れです。

**Comment by takahashim** [comment]
@yusukesaitoh  情報ありがとうございます。その流れで問題なさそう…と思ったのですが、最後の「ユーザBのみ、トップとヘルプ以外のページが見られなくなった」というのは、ユーザーBは登録した直後から一度も他のページが見えてない状態になる、ということですよね。これは防ぎたいところなので、修正してみます。
フィードバックありがとうございました！

**Comment by yusukesaitoh** [comment]
@takahashim 
色々とご対応ありがとうございます！
こちらの修正をshibuyatest.diycities.jpとshibuya-goodtalk.diycities.jpに反映していただくことは可能でしょうか？
今週木曜日に新規ユーザの登録を予定しておりまして、明日までに不具合が解消しない場合は、一旦「拡張属性あり」に戻して使用開始したいと考えています。

**Comment by kken78** [comment]
@yusukesaitoh 
ご心配おかけしています。開発MTGで対応方針確認しました。解消できているか検証を行った上で全体に反映させます。明日までに、というご事情は理解していますので、またご連絡します！

**Comment by ayuki-joto** [comment]
こちらの問題修正されましたのでissue closeします。
