### ISSUE TITLE
参加型プロセスのプライベート参加者をcsv経由でインポートした後、プライベート参加者ページがエラー

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#219]
## 対象ドメイン/ The domain
- shibuya-goodtalk.diycities.jp

## 起こっている問題 / The Problem
- 参加型プロセスの管理画面でプライベート参加者画面がエラーになる
- ページのパス  /admin/participatory_processes/{slug}/participatory_space_private_users
- エラー文言 「サーバーに問題が発生しました 後でもう一度お試しください。」

## 期待する見せ方・挙動 / Expected Behavior
- 正常に画面を表示する。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 非公開の参加型プロセスにプライベート参加者をcsv経由でインポート
2. プライベート参加者が表示される（新規招待した参加者のうち数件が表示されている）
3. 画面に再アクセスすると500エラー、それ以降は同様のエラーで表示できない

### 本日エラーになったcsv
```
bdsuser_0@example.com,bdsuser_0
bdsuser_1@example.com,bdsuser_1
...
bdsuser_36@example.com,bdsuser_36
bdsuser_37@example.com,bdsuser_37
```
のように38行のデータ（アドレスは伏せています）。
shibuya-goodtalk.diycities.jpで実行。

### 本日成功したcsv
```
bdsuser_0@example.com,bdsuser_0
bdsuser_1@example.com,bdsuser_1
```
のように2行のデータ。
shibuyatest.diycities.jpで実行。

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by takahashim** [comment]
こちらの件ですが、なんとなくpaginateで失敗しているようなので（そのため件数が少ないと問題が起こらず、件数が増えると発生する）、 https://github.com/decidim/decidim/pull/6986 で解決された問題かもしれません。
バックポートできるか調べてみます。

**Comment by yusukesaitoh** [comment]
@takahashim 
ご確認ありがとうございます！
現在、追加の参加者を招待することができない状態になっており、可能であればこの部分だけ早めにご対応いただけると助かります！

**Comment by ayuki-joto** [comment]
修正されたかと思いますのでcloseします
