### ISSUE TITLE
翻訳: `census`を「戸籍」か「住民票」に変更する

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/decidim-cfj#225]
## 改善詳細 / Details of Improvement

現在 `census`の訳語が「国勢調査」になっていますが、Decidimの文脈では「戸籍」とか「住民票」のような自治体が保有している住民のデータ（を使ってauthorizationを行うためのもの）になりそうなので、そのような用語に変更するのでどうでしょうか。

## 対象インスタンス / Instances

- 全て（ではありますが、実際にインスタンスで使うことはあまりなさそうです）

**Comment by kken78** [comment]
管理ダッシュボードのメニューでは「組織の国勢調査」「国勢調査データ」という使い方で、その実質はメールアドレスデータの一覧なので、「戸籍」とか「住民票」といった、役所用語に寄せない方がよさそうに思います（その目で見る人が勘違いしちゃいそう）。
他の「本人確認ドキュメント」による認証が自治体保有住民データでの話に近いように思います（とはいえ、こっちを使うようになる日はまだ遠そうですけど・・・）

また、使い方として、「一度に大勢に登録してほしいけど個人に登録作業をしてもらうとその作業へのヘルプ対応が大変」ということがありそうなので、一括してメールアドレスを入手して事務局で登録するという形が出てもきそうです（Decidimのユーザー属性にもよると思いますが、そういうことに慣れていない人の参加を増やそうという使われ方もあるので）。

ということで、
「リスト」くらいの訳語にして、「組織の国勢調査」は、「登録リスト」という意味合いはどうでしょう？

**Comment by halsk** [comment]
「センサス」にする方向で

**Comment by takahashim** [comment]
crowdinの方は「センサス」で統一しました
