### ISSUE TITLE
提案タイトルの文字数制限を弱めにする

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#23]
## 改善詳細 / Details of Improvement
- 提案作成時、提案タイトルの文字が15文字となっているが、8文字くらいにしたい
- また、エラーメッセージが重なってしまっている

## スクリーンショットなど / Screenshot
![image](https://user-images.githubusercontent.com/16509/97060013-16354180-15cd-11eb-9405-c9477648bd06.png)

## 期待する見せ方・挙動 / Expected behavior
- 8文字に変更
- エラーも読めるようにしたい

## 対象インスタンス / Instances

- 全て

**Comment by komtaki** [comment]
ruby初心者なので、簡単そうなこちら調べてみようと思います。

エラー表示がバグるのは、管理画面側の方ですね。一般ユーザー側は正常に表示されてました。

![キャプチャ](https://user-images.githubusercontent.com/39375566/97065935-02e59e80-15ec-11eb-970e-1601fa2d0926.JPG)

**Comment by komtaki** [comment]
文字数を検証している箇所は、下記ぽい

https://github.com/decidim/decidim/blob/master/decidim-proposals/app/forms/decidim/proposals/admin/proposal_form.rb#L8
https://github.com/decidim/decidim/blob/master/decidim-proposals/app/forms/decidim/proposals/proposal_wizard_create_step_form.rb#L15

**Comment by komtaki** [comment]
@knsg16 がMRで対応

**Comment by halsk** [comment]
とりあえずの暫定対応でこちらのIssueはクローズする。#61 で本格対応
