### ISSUE TITLE
リリースタグとCHANGELOG.mdを導入する

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/decidim-cfj#230]
## 改善詳細 / Details of Improvement
大きめの変更が入ったリリースを行った際に、どのタイミングでどういう変更があったかが追いかけづらいので、

- まとまった単位でリリースタグ(gitのタグ)を打つ
- 取り込んだ内容をCHANGELOG.mdに書く

というのを行うと良さそうです。

## 期待する見せ方・挙動 / Expected behavior

具体的には、

- #223 のようなDecidim本体のアップデート
- #227 のようなデプロイ方式の変更
- #229 のようなモジュールの大きな更新

などは、いつ導入されたかがCHANGELOG.mdに書かれて、そのバージョンをリリースタグで探せると良さそうです。
（リリースタグの代わりにgitのハッシュ値でも等価ではありますが、タグの方が人間に優しいので…）

## 対象インスタンス / Instances
- 全て

**Comment by takahashim** [comment]
タグの命名規則は、Decidim本体のタグにpostfixをつけるのがよいでしょうか
https://github.com/decidim/decidim/tags

**Comment by ayuki-joto** [comment]
Decidim本体のタグにpostfix+日付にしようと思います！
ex. v0.23.0-2021-5-24
