### ISSUE TITLE
提案ドラフトを編集する画面で画像と添付ファイルが削除できない

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#233]
## 対象ドメイン/ The domain
- shibuyatest.diycities.jp

## 起こっている問題 / The Problem
- 提案コンポーネントの提案ドラフトを編集する画面で、削除ボタンが正常に表示されない。

## スクリーンショット / Screenshot
![スクリーンショット 2021-05-25 0 56 39](https://user-images.githubusercontent.com/3460170/119375000-3f4dba00-bcf5-11eb-89b3-2543c70e8d0d.png)

## 期待する見せ方・挙動 / Expected Behavior
- 削除ボタンの正常な表示
- 画像および添付ファイルが削除できる

## 起こっている問題の再現手段 / Steps to Reproduce
1. 提案コンポーネントの提案を新規作成
2. Complete画面で画像またはファイルを添付し、送信ボタンをクリック
3. 提案を公開（preview）画面で「提案を編集する」をクリック
4. buttonのaria-labelとtitleが翻訳失敗し、htmlが崩れる
```html
<button class="close-button" aria-label="<span class=" translation_missing"="" title="translation missing: ja.decidim.proposals.proposals.edit.delete_image">Delete Image"
     title="<span class="translation_missing" title="translation missing: ja.decidim.proposals.proposals.edit.delete_image">Delete Image</span>"
    type="button"
    data-close&gt;
    <span aria-hidden="true">×</span>
</button>
```

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by takahashim** [comment]
これも翻訳データが足りてなかったためで、 #236 をマージできれば解決できるかと思います。
