### ISSUE TITLE
非公開の参加型プロセスで、提案作成やサポートのできないアカウントが存在する

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#234]
## 対象ドメイン/ The domain
- shibuyatest.diycities.jp

## 起こっている問題 / The Problem
非公開の参加型プロセス、提案コンポーネントにおいて、Decidim管理者アカウントでログインしている場合に
- 「新しい提案」ボタンが表示されない
- 「サポート」ボタンが無効になっている

## スクリーンショット / Screenshot
|参加者アカウント+公開および非公開 | Decidim管理者アカウント+公開 | Decidim管理者アカウント+非公開 |
| --- | --- | --- |
| ![スクリーンショット 2021-05-25 1 43 42](https://user-images.githubusercontent.com/3460170/119384036-13373680-bcff-11eb-8ecd-158f7713ff3e.png) | ![スクリーンショット 2021-05-25 1 43 42](https://user-images.githubusercontent.com/3460170/119384036-13373680-bcff-11eb-8ecd-158f7713ff3e.png) | ![スクリーンショット 2021-05-25 1 44 19](https://user-images.githubusercontent.com/3460170/119384066-1af6db00-bcff-11eb-83dc-83b1439e097c.png) |

## 期待する見せ方・挙動 / Expected Behavior
- プロセスの公開状態によって管理者アカウントで出来ることが変わるが、その原因がユーザから理解できないため不具合のように見えている。
- ただし、追記部分が原因とすると現状で仕様通りに動作しているとも考えられる

## 起こっている問題の再現手段 / Steps to Reproduce
1. Decidim管理者アカウントでログイン
2. 公開の参加型プロセスに提案コンポーネントを作成
3. フロントを見ると「新しい提案」ボタンが表示されている
4. 同プロセスを非公開に変更する
5. 「新しい提案」ボタンが消えている

### 追記
追加で動作確認したところ、下記現象が確認できました（もはや別Issueという感じですが）。
- Decidim管理者アカウントを参加型プロセスのプライベート参加者や参加型プロセス管理者に追加すると、すでに存在するユーザとして失敗してしまう
- つまり、Decidim管理者ユーザは非公開プロセスの参加者および管理者になることができず、上記の現象が発生している可能性があります。

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kken78** [comment]
追記のとおり実施しても、ユーザー作成できるので再現しなくなっている（かつ、挙動として正常）と判断します
