### ISSUE TITLE
提案の編集時に中身が消えてしまう

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#24]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- 作った提案を編集しようとすると、タイトル及び詳細が消えてしまう

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/97063151-fb68ca00-15d8-11eb-850d-5bf36832988d.png)

![image](https://user-images.githubusercontent.com/16509/97063132-ed1aae00-15d8-11eb-9be1-b28815f2e844.png)

## 期待する見せ方・挙動 / Expected Behavior
編集できるようにしたい

まずは、本家の decidim から新たにインスタンスを作ってみて、それでも発生するのか確かめたい

- [x] 本家 `develop` ブランチ
- [x] 本家 `release/0.23-stable` ブランチ（こちらと同様のブランチ）
- [x] 本家 `release/0.22-stable` ブランチ（少し古い安定版）

どなたかチェックいただけるとありがたいです！

## 起こっている問題の再現手段 / Steps to Reproduce
- 参加型プロセスを作る
- 「提案」コンポーネントを作る（提案の作成を有効にするのチェックを有効に）
- 提案を作成する
- 編集画面にいくと、中身が消えている。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
release/0.22-stable ブランチだと編集ができた
release/0.23-stable ブランチでは編集できなくなった

**Comment by halsk** [comment]
develop ブランチでも、編集ができなかった。本家の方にもあるバグだと思われる

**Comment by halsk** [comment]
本家にもバグを報告
https://github.com/decidim/decidim/issues/6739

**Comment by halsk** [comment]
`SELECT title FROM public.decidim_proposals_proposals;`

すると、

```
{
    "ja": "1. いつでもどこでもできるストレスフリーな行政手続きの実現"
}
```

となっている。
おそらく表示部分で多言語対応ができていない。

**Comment by halsk** [comment]
現行の修正だとハッシュタグ機能を使った際にうまく動かない可能性があると本家で教えてもらったので、調査が必要

https://github.com/decidim/decidim/issues/6739

**Comment by halsk** [comment]
上記のコメントで指摘された方法は、利用している関数が develop ブランチにしか存在しなかった。
とりあえずハッシュタグを使わなければOKなので、このままにしておく。

**Comment by takahashim** [comment]
この件について、 v0.24.3のソースではすでに修正済みのようなので、 #51 での追加したファイルは削除してしまっても良いかもしれません。
