### ISSUE TITLE
提案コンポーネントでサポート数が常に0件と表示される

### ISSUE THREAD

**Issue by yusukesaitoh** [codeforjapan/decidim-cfj#240]
## 対象ドメイン/ The domain
- shibuyatest.diycities.jp

## 起こっている問題 / The Problem
- 提案コンポーネントにおいて、サポート済みであってもサポート数が0件と表示される
- 一覧のソートで提案の順序を「最もサポートされています」に変更しても反映されない

## スクリーンショット / Screenshot
- 提案一覧
![スクリーンショット 2021-06-04 12 15 48](https://user-images.githubusercontent.com/3460170/120740859-01d80080-c52f-11eb-8551-60ed67e3dcf8.png)
- 提案詳細
![スクリーンショット 2021-06-04 12 19 10](https://user-images.githubusercontent.com/3460170/120740917-187e5780-c52f-11eb-88b4-6f83bef9cb78.png)
- 管理画面
![スクリーンショット 2021-06-04 12 21 37](https://user-images.githubusercontent.com/3460170/120741132-7317b380-c52f-11eb-8e05-e18b3c88384b.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正しいサポート数（投票数）の反映

## 起こっている問題の再現手段 / Steps to Reproduce
1. 提案を作成
2. サポートをクリック

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by takahashim** [comment]
こちらの件ですが、ローカルの開発環境で確認したところではうまく再現できておりません…。

メモ：
* サポート数は`decidim_proposals_proposal_votes`テーブルのレコード数と一致している模様。
* 同テーブルの`decidim_proposal_id`は、提案詳細表示画面のURLの末尾の数値（例: `/processes/et-sunt/f/12/proposals/48` なら 48）。
* サポートするとレコードが1件増え、再度クリックしてサポートを解除するとレコードごと削除される（！）
* それとは別に、`decidim_proposals_proposals`テーブルにも`proposal_votes_count`カラムにサポート数の数値が入っている（ActiveRecordのhas_many counter_cacheとして実装されている）。画面表示にはこちらの値が使われてそう。
* サポートしたり解除したりするとJSファイルが降ってきて、それでサポート数の表示を更新している（？）

**Comment by yusukesaitoh** [comment]
ご確認ありがとうございます。
対象ドメインで以下の操作を試したところ変わらず0サポートでした。
サーバ環境や特定ドメイン内での設定が関係しているのかもしれません。
- 新規で参加型プロセス（公開）を作成
- 新規で提案コンポーネントを作成
- 提案を作成、サポートをクリック

**Comment by takahashim** [comment]
こちらの現象を再現できました。

提案コンポーネントの設定で、「参加者一人あたりの最低サポート数」を2以上に設定していると、その数以上のサポートを選択するまでサポートの実数としてカウントされないようでした。
例えば一人最低3件以上サポートする設定だと、2件までのサポートはカウントに加算されなくなります。

「参加者一人あたりの最低サポート数」の設定方法は以下の通りです。

* 管理者としてログインし、管理ダッシュボードを開く
* 左側メニューの「参加型プロセス」をクリック
* 画面右側の「タイトル」の下にある、「提案」を含む参加型プロセス名をクリック
* 「公開ページを表示」の下、「情報」「フェーズ」「コンポーネント」…と並んでいるうちの「コンポーネント」をクリック
* 右側の「提案」の横にある歯車のアイコン（「設定」）をクリック
* 画面右側「コンポーネントを編集」の中の、「グローバル設定」にある「参加者一人あたりの最低サポート数」を設定（このページのURLは「`/admin/participatory_processes/XXXX/components/YYYY/edit`」のようになっているはずです）

こちらを0にするとすぐに反映されるようになるはずです。ご確認ください。
