### ISSUE TITLE
最初の画面でタイトルが見切れる(ウインドウサイズが小さい場合 or スマホの場合)

### ISSUE THREAD

**Issue by y-chan** [codeforjapan/decidim-cfj#25]
## 改善詳細 / Details of Improvement
- 題の通り

## スクリーンショットなど / Screenshot
![image](https://user-images.githubusercontent.com/34832037/97066367-e0558480-15ef-11eb-9d04-058c21bcbecb.png)
![Screenshot_20201024-114848](https://user-images.githubusercontent.com/34832037/97066400-26124d00-15f0-11eb-8515-681d8fe12cae.jpg)

## 期待する見せ方・挙動 / Expected behavior
- 見切れないように改行等対応を行う

## 対象インスタンス / Instances

- 全て

## 動作環境
- Ubuntu Firefox & Chrome / Android Chrome

**Comment by MaySoMusician** [comment]
埋め込まれているYouTubeプレーヤーも見切れている
![209568](https://user-images.githubusercontent.com/34566290/97066708-84d8c600-15f2-11eb-850d-1c49e29c5fc3.jpg)
