### ISSUE TITLE
Docke環境でseedが動かない

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#253]
## 対象ドメイン/ The domain
- local

## 起こっている問題 / The Problem
- 手順通りに環境構築を行うと、seed実行時にOrganizationのlogo画像部分でバリデーションエラーが起きる

## スクリーンショット / Screenshot
/app # ./bin/rails db:seed --trace
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:abort_if_pending_migrations
Creating seeds for decidim-core...
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Organization logo Error processing image
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:80:in `raise_validation_error'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:52:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `block in save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:53:in `create!'
/usr/local/bundle/bundler/gems/decidim-912bb8b483fd/decidim-core/db/seeds.rb:191:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/engine.rb:554:in `block in load_seed'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/engine.rb:672:in `with_inline_jobs'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/engine.rb:554:in `load_seed'
/usr/local/bundle/bundler/gems/decidim-912bb8b483fd/decidim-core/lib/decidim/core.rb:107:in `block in seed!'
/usr/local/bundle/bundler/gems/decidim-912bb8b483fd/decidim-core/lib/decidim/core.rb:104:in `each'
/usr/local/bundle/bundler/gems/decidim-912bb8b483fd/decidim-core/lib/decidim/core.rb:104:in `seed!'
/app/db/seeds.rb:14:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/engine.rb:554:in `block in load_seed'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/engine.rb:672:in `with_inline_jobs'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/engine.rb:554:in `load_seed'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
./bin/rails:6:in `<main>'
Tasks: TOP => db:seed

## 期待する見せ方・挙動 / Expected Behavior
- seedが正しく実行される

## 起こっている問題の再現手段 / Steps to Reproduce
1. DEVELOPMENT.mdのDockerバージョンに従って実行

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome 
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by takahashim** [comment]
これは確かに再現するようでした。
`Decidim::OAuthApplication` のvalidationに失敗していて、`carrierwave`の問題かと思ったら、`mini_magick`側の問題？のようでした。
mini_magickは4.10.1で、これはimagemagickの6でも7でも動く（両方あれば7を優先する）ものなので、これが直接の問題ではなさそうです。

**Comment by takahashim** [comment]
おそらくエラー内容としては以下のようなものではないかと思います。

> #<CarrierWave::ProcessingError: Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `magick identify /app/tmp/1624987133-49-0001-6153/homepage_image.jpg` failed with error:
identify: insufficient image data in file `/app/tmp/1624987133-49-0001-6153/homepage_image.jpg' @ error/jpeg.c/ReadJPEGImage_/1112.>

**Comment by ayuki-joto** [comment]
全てのイメージ飛ばして最新のdevelopのブランチ、masterのブランチでやってますが変わらずですね...

**Comment by takahashim** [comment]
私の方で上記手順を行った際も再現するようでした。
carrierwaveの挙動が怪しいのですが、もしかするとdevelopmentでもAWSを使う設定になっている(?)と再現しなくなるのかもしれません(そもそもdevelopment環境でcarrierwaveの設定がされないところが怪しい)。

なお、（あまり役に立たない）参考情報としては、Dockerイメージに `docker-compose run --rm app /bin/sh` で潜り込み、

```
vi /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/processing/mini_magick.rb
```

を使って https://github.com/carrierwaveuploader/carrierwave/blob/9d17a443d39ddf0c44bac985f69bf4c94d923a16/lib/carrierwave/processing/mini_magick.rb#L309 の `image.write(current_path)` を無理矢理コメントアウトする（！）とエラーが出なくなります。
要はここで `current_path` を書き換える際、 `current_path` のファイルを壊してしまう（具体的には0バイトにしてしまうらしい？）ことがあるようでした。

**Comment by komtaki** [comment]
トライありがとうございます。上手くいく私の環境の方がおかしそうですね。

Dockerなので、あまり差分が出るとは思えないのですが。:confused:

**Comment by komtaki** [comment]
私も発生しました。 💦 

イメージのベースをいじったのですが改善しませんでした。takahashimさんの言う通りgem起因ぽいですね。

- alpineやめて、slimに変更　×
- imagemagick 7 ->6 バージョンダウン ×
- imagemagick-libs, imagemagick-dev追加 ×

**Comment by ayuki-joto** [comment]
おお．．．やっぱり発生したんですね...
どうしましょうかこれ...

**Comment by takahashim** [comment]
これは何か根本的におかしいですね…。
とはいえ本家のCIが通っているということは、ubuntu-latest相当のdistributionにすれば通るんでは？？ という気もちょっとしております。

**Comment by takahashim** [comment]
logに出てくるエラーは以下になります:

> Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `magick identify /app/tmp/1636377117-199-0001-8613/homepage_image.jpg` failed with error:
> identify: insufficient image data in file `/app/tmp/1636377117-199-0001-8613/homepage_image.jpg' @ error/jpeg.c/ReadJPEGImage_/1112.

**Comment by takahashim** [comment]
これですが、原因はOSじゃなくてDocker(とLinux)なのかもです…。

**Comment by takahashim** [comment]
確認ありがとうございます、この件ですが、#306 で解決するようでした…。
Rubyの実装の問題かと思いきや、CやRustでも再現するようです。
