### ISSUE TITLE
robots.txtの追加

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#254]
## 改善詳細 / Details of Improvement
- 現状対象インスタンスで、ディベートの更新が積極的に行われている
- これらのディベートのバージョン部分で画像を含む更新履歴をDBから取得する処理の関係で本番インスタンスに負荷がかかっている
- robots.txtを追加してこれらのURLに定期的アクセスしてくるbotを止める

## 期待する見せ方・挙動 / Expected behavior
- robots.txtを追加し、botが回ってこないようにする
- 対象のURLのみ除外できるか等も併せて調査する

## 対象インスタンス / Instances
- hyogo-vision.diycities.jp
- kakogawa.diycities.jp

## 対象URL / URL
- https://hyogo-vision.diycities.jp/processes/opinions/f/120/debates/152/versions/以下

**Comment by komtaki** [comment]
robots.txt自体は既にあるので、下記のように記載すればできると思います。

公開URL:  https://hyogo-vision.diycities.jp/robots.txt
ファイルパス: https://github.com/codeforjapan/decidim-cfj/blob/develop/public/robots.txt

```
User-agent: *
disallow: https://hyogo-vision.diycities.jp/processes/opinions/f/120/debates/152/versions/*
```

**Comment by ayuki-joto** [comment]
*が使えるなら
``` 
Disallow: https://*.diycities.jp/*/versions/*
```
こんなのだとどうなんでしょうか？

**Comment by takahashim** [comment]
robots.txtの仕様ですが、

* ホスト名は不要（普通は書かない？）
* 末尾の`*`は省略可

ということなので、

```
Disallow: /*/versions
```

で良いかもしれません。
https://developers.google.com/search/docs/advanced/robots/robots_txt?hl=ja

**Comment by ayuki-joto** [comment]
これで一度検証しましょうか

**Comment by ayuki-joto** [comment]
デプロイしたのに反映されない...
@komtaki 何か心当たりありますでしょうか...?

**Comment by ayuki-joto** [comment]
全然気づいてなかったんですけど，

https://github.com/codeforjapan/decidim-cfj/blob/47230c361c15479f0b79b9d15aa3faa7e0d54f75/deployments/docker-compose.yml#L3-L27

このvolumesのstatic-publicってどんな動きしてるんでしょうか？
一応下の方で
https://github.com/codeforjapan/decidim-cfj/blob/47230c361c15479f0b79b9d15aa3faa7e0d54f75/deployments/docker-compose.yml#L36-L38
これだけ書かれてるんですけど

**Comment by komtaki** [comment]
共有ボリュームです。nginx側に静的コンテンツをマウントするために追加したのですが、同じインスタンスだとデプロイ時に更新されてないみたいですね。少し不便なのでなんとかしたい。

インスタンスを入れ替えたら、正常に表示されたように見えます。

**Comment by ayuki-joto** [comment]
解決しました！
おっしゃられたとおりインスタンスをこちらで終了して再度新しいインスタンスを立ち上げた際にきちんと反映されました！
