### ISSUE TITLE
development: NewRelicの警告が鬱陶しい

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/decidim-cfj#255]
## 改善詳細 / Details of Improvement

development環境で動かす際、newrelic agentの設定をしないとnewrelicの警告がたくさん出て鬱陶しいことがあります。

実行手順に、 `NEW_RELIC_AGENT_ENABLED=false` の設定を入れた方が良いかもしれません。

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 対象インスタンス / Instances

- 全て
- ○○市

**Comment by ayuki-joto** [comment]
これは確かに。。。
対応した方が良さそうですね

**Comment by komtaki** [comment]
これ私も同じことを思って手元で入れてました。:sweat_drops:

**Comment by ayuki-joto** [comment]
こちらstagingも対応したいです。
new relic まだ有償化していないので、callのlimitに引っかかりそうなので

**Comment by komtaki** [comment]
では、本番以外基本new relic offですね。

**Comment by takahashim** [comment]
はい、そうしてもらった方が良さそうです…！＞基本off
