### ISSUE TITLE
調査コンポーネントが使えない

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#256]
## 対象ドメイン/ The domain
- kakogawatest.diycities.jp

## 起こっている問題 / The Problem
- 調査コンポーネントを作成し、内容を追加しようとしたところ「サーバーに問題が発生しました　後でもう一度お試しください。」といったメッセージが表示され編集ができない。

## スクリーンショット / Screenshot
![スクリーンショット 2021-07-06 22 13 14](https://user-images.githubusercontent.com/40754081/124606661-100b9a80-dea8-11eb-900f-b99456425926.png)

![スクリーンショット 2021-07-06 22 14 28](https://user-images.githubusercontent.com/40754081/124606792-2e719600-dea8-11eb-9319-473956f79ebe.png)

## 期待する見せ方・挙動 / Expected Behavior
- 調査コンポーネントを使用したい。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 添付の赤枠部分をクリックすると2つ目の画像が表示される。

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by takahashim** [comment]
ちょっと見てみましたが、これは [Decidim::Templates](https://github.com/decidim/decidim/tree/develop/decidim-templates)を導入してないためエラーが発生しているようでした。
（現在Decidim-cfjで使っているのよりも新しいバージョンでは、エラーにならないように修正が入っているようでした https://github.com/decidim/decidim/pull/6652 ）

@ayuki-joto Decidim::Templatesをインストール・設定しますか？ README.mdに書かれてる手順を実行することになりそうです（ちゃんとした動作検証はまだできてないです）。

**Comment by halsk** [comment]
@takahashim いれましょう！

**Comment by takahashim** [comment]
#223 が取り込まれれば、調査コンポーネントも利用できるようでした。

**Comment by ayuki-joto** [comment]
こちらは解決された認識で大丈夫でしょうか？
