### ISSUE TITLE
翻訳：提案サポートの表示

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#259]
## 改善詳細 / Details of Improvement
- 提案をサポートしたときに「サポート済みです」と表示されるが、サポート上限（加古川の場合は３つ）を満たすとサポートしていない提案には「サポートがありません」と表示される

## スクリーンショットなど / Screenshot
![スクリーンショット 2021-07-15 8 03 17](https://user-images.githubusercontent.com/40754081/125705186-f31420b2-413f-4f2a-a2c7-0d0fe7c2fa32.png)

## 期待する見せ方・挙動 / Expected behavior
- どのように表示するのが良いのかは検討が必要ですが、「サポートしていません」ぐらいの表現のほうがわかりやすい
- 
## 対象インスタンス / Instances

- 全て

**Comment by takahashim** [comment]
細かい確認ありがとうございます。確かにこれは検討が必要というか、表現が難しいですね…。

英語版では`No supports remaining`で、長めの日本語に訳すと「サポートが残っていません」「サポートが足りません」になるかと思います。サポートしていない、ということよりもサポート上限に達しているので「サポートしたくてもできない」ということを伝えたいのではないかと思います。

どうするのがよいでしょうか？（やっぱり「サポートしていません」くらいが無難でしょうか？）

**Comment by takahashim** [comment]
案: `サポート可能上限に達しています`といった文言に変更してみる

**Comment by halsk** [comment]
@isaozz 
「サポート可能な上限に達しています」ではどうでしょうか

**Comment by halsk** [comment]
サポート自体の文言を変えたいですよね。
* 支持する
* 賛同する
とか？

**Comment by isaozz** [comment]
@halsk 
「サポートできる上限に達してます」はいかがですか。あまり意味は変わらないですかね。

**Comment by dmikurube** [comment]
はじめまして、最近 `#proj-decidim` で decidim.org の翻訳に参加させてもらった @dmikurube です。

Slack にも流れるのを見てお邪魔させていただきまして、一案ですが、

* Support → 支持を表明する
* No supports remaining → これ以上は支持を表明できません (「サポート」を残すなら、これ以上サポートできません、とか)

あたりではいかがでしょう? もとの英語の意味からするとこんな感じかなと。
