### ISSUE TITLE
翻訳に関する総合Issue

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/decidim-cfj#26]
## このissueについて
翻訳の追加・変更や誤訳の報告など、翻訳に関するものはこちらのissueにコメントをお願いします！

## 対象インスタンス / Instances
- 全て

## 対応状況

| 修正箇所 | 修正対象 |  修正後   | 対応済(Decidim) | 対応済(開発環境) | 対応済(本番環境 | 備考 |
| -------- | -------- | -------- | -------- | -------- | -------- | ------- |
| 全て | 官職の提案 | 事務局の提案 | 済 | 済 | | |
| 全て | あなたの名前 | 表示名 | 済 | 済 | | #71 |
| 全て | ニックネーム | アカウントIDアカウント | 済 | 済 | | #71 |
| 新規登録 | 関連情報を含む時折ニュースレターを受け取る | 関連するお知らせを受け取る | 済 | 済 | | |
| 新規登録 | 議論とサポートの提案に参加するにはサインアップしてください。 | 参加するにはユーザ登録をしてください。 | 済 | 済 | | サインアップをユーザ登録に |
| 新規登録 |  利用規約やに同意したことになります | 利用規約に同意したことになります| 済 | 済 | | |
| 新規登録 | 確認の指示を受信しませんでしたか？ | ユーザ登録確認メールが届かない方はこちら | 済 | 済 | | |
| 新規登録 |  ロック解除の指示を受信しませんでしたか？ | ロック解除の手順を送信したい方はこちら | 済 | 済 | | |
| 新規登録 | 10 文字以上。一般的すぎてはいけません | 半角英数字10文字以上で入力してください。単純すぎてはいけません（例：123456）。 | 済 | 済 | | |
| 全体 | 指紋を確認 | フィンガープリントを確認 | 済 | 済 | | 確かに一般用語ではないが、他に言いようが無い？ |
| プロセス一覧 | 見る | ? | | | | 見当たらず・・・ |
| 全体 | サインイン | ログイン | 済 | 済 ||
| 全体 | 連絡の許可 | ニュースレターを受け取る | 済 | 済 ||
| 全体 | 関連情報を含む時折ニュースレターを受け取る | 関連するお知らせを受け取る | 済 | 済 ||
| フッタ | このサイトはフリーソフトウェアで作られています | 変更無し | 済 |||クリエイティブ・コモンズとは直接は関係ない|
| メール | こんにちは○○ | こんにちは○○さん | 済 | 済 | |その他の言い回しも調整済 
| 参加者の設定 - 通知の設定 |  | 電子メールで通知を受け取る/通知をメールで受け取る | 済 | 済 | |
| 参加者の設定 - 通知の設定 |  | 通知を毎回メールで受け取る | 済 | 済 | |
| 登録確認メール | 以下のリンクからメールアカウントを確認できます | 下記のリンクにアクセスすると、メールアドレスの確認が完了します。 | 済 | 済 |
| 登録確認メール | 確認の手順 | 登録のご案内（メールアドレスの確認）| 済 | 済 | |
| 新規登録 | 用語を拒否する | 同意しない | 済 | 済 | |

**Comment by isaozz** [comment]
事務局側が提案した際の「官職の提案」を「事務局の提案」としてください。

**Comment by isaozz** [comment]
ユーザ登録時に出る「関連情報を含む時折ニュースレターを受け取る」を「関連情報に関するニュースレターを受け取る」としてください。

**Comment by MaySoMusician** [comment]
「サインアップすることで、利用規約やに同意したことになります」を適切な日本語に（原文を参照する必要あり）

![image](https://user-images.githubusercontent.com/34566290/97066782-1b0cec00-15f3-11eb-9ff3-24408f151717.png)

**Comment by isaozz** [comment]
新規登録時に「10 文字以上。一般的すぎてはいけません」こいつも気になりますね。

**Comment by MaySoMusician** [comment]
「指紋を確認」の指紋はフィンガープリントのことのようですね
ただ、「フィンガープリント」という言葉も難解なので検討の余地あり

![image](https://user-images.githubusercontent.com/34566290/97066961-bdc56a80-15f3-11eb-97c7-7eb8845d3233.png) ![image](https://user-images.githubusercontent.com/34566290/97066971-cddd4a00-15f3-11eb-8ee2-4277f8594e53.png)

**Comment by MaySoMusician** [comment]
プロセス一覧の「見る」「アクティブ」が何なのか不明（翻訳を変えれば対応可能と思われる）

![image](https://user-images.githubusercontent.com/34566290/97066984-febd7f00-15f3-11eb-9f7b-45e08b2d6679.png)

**Comment by MaySoMusician** [comment]
「ログイン」「サインイン」の表記ゆれがある

![image](https://user-images.githubusercontent.com/34566290/97067028-77244000-15f4-11eb-832c-fb57e50aebc9.png)

**Comment by SKosaka** [comment]
登録画面
- 「連絡の許可」 -> 何か違和感..(タイトル必要?)
- 「関連情報を含む時折ニュースレターを受け取る」 -> 「お知らせを受け取る」で十分では?
![Uploading IMG_1401.jpg…]()

**Comment by SKosaka** [comment]
フッター
- 「このサイトはフリーソフトウェアで作られています」-> 「このサイトの内容物は クリエイティブ・コモンズ 表示 4.0 ライセンス の下に提供されています。」とか?
![IMG_1402](https://user-images.githubusercontent.com/46814044/97067113-5f00f080-15f5-11eb-9f64-9d6ea81d06da.jpg)

**Comment by MaySoMusician** [comment]
メアド確認メールで「こんにちは ○○」と呼び捨てになってしまうので「○○さん」といった表記に変更

![image](https://user-images.githubusercontent.com/34566290/97067153-b30bd500-15f5-11eb-9498-aea28a726831.png)

**Comment by SKosaka** [comment]
> メアド確認メールで「こんにちは ○○」と呼び捨てになってしまうので「○○さん」といった表記に変更

スクショに映り込んでる他の日本語全般が気になりますね..
-「こんにちは 〜 歓迎します！」-> 「ようこそ、わたなべさん。加古川市市民参加型合意形成プラットフォームへご参加いただきありがとうございます。」
- 「もし、あなたが〜ご参照ください。」->「このサイトの使い方はこちらから」
- 「もし目を通していただけると最初のバッジを獲得できます。」-> バッジ..?

**Comment by isaozz** [comment]
> 「ログイン」「サインイン」の表記ゆれがある
> 
> ![image](https://user-images.githubusercontent.com/34566290/97067028-77244000-15f4-11eb-832c-fb57e50aebc9.png)

「ログイン」がわかりやすかもしれませんね。

**Comment by isaozz** [comment]
#新規登録時の「連絡の許可」は「通知を受け取る」もしくは「ニュースレターを受け取る」ぐらいでしょうか
![連絡の許可](https://user-images.githubusercontent.com/40754081/97067471-873e1e80-15f8-11eb-8e8c-afda053161c4.png)
「連絡の許可」

**Comment by kken78** [comment]
参加者の設定 - 通知の設定 の、

![スクリーンショット 2020-10-24 13 11 43](https://user-images.githubusercontent.com/35302518/97067654-87d7b480-15fa-11eb-88a3-2f9dadbba2ec.png)

正しい表現だけど「送信」と「受信」が同時に出てきて（さらに「通知を受け取る」という表現と組み合わさって）気持ち悪い

電子メールで通知を受け取る
　通知をメールで受け取る

**Comment by kken78** [comment]
ヘルプページのリード文はシンプルでいいかなと

![スクリーンショット 2020-10-24 13 17 46](https://user-images.githubusercontent.com/35302518/97067753-94a8d800-15fb-11eb-9267-8a00a3a94533.png)

→　加古川市 市民参加型合意形成プラットフォーム のヘルプページです

**Comment by isaozz** [comment]
新規登録時のボタンの下のところ「確認の指示を受信しませんでしたか？」「ロック解除の指示を受信しませんでしたか？」
![新規登録画面](https://user-images.githubusercontent.com/40754081/97067809-78f20180-15fc-11eb-992f-ed4592927523.png)

**Comment by MaySoMusician** [comment]
#37 も翻訳関連っぽい

**Comment by MaySoMusician** [comment]
> プロセス一覧の「見る」「アクティブ」が何なのか不明（翻訳を変えれば対応可能と思われる）
> 
> ![image](https://user-images.githubusercontent.com/34566290/97066984-febd7f00-15f3-11eb-9f7b-45e08b2d6679.png)

[meta](https://meta.decidim.org/processes)版を見てきましたが、「SEE PAST」「SEE ALL」というように繋げて読むのが前提のUIのようです。

![image](https://user-images.githubusercontent.com/34566290/97069689-cf673c00-160c-11eb-8eb1-0ae970484d67.png)

日本語で表現するなら「表示: 進行中」「表示: 過去」「表示: 全て」（コロンがあるのが重要）ですかね

イメージ図: 
![image](https://user-images.githubusercontent.com/34566290/97069728-1e14d600-160d-11eb-9e3c-c7a34ee80a38.png)

**Comment by mcyph** [comment]
> 「ログイン」「サインイン」の表記ゆれがある
> 
> ![image](https://user-images.githubusercontent.com/34566290/97067028-77244000-15f4-11eb-832c-fb57e50aebc9.png)

`/app/assets/stylesheets/decidim.css`にこのCSS入れたらこの問題が解決されると思います。

```css
.button--social{
  padding: 0;
}
.button--social__icon,
.button--social__text{
  text-align: center;
  margin: 0;
}
```

そうすると中心のポジションににります：

![image](https://user-images.githubusercontent.com/20507948/97078418-eec78e80-1637-11eb-8f96-b81f15ad252e.png)

**Comment by mcyph** [comment]
![image](https://user-images.githubusercontent.com/20507948/97078542-9ba20b80-1638-11eb-8323-82c16a1dfb3e.png)
![image](https://user-images.githubusercontent.com/20507948/97078564-b5dbe980-1638-11eb-9d5e-6c0c0d7746c5.png)

現在とあるメニューは2行を渡しますので、`decidim.css`にこのCSS加えたら直すと思います。

```css
.menu li, .menu.horizontal li {
    white-space: nowrap;
}
```

携帯ではこのようなメニューは表示されないと思うので、多分こうすると携帯でも大丈夫です。

**Comment by MaySoMusician** [comment]
@mcyph Thank for commenting! I mean spelling variants between "signin" and "login"

**Comment by mcyph** [comment]
> @mcyph Thank for commenting! I mean spelling variants between "signin" and "login"

Oh I see! Sorry yes I thought the trouble was it wasn't centered! I think I should maybe move these two replies to separate issues as they're really separate issues to translation, even if they might not occur for Spanish or English

**Comment by isaozz** [comment]
![スクリーンショット 2020-10-24 22 44 03](https://user-images.githubusercontent.com/40754081/97083380-8c2bbe00-164a-11eb-82fd-2d9fc9f26418.png)

Facebookから認証をかけた際に「プロフィールを完成させてください」「サインアップを完了するには〜」「プロファイルを完了」と表記が微妙な感じがしますね。

**Comment by isaozz** [comment]
![スクリーンショット 2020-10-24 22 48 15](https://user-images.githubusercontent.com/40754081/97083441-05c3ac00-164b-11eb-9298-11def379b7a5.png)

サインアップ後のメールですが、「確認の手順」と表記されていますので、「登録のご案内（メールアドレスの確認）
」でいかがでしょうか。
「以下のリンクからメールアカウントを確認できます。」も日本語としては表現が微妙なので、「下記のリンクにアクセスすると、メールアドレスの確認が完了します。」でどうでしょう。

**Comment by isaozz** [comment]
> 新規登録時に「10 文字以上。一般的すぎてはいけません」こいつも気になりますね。

10文字というのも長すぎるような気がしますが、表記としては「半角英数字10文字以上で入力してください」としてはどうでしょうか。

**Comment by isaozz** [comment]
利用規約のところが「用語を拒否する」になってますので、「同意しない」「同意する」でどうでしょうか。

![97083279-d2cce880-1649-11eb-98a4-a178aec9130c](https://user-images.githubusercontent.com/40754081/97084470-3f4be580-1652-11eb-9c30-95ef18d2fe93.png)

**Comment by halsk** [comment]
@MaySoMusician これ、ほとんどが一般的に直したほうが良い修正だと思うので、Crowdin の方を直す方針で考えています。

**Comment by doyaaaaaken** [comment]
このIssueに関係しそうな補足情報ですが、[翻訳修正の仕方について本家ドキュメントに記載されていました。](https://docs.decidim.org/en/contribute/translations/)
直接locale/ja.ymlファイルにPRを送るのではなく、Crowdin経由で修正してほしいと書かれていました。

[Crowdinのdecidim翻訳プロジェクト](https://translate.decidim.org/project/decidim/ja)はCrowdinアカウントを作成した後参加申請を出すと登録できるようです。 **参加承認制なので承認までに時間がかかるのと、Crowdinへの修正は本家decidimのほうにPR作成という形で反映されるようなので、反映までに時間がかかる点は気をつけたほうがいいかもしれません。**

**Comment by halsk** [comment]
@doyaaaaaken 
はい。そうですね。既に私はアカウントを取っています。
（というか、半分以上の翻訳は私がやっています。）
Crowdin で更新したものは、chore/l10n/develop ブランチに数分後にアップされます。

https://github.com/decidim/decidim/tree/chore/l10n/develop

ですので、こちらから ja.yml のみをこちらのリポジトリに反映させる必要がありそうです。

**Comment by isaozz** [comment]
コメント欄の横にある旗のアイコンを押すと出てくるダイアログの翻訳が微妙でした。
![不適切なコンテンツ](https://user-images.githubusercontent.com/40754081/97258374-a688b600-185b-11eb-81b4-90f850fdddcd.png)

- クリックベイト、広告、詐欺などが含まれています。
- 差別的な内容、誹謗中傷などの不適切な内容が含まれています。
- その他、禁止事項に当たる内容が含まれています。

などはいかがでしょうか。

**Comment by isaozz** [comment]
ディベートの管理画面において、「Instructions to participate」というものが出てきました。
「参加方法」？？という意味合いでしょうか。

**Comment by halsk** [comment]
@isaozz 翻訳文は一通り修正しました。
今後、翻訳に関する不具合は改善要望として新たに Issue 登録してください。

**Comment by isaozz** [comment]
@halsk ありがとうございます！！！
