### ISSUE TITLE
翻訳：住所

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#260]
## 改善詳細 / Details of Improvement
- ニュースレターテンプレートのリンク先を押したときに表示されるエラーが「この住所は正しくないか削除されています。」となっている。

## スクリーンショットなど / Screenshot
![スクリーンショット 2021-07-15 8 25 56](https://user-images.githubusercontent.com/40754081/125705576-08f63b09-84d0-4ad9-ac15-7154560dfd99.png)
![スクリーンショット 2021-07-15 8 27 26](https://user-images.githubusercontent.com/40754081/125705587-b279ce20-2239-4bb2-b9aa-365c2a3c0504.png)

## 期待する見せ方・挙動 / Expected behavior
- 「住所」を「URL」もしくは「アドレス」としたい

## 対象インスタンス / Instances

- 全て

**Comment by takahashim** [comment]
こちらは原文が `This address is incorrect or has been removed.` だったので、 #262 で「アドレス」に修正してみます。
Crowdinの方は修正済みです。
