### ISSUE TITLE
複数のSSL証明書の対応

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#263]
## 改善詳細 / Details of Improvement
- diycityの名称の変更に伴い、makeour.cityの新ドメインでの対応に変更していくことになりました
- とはいえ、現在の環境も並行して動くことになるのでLBに複数の証明書を割り当てたい
- 今は手動で、LBに割り当てているが、コードベースに落としておきたい

## 期待する見せ方・挙動 / Expected behavior
- https://aws.amazon.com/jp/premiumsupport/knowledge-center/elastic-beanstalk-ssl-load-balancer/
- これと同様の対応をする。

## 対象インスタンス / Instances

- 全て

**Comment by komtaki** [comment]
コードに落とすにはSSLCertificationのArnを書かなければいけないので、どうやって値を隠蔽するかが課題ですね。
流石に直書きは、セキュリティ的に問題がありそうなので。

**Comment by ayuki-joto** [comment]
こちらdecidimのcdk側で対応予定です！
https://github.com/codeforjapan/decidim-cfj-cdk
