### ISSUE TITLE
本番環境のインスタンス数がおかしい

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#264]
## 対象ドメイン/ The domain
- 全て

## 起こっている問題 / The Problem
- 常時インスタンスが5台立ち上がっている状態になっている
- Auto Scalingの設定は最小3になっている。
- 手動でインスタンスを落としてもすぐにもう一台が立ち上がり5台を維持されてしまう

## スクリーンショット / Screenshot
![スクリーンショット 2021-07-20 22 08 52](https://user-images.githubusercontent.com/19406594/126329592-72afda6b-b194-4c13-a092-bef0c81a4152.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 適切な動きをするように

## 動作環境・ブラウザ / Environment
- AWS

**Comment by komtaki** [comment]
![count](https://user-images.githubusercontent.com/39375566/126500120-57b3928e-2d8f-46e5-b654-84b4919730a6.JPG)
![cpu](https://user-images.githubusercontent.com/39375566/126500124-71d43f70-74e3-4c1c-8225-e510687e3453.JPG)

動作的には正常に見えます。アクセスの増加か一週間ほど前から微妙に負荷があがって、ダウンスケールに抵触しないだけかと。

オートスケールの設定を、最大になってるのを平均に変えるだけでも多少は変わる気がしました。
