### ISSUE TITLE
ディベートを閉じた際のメールタイトルの翻訳がない

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#268]
## 対象ドメイン/ The domain
- https://kakogawa.diycities.jp/

## 起こっている問題 / The Problem
- ディベートを閉じた際に送られてくるメールのタイトルが「translation missing: ja.decidim.events.debates.debate_closed.follower.email_subject」となっている。

## スクリーンショット / Screenshot
![スクリーンショット 2021-08-02 22 11 38](https://user-images.githubusercontent.com/40754081/127867997-3fa57a12-9050-48a9-a4c3-4cddfa699b02.png)

## 期待する見せ方・挙動 / Expected Behavior
- ディベートを閉じた際のメールタイトルの翻訳「〇〇のディベートが閉じられました」を付ける
- 「閉じられました」よりも「〇〇のディベートは終了しました」の方が適している

## 起こっている問題の再現手段 / Steps to Reproduce
1. ディベートを閉じる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takahashim** [comment]
確認しました。
本来はディベート終了時には `「〇〇〇」のディベートは終了しました` といった件名のメールになるよう翻訳データが設定されているのですが、`decidim.events.debates.debate_closed.follower.email_subject` ではなく `decidim.events.debates.debate_closed.email_subject` で設定されていたので翻訳が見つからずエラーになった、ということのようです。

`decidim.events.debates.debate_closed.follower.email_subject`になるのが不具合のような気がするのですが、とりあえずこちらのメッセージでも使えるように翻訳を追加しておきます。
