### ISSUE TITLE
ユーザー登録画面で、横幅が狭いと表示が崩れる

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/decidim-cfj#27]
### 不具合の内容
- ニックネーム入力欄の「@」とインプット部分が改行されてしまう

### スクリーンショット（あれば）
![209569](https://user-images.githubusercontent.com/34566290/97066751-e305a900-15f2-11eb-922a-3e2a7bd22988.jpg)

### 再現手順
- スマホなどで https://kakogawa.diycities.jp/users/sign_up にアクセス

### 利用環境
- Android 10 Chrome

**Comment by SKosaka** [comment]
エラー時も同様。
![IMG_1398](https://user-images.githubusercontent.com/46814044/97066804-40015f00-15f3-11eb-9aa8-08a56c831fd4.png)

再現環境：iOS(iPhoneSE1) / Chrome
