### ISSUE TITLE
トップ画面のYouTubeの埋め込みが見切れる(ウインドウサイズが小さい場合 or スマホの場合)

### ISSUE THREAD

**Issue by SKosaka** [codeforjapan/decidim-cfj#28]
## 詳細
- タイトルのとおり

## スクリーンショット / Screenshot
![IMG_1396](https://user-images.githubusercontent.com/46814044/97066731-bd789f80-15f2-11eb-86ad-a2a358011d5a.png)

## 期待する見せ方・挙動 / Expected Behavior
- 560px付近?よりも狭い幅でも縮小するよう修正

## 動作環境・ブラウザ / Environment
- macOS / Chrome
- iOS(iPhoneSE1) / Chrome

**Comment by halsk** [comment]
#80 で解決済
