### ISSUE TITLE
改行が正しく動いていない場合がある

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#288]
## 対象ドメイン/ The domain
- rules-2121.diycities.jp
- おそらく他のドメインも

## 起こっている問題 / The Problem
- 英数字で適当に文字が打たれた場合に改行されず枠内に収まらないことがある
- 日本語のコメントでは正しく動いていそう

## スクリーンショット / Screenshot
![スクリーンショット 2021-10-12 15 27 20](https://user-images.githubusercontent.com/19406594/136903222-3772b01e-8e25-4bb1-95d3-e5ae8dc802e2.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 正しく改行される

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://rules-2121.diycities.jp/processes/resume/f/214/debates/247のドメインにアクセス
2. コメントを読み込む
直接リンク https://rules-2121.diycities.jp/processes/resume/f/214/debates/247?commentId=2674

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome / safari

**Comment by takahashim** [comment]
遅くなりましたが、これはCSSの問題のようです。
`word-wrap: break-word;`等を指定すると改行されるようになります。

<img width="800" alt="word-break" src="https://user-images.githubusercontent.com/10401/152760280-de5ce13c-7a46-4ac2-9035-a08e619316d9.png">
