### ISSUE TITLE
プロセスの一覧表示画面が分かりにくい

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/decidim-cfj#30]
## 改善詳細 / Details of Improvement
- 「段階 1/1」「?-?」「プロセスのフェーズ」など、何のことを指しているか不明
- プロセスのカテゴリ(?)ごとにフィルターするドロップダウンボックスがわかりにくい
    - これについては本家ごと変えてもよい案件かも
- 「リストに戻る」リンクがしたすぎる
    - 同じく、本家ごと変える必要がありそう

## スクリーンショットなど / Screenshot
![image](https://user-images.githubusercontent.com/34566290/97067049-af2b8300-15f4-11eb-93b5-622e8034989d.png)

## 期待する見せ方・挙動 / Expected behavior
- この画面が分かりやすくなるように

## 対象インスタンス / Instances
- 全て

**Comment by halsk** [comment]
プロセスのフェーズと日時を設定したので解消された
