### ISSUE TITLE
pptxファイルが添付できない

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#301]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- PowerPoint2007以降のPowerPointファイルを添付しようとしたが添付できない。
- Word2007以降、Excel2007以降のdocx、xlsxファイルはあるが、pptxファイルの定義がなくppx となっている

## スクリーンショット / Screenshot

![スクリーンショット 2021-11-03 19 37 46](https://user-images.githubusercontent.com/40754081/140046490-c8e54b34-baeb-4c3d-aa31-10f2162bb3af.png)

## 期待する見せ方・挙動 / Expected Behavior
- ppxではなくpptxを定義することで良いと思われる

## 起こっている問題の再現手段 / Steps to Reproduce
1. 新しい添付ファイルを選択
2. ファイルを選択し「pptx」ファイルを添付する

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by takahashim** [comment]
確認しました。確かにおかしそうというか、なんでppxになってるんでしょうね…。

**Comment by halsk** [comment]
組織管理画面で使える拡張子を指定できるんですが、一応pptxも入っていますね

![image](https://user-images.githubusercontent.com/16509/140240751-97e43f8a-7fe2-4207-b6b2-bdbd910e370d.png)

**Comment by takahashim** [comment]
本家の方にもフィードバックと修正を投げておきました https://github.com/decidim/decidim/issues/8501
ちなみに私のローカル開発環境だとpptxでもアップロードできるようでした（？）

**Comment by takahashim** [comment]
こちらもすでに解決済みのはずです。再現されるようでしたらreopenしていただくか、新しくissueを作っていただけるとありがたいです。
