### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed: Organization logo Error processing image

### ISSUE THREAD

**Issue by imdkarthik** [codeforjapan/decidim-cfj#302]
**Describe the bug**
ActiveRecord::RecordInvalid: Validation failed: Organization logo Error processing image - while running docker-compose run --rm app ./bin/rails db:seed

**To Reproduce**
1. Fresh Ubuntu 18.04 Docker based installation 
2. After Git pull & docker build 
3. docker-compose run --rm app ./bin/rails db:seed
![Screenshot 2021-11-05 at 6 44 18 PM](https://user-images.githubusercontent.com/14892269/140516406-e4b1f611-38ab-4250-bd67-22a0809f73cb.png)

**Comment by takahashim** [comment]
Thank you for your feedback!

It may be the same issue that caused the problem #253, that docker fails to register seeds.

**Comment by takahashim** [comment]
@imdkarthik This bug is supposed to have been fixed in #306.
