### ISSUE TITLE
検索結果がある筈なのにゼロ件になる

### ISSUE THREAD

**Issue by tomoaki-n** [codeforjapan/decidim-cfj#31]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- 検索画面で存在しているキーワードを入力している筈なのに結果が反映されない

## スクリーンショット / Screenshot

![IMG_2052](https://user-images.githubusercontent.com/22102102/97067490-a472ed00-15f8-11eb-8db4-8df7e607ccd9.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 正しい検索結果が反映されるよう修正する

## 起こっている問題の再現手段 / Steps to Reproduce
1. 検索窓でキーワード検索する

## 動作環境・ブラウザ / Environment
- iOS(iPad Pro2)
- Chrome

**Comment by mcyph** [comment]
まだ詳しく調べてないんですけど、 https://www.racksam.com/2016/05/03/chinese-full-text-searching-with-postgresql-zhparser-and-rails/#more だと（中国語の記事）decidimに使っているpg_searchは中国語の文書の解析がサポートしてはいないため、いろいろなこつを使って外部の解析エンジンを使っています。

pg_searchやPostgreSQL Full Textも日本語のサポートをしているかどうかわかりませんけど、していなければ[mecab](https://taku910.github.io/mecab/)、chasenみたいな解析エンジンもこのようにテキストインデックスのパイプラインに入れる必要があるかと思っています。

**Comment by halsk** [comment]
以前Railsで全文検索を実装したときはPGroongaを使いましたが、最近はどうなんでしょうか。
https://workabroad.jp/posts/2244

**Comment by takahashim** [comment]
最近だとElasticsearchを導入する話を聞きますが、PGroongaも安定して開発が継続されている印象があります。
来月のPostgreSQL Conference Japan 2020でもPGroongaのセッションがあるようでした。 https://www.postgresql.jp/jpug-pgcon2020

**Comment by takahashim** [comment]
こちらについて改めて調べてみたところ、

* 検索についてはpg_searchというgemを使っている
* pg_searchでは検索方式を指定できるが、DecidimではPostgreSQL標準の全部検索機能を使っている（pg_searchのデフォルトがこれ）
* PostgreSQL標準の全文検索を使う場合、比較的新しいPostgreSQLであれば、トークナイザーを自力で実装し、それを使うようにすれば日本語も検索できそう（参考: https://www.clear-code.com/blog/2020/12/22.html ）

という状況でした。

pg_searchにcontributeして自前トークナイザーをサポートしてもらえるとありがたいですが、まずは両方を上書きして修正する対応ができるのであれば、それが手っ取り早そうです。とはいえどっちにしてもあまり簡単ではなさそう。

**Comment by takahashim** [comment]
Decidimもバージョンは上がり、コンポーネント検索はできるようになったものの、グローバルな検索については現状でも検索できる状態にはなっていないようでした。

検索対象になっているテーブル `decidim_searchable_resources` のデータを作り直すところから修正する必要がありそうです（これは上記のpg_searchの問題と思われます）。
