### ISSUE TITLE
NoMethodError: undefined method 'manipulate!' といったエラーが出る

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/decidim-cfj#322]
## 対象ドメイン/ The domain
-  v0.24.3用の開発環境とCIサーバ

## 起こっている問題 / The Problem
- v0.24.3用のブランチでテストを実行すると、`NoMethodError: undefined method 'manipulate!'` といったエラーが出る

関連: https://github.com/codeforjapan/decidim-cfj/pull/312

## スクリーンショット / Screenshot

```
  1) Need user extension when user_extension is disable when signed in as user without user extension not redirect in notifications page
     Failure/Error: let(:organization) { create(:organization) }
     
     NoMethodError:
       undefined method `manipulate!' for #<Decidim::OrganizationFaviconUploader:0x00007f80c04754f8>
```

## 期待する見せ方・挙動 / Expected Behavior
- テストが正常に実行される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 開発環境を準備する
2. `bundle exec rspec` を実行する

## 動作環境・ブラウザ / Environment
- macOS
- （ブラウザは関係なさそう）

**Comment by takahashim** [comment]
この件ですが、実は先ほど原因が判明しておりまして、「`app/uploaders/decidim/application_uploader.rb`をこのインスタンスで上書きしている一方で、v0.24.3版の更新が反映されていない」ということによるもののようでした…。

これはバージョンアップのたびに確認しないといけなさそうです。厳しい。

**Comment by takahashim** [comment]
#312 の方にコミットしたのでこちらは閉じておきます

**Comment by ayuki-joto** [comment]
あーなるほど。。。
となると
#321 と #317 の対応も毎度調整必要になるかもですね...

**Comment by takahashim** [comment]
そのあたりは対応が必要になりそうですね
