### ISSUE TITLE
スマホで見た時に、Youtube の画面が切れてしまう

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#332]
## 対象ドメイン/ The domain
- meta.diycities.jp

## 起こっている問題 / The Problem
- Youtube動画が埋め込まれているページをスマホから見ると、画面が切れてしまっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/152248301-c6e61174-29b2-4d8d-a074-49f586778553.png)

## 期待する見せ方・挙動 / Expected Behavior
- 切れずに表示されて欲しい

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://meta.diycities.jp/assemblies/dpps/f/374/meetings/30 にスマートフォンでアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

iOS 14.8.1 iPhone 11 Pro

**Comment by kken78** [comment]
この件、iframeでいい感じにできそうなんですが、タグが消えてしまう問題に遭遇してこうなっています。[#316](https://github.com/codeforjapan/decidim-cfj/issues/316)

なお、やりたいのは、
（A)
<iframe src="https://www.youtube-nocookie.com/embed/aimKhstNdFg" height="100%" width="100%" allowFullscreen></iframe>　

ですが、作成すると
（B)
<iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.youtube-nocookie.com/embed/aimKhstNdFg"></iframe>
に強制的に変化されてしまいます。

なお、コンポーネント「全画面 Iframe」では、（A)のように書くように言われます。でもミーティングコンポーネント他、bodyが編集できるコンポーネントでやるとのきなみ（B)になってしまい、「全画面iframe」のときだけ消えないので謎ですね・・・

**Comment by takahashim** [comment]
ちなみに、私のAndroidのChromeブラウザでは切れずに表示されていました。

<img width="400" src="https://user-images.githubusercontent.com/10401/152303278-d1df8a0b-9e98-481c-a176-b864038f184a.png">

https://meta.decidim.org/processes/Decidim4Dummies でも同様のタグが生成されているようなので、Decidim的にはこれが妥当な表示、ということなのかと思います。

**Comment by takahashim** [comment]
↑そして、上記のDecidim4Dummies の表示もよろしくなさそうであれば、その結果をDecidim gitterかmatrixに投げると反応をもらえるかも、と思いました。

**Comment by kken78** [comment]
![Safari](https://github.com/user-attachments/assets/ddb2d715-4cda-49df-b819-dd600020abe6)
![Chrome](https://github.com/user-attachments/assets/957efdb6-2826-4d8b-bc2d-d2346cae761e)
0.28だとちゃんと表示されてそう（Safari、Chromeともに）
