### ISSUE TITLE
ユーザー登録の際の記載例を追加する

### ISSUE THREAD

**Issue by kken78** [codeforjapan/decidim-cfj#333]
## 改善詳細 / Details of Improvement
- 記載例がないと間違いやすい入力フォームがある（特に生年）
- 間違うと「不正な値です」と言われるが、何が「不正」なのかがわかりにくい

## スクリーンショットなど / Screenshot
<img width="440" alt="スクリーンショット 2022-02-03 11 51 54" src="https://user-images.githubusercontent.com/35302518/152273702-530094f5-78d6-45d0-8172-f791c3d98b9d.png">

## 期待する見せ方・挙動 / Expected behavior
- 記載例を追記する
- 生年（西暦、記載例：2000）

## 対象インスタンス / Instances

- 全て

**Comment by kken78** [comment]
セレクトボックスとどっちがいいか問題ありますね
生年だと、1900〜2022くらいになってしまい「スクロール長っ！」ってならないかな・・・

**Comment by takahashim** [comment]
selectで100件超のドロップダウンリストにする場合も多そうです。が、記入例をつけて数値で入力してもらうでもいいような気もします。

**Comment by takahashim** [comment]
多言語対応を考慮しない場合は、後ろに「年」を入れておくのが手っ取り早いかもですね。

**Comment by takahashim** [comment]
<img width="568" alt="birth_year" src="https://user-images.githubusercontent.com/10401/152299774-e7a04b2a-8aa7-4164-8610-e4b70568e76f.png">
下に説明テキストを入れることもできます（表示名のところにも追加しているものと同様のしくみです）

**Comment by takahashim** [comment]
この件ですが、（おそらくスマートフォン限定にはなりますが）inputmode="numeric"を追加すると数値入力のモードになるため少しユーザーに優しくなりそうです。
