### ISSUE TITLE
wafで、一部の画像のuploadがSQLi_BODYのルールに引っ掛かってしまう

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#336]
## 対象ドメイン/ The domain
- wafが導入されているすべての環境

## 起こっている問題 / The Problem
- 管理画面から画像のupload処理を行う
- 画像によっては、wafでblockされて403が帰ってくる

## スクリーンショット / Screenshot
![スクリーンショット 2022-02-07 18 11 36](https://user-images.githubusercontent.com/19406594/152758586-8996a093-8316-4127-a6cc-cdccb382dc68.jpg)
![スクリーンショット 2022-02-07 18 12 04](https://user-images.githubusercontent.com/19406594/152758654-4cf3aae8-df86-47ea-b652-69be0908cf32.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 画像のuploadを適切に行うことができる

## 起こっている問題の再現手段 / Steps to Reproduce
1. 管理画面にログイン
2. どの操作でもいいので、以下の画像をupload
![kakogawahigashikoukou](https://user-images.githubusercontent.com/19406594/152758918-98b17b2e-2b4a-49c1-8807-a55802f8c6c8.jpg)

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari

**Comment by ayuki-joto** [comment]
@komtaki 
こちら何か対策思いつきますでしょうか...?

**Comment by komtaki** [comment]
メンションでき気づきました。:bow:

managed ruleなので、一旦SQLi_BODYだけ無効化するのが良さそうですね。

対応します。
