### ISSUE TITLE
「興味のあるもの」設定不可

### ISSUE THREAD

**Issue by tomoaki-n** [codeforjapan/decidim-cfj#34]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- 参加者の設定メニューで、興味のあるものが追加できない

## スクリーンショット / Screenshot

![IMG_2060](https://user-images.githubusercontent.com/22102102/97067850-0170a200-15fd-11eb-9def-023ec6275ce0.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 機能が不要なら削除する
- 機能が必要なら「この組織には範囲」を設定する（？）

## 起こっている問題の再現手段 / Steps to Reproduce
1. 参加者の設定メニューから「興味のあるもの」を選択する

## 動作環境・ブラウザ / Environment
- iOS(iPad Pro2)
- Chrome

**Comment by kken78** [comment]
管理ダッシュボード上で「スコープ」の設定を行うことで設定できます
<img width="1264" alt="スクリーンショット 2022-12-17 14 32 01" src="https://user-images.githubusercontent.com/35302518/208227017-4147bb2a-80cd-47ba-a7ad-6b34caa66b53.png">

<img width="1271" alt="スクリーンショット 2022-12-17 14 32 20" src="https://user-images.githubusercontent.com/35302518/208227024-22508aa7-34f8-4301-ac86-316bf499ee62.png">
