### ISSUE TITLE
Decidim awesomeのメニュー設定のラベル表示をサイト全体に適用したい

### ISSUE THREAD

**Issue by kken78** [codeforjapan/decidim-cfj#353]
## 対象ドメイン/ The domain
全体

## 起こっている問題 / The Problem
- Decidim awesomeで実装された「メニュー設定」で「ラベル」を変更してもサイト全体に適用されず元の名前が残る（そもそもそんなことに使わない機能ってことなら別ですが・・・）
- 管理ダッシュボード上も同様の状態になっている

## スクリーンショット / Screenshot
（１）ラベルで「参加型プロセス」を「参加スペース」に変更
<img width="931" alt="スクリーンショット 2022-03-14 16 17 54" src="https://user-images.githubusercontent.com/35302518/158124435-0a1f25ad-93a5-470d-91a5-cb83c0501a64.png">

（２）「ハイライトされた参加型プロセス」は「ハイライトされた参加スペース」になってほしい
<img width="796" alt="スクリーンショット 2022-03-14 16 18 08" src="https://user-images.githubusercontent.com/35302518/158124635-0dc68132-f4b9-4bcf-987c-c4e96bdf774e.png">

## 期待する見せ方・挙動 / Expected Behavior
- ラベルの「参加型プロセス」を「参加スペース」にする
- サイト・管理ダッシュボードともに「参加スペース」で用語が統一される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 管理ダッシュボードでDecidim awesomeから「メニュー設定」を選択
2. 「参加型プロセス」の項目でラベルに任意の言葉を入れる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
やりたいことは #354 でかいけつしたのでクローズ
