### ISSUE TITLE
メッセージを受信した時の通知メールが分かり難い

### ISSUE THREAD

**Issue by tomoaki-n** [codeforjapan/decidim-cfj#36]
## 改善詳細 / Details of Improvement
- メール本文と通知文にURLが挟まれ、読みにくい。

## スクリーンショットなど / Screenshot
![メッセージ通知](https://user-images.githubusercontent.com/22102102/97068443-a0e46380-1602-11eb-989f-e1c727f728d0.jpg)

## 期待する見せ方・挙動 / Expected behavior
- 「お楽しみください！」を削除してしまう。以下のイメージ。
![メッセージ通知kai](https://user-images.githubusercontent.com/22102102/97068489-de48f100-1602-11eb-9598-914aca2ffd7e.jpg)

## 対象インスタンス / Instances

- 全て
- ○○市

**Comment by halsk** [comment]
お楽しみください！を削除する方向で。
