### ISSUE TITLE
プラットフォームの詳細情報がリンク切れ

### ISSUE THREAD

**Issue by tomoaki-n** [codeforjapan/decidim-cfj#38]
## 対象ドメイン/ The domain
- kakogawa.diycities.jp

## 起こっている問題 / The Problem
- トップページから「加古川市市民参加型合意形成プラットフォームに関する詳細情報」を開くと「お探しのページが見つかりません」と表示される

## スクリーンショット / Screenshot

[スクショ動画](https://youtu.be/TC-9PfbAs-A)

## 期待する見せ方・挙動 / Expected Behavior
- リンクを正しく設定する

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページから該当ボタンを選択
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- iOS(iPad Pro2)
- Chrome

**Comment by halsk** [comment]
現状リンク自体無くなっている

**Comment by isaozz** [comment]
コンテンツブロックの「参加方法」において詳細情報が表示されるようになっていましたが、トップ画面があまりにもごちゃごちゃしていたので整理しました。
