### ISSUE TITLE
ベルのアイコンを押すとエラーが出る

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#397]
## 対象ドメイン/ The domain
- https://kakogawa.diycities.jp/

## 起こっている問題 / The Problem
- タイトル画面の右側にあるベルのアイコンを押すと「サーバーに問題が発生しました」というエラーメッセージが出る

## スクリーンショット / Screenshot
![スクリーンショット 2022-06-24 21 28 29](https://user-images.githubusercontent.com/40754081/175536904-513f4265-caa0-4178-a0ce-ec8d0682505a.png)

## 期待する見せ方・挙動 / Expected Behavior
- ベルのアイコンに意味があるようであれば、挙動するようにしてほしい。
- 可能であればメール通知ON/OFFの確認という意味合いとして使いたい。

## 起こっている問題の再現手段 / Steps to Reproduce
1. ベルのアイコンを押す

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari / Firefox

**Comment by takahashim** [comment]
@ayuki-joto これってどういうエラーが出てるか分かりますか？　基本的にはnotificationに関連した問題が起きているんではないかと思われます。

**Comment by ayuki-joto** [comment]
こちらはv0.25以降では修正されます

**Comment by halsk** [comment]
解決済です。
