### ISSUE TITLE
HTMLタグ編集機能の更新(Decidim v0.25.x)

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/decidim-cfj#399]
## 対象ドメイン/ The domain
- すべて

## 起こっている問題 / The Problem
decidimとdecidim_awesomeの更新 (v0.25.x) に合わせて、HTMLタグ編集機能も更新が必要になりそうです

関連: #377 

## 期待する見せ方・挙動 / Expected Behavior

- HTMLタグ編集機能がこれまで同様に使える

## 動作環境・ブラウザ / Environment
- すべて

**Comment by ayuki-joto** [comment]
対応したのでcloseします
