### ISSUE TITLE
メールアドレス認証を有効にする

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#4]
## 改善詳細 / Details of Improvement
- 現状だと、メールアドレスが偽物でも登録できてしまうので、メール認証を実装する

## 期待する見せ方・挙動 / Expected behavior
- 指定メールアドレスにトークン付きのURLがついたメールを配信
- メールからURLをクリックすることで入力が完了する
- Decidim で使っている Devise では、 Confirmable 機能で実現できる。[Decidim でも Confirmableについての記述がある](https://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Confirmable)ので、この辺を調べると良いかも？

## 対象インスタンス / Instances

- 全て

**Comment by matsuihidetoshi** [comment]
@halsk 

すみません、お聞きしたほうが早そうなので、ご質問失礼します🙇‍♂️

登録のフローを試したいのですが、`rails routes`で出てくるそれらしきルーティング`/users/sign_up`を開こうとすると`/system/admins/sign_in`にリダイレクトされてしまいます。
Decidim側の仕様でしょうか？

現状、Macのローカルにコードをクローンして動かしている状況ですが、何か設定等不足していそうでしょうか？（DBの何かしらの設定テーブルなど？）

> 現状だと、メールアドレスが偽物でも登録できてしまうので、メール認証を実装する

こちらの登録フローはどのルーティング（パス）で試せますでしょうか？

**Comment by halsk** [comment]
@matsuihidetoshi さん、ありがとうございます。
とりあえず、`DEVELOPMENT.md` にある手順で、開発環境は動かせると思います。
私は Docker を使っています。

decidim は、2種類のログインアカウントがあります。

1. システム管理者
organization の管理者で、サイトのインスタンスを作ることができます。
最初に、このユーザを作る必要があります。
`db:seed` を実行すると、`system@example.org` というユーザが自動的にできます。
そうでない場合、自分で `rails console` で管理者ユーザを作る必要があります。
[このドキュメント](https://github.com/Platoniq/decidim-install/blob/master/decidim-bionic.md) の下の方にあります。
この route は、`/system/admin/sign_in` です。

2. サイト管理者
ステップ1で組織を作るときに、組織ごとに管理者を作成することができます。
`db:seed` を実行すると、 `admin@example.org` というユーザが自動的にできます。
そうでない場合、ステップ1で組織を作成する際にサイト管理者のメールアドレスを入力します。
そのアドレス宛に届くメールから、有効化させる必要があります。
（開発環境の場合で ActionMailer の設定をしておらずメール送信がされない場合、ログファイルに送信メールの内容が出るので、自分でコピペする必要があります。）
有効化の `route` は `/users/invitation/accept` です。
一度サイト（組織）を作成し、一般ユーザの登録を許可している場合、そのサイトから閲覧者が自分でユーザ登録をすることが可能になります。その場合の `route` は `/users/sign_up` です。
ログインは `/users/sign_in` です。

> こちらの登録フローはどのルーティング（パス）で試せますでしょうか？
この場合の登録フローは一般ユーザの方ですので、`/users/sign_in` となります。
ステップ1でサイトを作っていれば有効になるはずです。

**Comment by matsuihidetoshi** [comment]
@halsk 
ありがとうございます！
そう言うことだったんですね💡

こちら、試してみます！

**Comment by halsk** [comment]
@matsuihidetoshi さん、ありがとうございます。
すみません。Issue 上での、本家の議論スレのリンクが間違ってました。正確にはこちらです。

https://github.com/decidim/decidim/issues/1791

**Comment by halsk** [comment]
@matsuihidetoshi 

ちなみに、今でもメールの確認リンクは飛んでるんですよね。なので、confirmable のフラグ自体はセットされているのかも。

問題は、メール確認してないのにコメントしたりできてしまう事かなとも思いました。

![image](https://user-images.githubusercontent.com/16509/97094702-14818180-1692-11eb-8516-ccb7f24df20a.png)

**Comment by takahashim** [comment]
https://github.com/codeforjapan/decidim-cfj/blob/80213f250b0567f77ecdf8b5bac4725dc22286fb/config/initializers/decidim.rb#L93-L94

Confirmableについてはこの辺の設定が関係ありそうなんですが、`0`等にしても普通に使えそうなのが謎でした（深くは追ってません）。

**Comment by matsuihidetoshi** [comment]
@halsk @takahashim 

お二方ともありがとうございます😊

確認いたします！
