### ISSUE TITLE
コメントの並び順をリロードするとリセットされてしまう

### ISSUE THREAD

**Issue by kken78** [codeforjapan/decidim-cfj#407]
## 対象ドメイン/ The domain
- すべて

## 起こっている問題 / The Problem
-コメントの「並び順」を任意のものに選択したあと、リロードすると初期値（古い順）にリセットされる

## スクリーンショット / Screenshot

1. 初期値：「古い順」
<img width="936" alt="スクリーンショット 2022-08-15 16 23 30" src="https://user-images.githubusercontent.com/35302518/184593242-2e16b892-f99c-4fce-b2d9-c3934cd7c09d.png">

2. 並び順を「最高評価」に変更
<img width="917" alt="スクリーンショット 2022-08-15 16 23 42" src="https://user-images.githubusercontent.com/35302518/184593278-e98926d2-c8ac-44f0-90ba-813455b20ef2.png">

3. リロードすると「古い順」に戻る

## 期待する見せ方・挙動 / Expected Behavior
- リロードしても自分で変更した並び順を維持する

## 起こっている問題の再現手段 / Steps to Reproduce
（0. サイトアクセス時にCookieの使用について「同意します」ボタンを押す）
1. コメントの「並び順」を自分で選択する（最高評価・最近のもの・最も議論されたもの　のどれか）
2. コメントの並び順が選択したものに変更される
3. リロードする
4. 初期値の「古い順」に戻る

## 動作環境・ブラウザ / Environment
- macOS  / iOS
- Chrome / Safari

**Comment by kken78** [comment]
これは、以前
https://github.com/codeforjapan/decidim-cfj/pull/331
で議論をした「提案」コンポーネントに続いて、「ディベート」コンポーネントでも使えるようにしたいという話になりますね

**Comment by takahashim** [comment]
* 現在あるのは提案コンポーネント内の「提案」の並び順で、コメントの並び順については固定されていません
* また、ディベートコンポーネントや「ディベート」の並び順や、その他のコンポーネントでの並び順も固定されていません
* コメントの並び順については、全コンポーネントで共通の仕組みが使われているため、提案コンポーネントのコメントの並び順を設定すると、他のコンポーネントのコメントの並び順も同様の順序でソートされるようになるはずです
    * ただし同一インスタンス内で共有されるだけで、他のインスタンスには影響はありません
* コメントのソート順については、指定がない場合のデフォルト値としてあちこちで「古い順」に指定するようになっているので、変更するしくみを入れると今後のDecidimの更新作業にも影響があるかもしれません
    * とはいえこれはDecidim本体側のdecidim-commentsの実装をなんとかするべき、という気もしますね…。

**Comment by kken78** [comment]
なかなか手ごわいですね・・・
並び順を指定するURLが効いてくれると、当該箇所だけURLを別のところに貼り付けてそこでみんなで見る的なことができればいいんですが・・・
例えば、
https://meta.diycities.jp/processes/sample-pb/f/496/proposals/611?order=random&per_page=50
https://meta.diycities.jp/processes/sample-pb/f/496/proposals/611?order=best_rated&per_page=50
のramdomとかbest_ratedっていうのが効いてないようなので・・・

**Comment by ayuki-joto** [comment]
この機能も25で対応する必要がありますね...
