### ISSUE TITLE
通知を一度既読にすると2度と読めなくなる

### ISSUE THREAD

**Issue by tomoaki-n** [codeforjapan/decidim-cfj#44]
## 改善詳細 / Details of Improvement
- 通知を既読にすると削除されたかのようになり、過去の通知内容が不明になる。

## スクリーンショットなど / Screenshot
![kidoku](https://user-images.githubusercontent.com/22102102/97070915-0f332100-1617-11eb-83bb-4b26a9ecfe9f.jpg)
（ここで「すべて既読にする」を選択すると2度と戻れなくなる）

## 期待する見せ方・挙動 / Expected behavior
- 既読後も「全ての通知」等で既読通知を閲覧可能にする。

## 対象インスタンス / Instances

- 全て
- ○○市

**Comment by takahashim** [comment]
この機能ですが、どうも `Mark all as read`という表記なのにも関わらず、実際には該当する通知を全削除しているようです。

https://github.com/decidim/decidim/blob/71e3ccd0c81acb6d8cdc69ee440d74a05c673abc/decidim-core/app/controllers/decidim/notifications_controller.rb#L16-L19

「すべて既読にする」ではなく「すべて削除する」に表記を変えた方がいいかもしれません…。
