### ISSUE TITLE
puma workerが再起動した際にslackに通知する

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#448]
## 改善詳細 / Details of Improvement
- #447 で再起動した際にログにしか記録が残らないので、slackなど他の場所に通知する

## 期待する見せ方・挙動 / Expected behavior
- #447 で再起動した際にslackに通知する

## 対象インスタンス / Instances

- 全て

**Comment by ayuki-joto** [comment]
参考：https://github.com/slack-notifier/slack-notifier

**Comment by takahashim** [comment]
slack-notifierはメンテされていなさそうなので、 https://github.com/slack-ruby/slack-ruby-client を使う方が良さそうです（正直通知するだけならちょっと機能多すぎなんですが…）
