### ISSUE TITLE
SNS認証をかけたい

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#48]
## 改善詳細 / Details of Improvement
- 新規登録画面においてFacebookの認証ができるようになっているが、認証をしようとするとスクリーンショットのようなエラーが出る

## スクリーンショットなど / Screenshot
![スクリーンショット 2020-10-24 21 26 51](https://user-images.githubusercontent.com/40754081/97081938-ce500200-1640-11eb-8950-accef7b616d1.png)

## 期待する見せ方・挙動 / Expected behavior
- 認証できるようにしたい

## 対象インスタンス / Instances
- 加古川市

**Comment by halsk** [comment]
あー、すみません。これはまだFacebookのアプリが開発モードだからですね。テストユーザー登録しないと登録できません。
開発者モードから公開モードに切り替えます。

**Comment by isaozz** [comment]
ありがとうございます。

**Comment by halsk** [comment]
公開モードにしたので、登録できると思います。

**Comment by isaozz** [comment]
できました！！
ですが、「your 氏名と〜」とジャニーさんばりのコメントが・・・・

![スクリーンショット 2020-10-24 22 34 57](https://user-images.githubusercontent.com/40754081/97083133-2985f280-1649-11eb-81eb-863b4d5614aa.png)

**Comment by isaozz** [comment]
利用規約のところが「用語を拒否する」になってますね。コレは翻訳案件ですかね。

![スクリーンショット 2020-10-24 22 39 28](https://user-images.githubusercontent.com/40754081/97083279-d2cce880-1649-11eb-98a4-a178aec9130c.png)

**Comment by halsk** [comment]
そうですね。新たに翻訳の方にIssueを立てていただければ。
your氏名と・・・の方はFacebookが出しているメッセージなので、こちらでは修正できません。

**Comment by isaozz** [comment]
> そうですね。新たに翻訳の方にIssueを立てていただければ。
> your氏名と・・・の方はFacebookが出しているメッセージなので、こちらでは修正できません。

翻訳案件にあげました。Facebookが出しているメッセージの件は了解です！！
