### ISSUE TITLE
rails testのGitHub actionsが動かない

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#505]
## 対象ドメイン/ The domain
- 全て

## 起こっている問題 / The Problem
- imageMagicのinstall時にエラーで落ちている

## 期待する見せ方・挙動 / Expected Behavior
- rails testのGithub actionsが無事に動く

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ayuki-joto** [comment]
そうですね。一時的に起こっていた問題の様です！
一応修正用のPRは用意してたのですが、マージしなくても良さそう？
https://github.com/ayuki-joto/decidim-cfj/pull/18/files

**Comment by takahashim** [comment]
なるほどです、実行時間が短くなるならぜひ！…と思ったけどapt installがちょっと減るだけだとあんまり変わらないですかね…。マージするでもしないでもどちらでも良さそうです。

**Comment by ayuki-joto** [comment]
ですよね。。。
実行時間が長すぎるので、CICDの見直しはやりたいですがという感じですね...
