### ISSUE TITLE
テスト/デプロイを自動化したい

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#56]
## 改善詳細 / Details of Improvement
- テストとデプロイを自動化したいですね

## 期待する見せ方・挙動 / Expected behavior
- CI/CD環境を作る
- CIについては #42 も関連
- デプロイについては、今は Elastic Beanstalk に eb deploy しています。

## 対象インスタンス / Instances

- 加古川市

**Comment by doyaaaaaken** [comment]
CI/CD周りでこのプロジェクトに合いそうだと個人的に感じた構成について記載します。
（全く要件理解していない上での意見なので、違和感あれば気にせずスルーしてください！）

どちらのツールも利用経験者なので、内容聞きたいとか、設定作業自体も誰かに依頼したいとかありましたら、遠慮なく教えて下さい。 🙇 

## CI

[CircleCI](https://circleci.com/docs/ja/2.0/#section=welcome)のようなサービスを使うのが合っていそうに感じました。

folkしたリポジトリからのコミット含む、どんなコミットに対してもテストを回すことができるため、PRの受取時にもテストされたコミットであることが保証され安心感があります。
私自身も個人のOSSで使っていますが、[簡単な設定ファイルをこのように1ファイル書けば](https://github.com/doyaaaaaken/kotlin-csv/blob/master/.circleci/config.yml)あとは管理画面上で設定するだけなので簡単に使えます。
また[OSSであることを申請する](https://circleci.com/docs/ja/2.0/oss/)ことで、無料分ビルド時間が長くなったりもします。

## CD

AWS Codepipelineが、AWS Elasticbeanstalkとの相性が良さそうに感じました。（私自身職場でも利用している構成です）
Githubの特定ブランチ（例えばmaster）の変更をもとにトリガーされ、指定したコマンド（ビルド系コマンド）を実行し、最後にElasticBeanstalkへのデプロイを行うことができます。
こちらもbuildspec.ymlというビルドコマンド設定ファイルを1つ書いてリポジトリ内に含めておけば、あとはCodePipelineの画面上で少し設定するだけで使えたりします。

**Comment by komtaki** [comment]
私もCircle CIとかGithub Actions & AWS Codepipelineがいいかなと思ってました。

AWS CodepipelineならAWS ECRへのpushをキーにデプロイとかできますし。

切り戻しのjobをどこからフックさせるかとかが肝になりそうですね。
一旦はAWSコンソールからでもいいのかもしれませんが。

現状は、AWS Elasticbeanstalkに直接デプロイしている感じですよね。CI/CDするなら、コンテナにしてテストされた資源をそのままデプロイするのがベストかなと思いました。

1. CIでimageをbuild
2. imageをECRにpush
3 .BeanstalkがECRからimageをpullし、EC2上でコンテナを起動

**Comment by halsk** [comment]
CIについて：今は Github Actions が楽なので、そちらで行きたいです！
@doyaaaaaken 
@komtaki 
AWS の設定、できそうであれば管理権限をシェアしますが、いかがでしょうか。
（機密事項に触ることになるので、NDA結んでいただきますが）

**Comment by komtaki** [comment]
構築頑張ります。NDAの件、承知しました。

電子契約だとありがたいです。クラウドサインとか（自社製品を押してるわけではないです。笑）

**Comment by komtaki** [comment]
Github Actionsも最近は、機能が充実してきましたからね。

AWSのリソースは、cloud formationで作ると管理が楽なので、その方向でやりたいです。ecrとか、ほぼなんでも作れるので。

**Comment by halsk** [comment]
@komtaki ありがとうございます！
hal@code4japan.org
CC: jinnouchi@code4japan.org
宛にNDAを送る先をメールしてください。

**Comment by doyaaaaaken** [comment]
@halsk 
ありがとうございます！↑のメールアドレス宛に、NDAを送る先を記載したメール送信いたしました。

@komtaki 
cloud formation, ecr普段使ってないのですみませんがAWS構築はリードしていただいてもいいですか？
（変に分担するのも難しいかもしれませんが）もし分担したほうが楽そうな箇所あればやりますので遠慮なく教えて下さい！
一番きれいな分担はGithub Actionsだけ僕が設定するとかな気がしてますが、いかがでしょう？

**Comment by komtaki** [comment]
@halsk 
NDA送付先をメールしました。

@doyaaaaaken 

>一番きれいな分担はGithub Actionsだけ僕が設定するとかな気がしてますが、いかがでしょう？

承知しました。一旦、ふんわりこの分担でいきましょうか。ElasticBeanstalkに、私はそこまでくわしくないので、Cloud Formationで基礎的な部分を作って、適宜レビューしてもらうのでいかがでしょう？

あとは、現状、Dockerイメージは公式のイメージを使っています。ですが、イメージサイズが大きいので、セキュリティ的にもslimとかにして圧縮した方がいいと思います。途中まで作っているので、引き続き私がやろうと思います。

Github Actionsのワークフローは、こんなイメージでしょうか

1. Docker image build
1. Rubocop test
1. RSpec test
-- master --のみ
1. Docker image push  to ECR
1. Deploy to AWS Elastic Beanstalk from AWS Code  Pipeline

**Comment by takahashim** [comment]
deployのタイミングではRuboCopは動かさなくて良さそうです。基本的にはlintなので、RSpecによるテストが通っていれば動作は問題ないかと思います。

**Comment by doyaaaaaken** [comment]
@komtaki

諸々考えていただきありがとうございます！

> 承知しました。一旦、ふんわりこの分担でいきましょう。ただ、私はElasticBeanstalkにそこまで詳しくないので、Cloud Formationで基礎的な部分を作るので、適宜レビューしてもらう感じで。

はい、承知しました！

> あとは、現状、Dockerイメージは公式のイメージを使っています。ですが、イメージサイズが大きいので、セキュリティ的にもslimとかにして圧縮した方がいいと思います。途中まで作っているので、引き続き私がやろうと思います。

#67 ですね。ありがとうございます！

> Github Actionsのワークフローは、こんなイメージでしょうか

大体僕も同じイメージです。
@takahashim さんおっしゃるとおりで、 `2.Rubocop test` は無くそうと思います。

> あとは、デプロイタイミングですかね？

この要件、決めたいですね。 
@halsk デプロイタイミングはどちらがいいでしょうか？

> 1. Git tagベース - > ある程度タイミングを制御する場合（毎回デプロイしない）
> 2. Commit pushベース -> コミットがmasterブランチに入るたび毎回デプロイする

あとGithub ActionsについてはもしGithubの権限いただければ、早速CIだけでも先に作っていきたいので権限付与のタイミングもご検討よろしくおねがいします。

**Comment by halsk** [comment]
ありがとうございます！
git tag ベースが良さそうに思います。

**Comment by komtaki** [comment]
仮で、ECRのレポジトリを作成しました。
cloud foramtionのテンプレートは後で、このレポジトリ？にあげます。

ECR URL
https://ap-northeast-1.console.aws.amazon.com/ecr/repositories/decidim-cfj/?region=ap-northeast-1

Cloud formation stack
https://ap-northeast-1.console.aws.amazon.com/cloudformation/home?region=ap-northeast-1#/stacks/stackinfo?filteringText=&filteringStatus=active&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aap-northeast-1%3A887442827229%3Astack%2Fcreate-ecr-repository-decidim-cfj%2Ff786f940-1be9-11eb-8873-0a4084594d18

**Comment by halsk** [comment]
このIssue、まだ終わっていないと思うので、再オープンします。

**Comment by doyaaaaaken** [comment]
GithubActionのCIの件、着手遅くなっていてすみません 🙏 
明日祝日ですので着手します。

**Comment by komtaki** [comment]
@doyaaaaaken 

すみません。ざっくりデプロイのGithubActions作っちゃいました。:bow:
@\takahashim さんが、テストの方もだいたい作ってくれてるみたいですし。

そちらは大体できそうなのですが、肝心のstaging環境のElastic Beanstalkの構築に少々手こずりそうです。
設定手順がわりとあるので、こちら手伝ってほしいです。

↓
https://github.com/codeforjapan/decidim-cfj/issues/110

**Comment by takahashim** [comment]
テストについては、現状のrails-test.ymlでのテストはGitHub上のubuntu-latestの汎用的なActionベースで動かしているため、コンテナを使うのであればその環境でも動かして問題ないかどうか確認した方がよいのでは？　という気持ちもあるのでした。

でも現状のDockerfileだとtest環境のbundle installはしないんですよね。コンテナを使ったビルド・デプロイパイプラインって最近はどういう対応にするのがいいんでしょうか？（あくまで軽量化を優先 vs あくまでtestとproductionで同一のイメージにこだわる）

**Comment by komtaki** [comment]
testとかだと、bundle installしたライブラリをDockerにmountして使うのがいいのかなと思ってます。
Gemfile.lockでlockされているので、基本バージョンはずれないはずですし。

毎回Buildすると、実行速度にも影響があるので、変更がなければ、latestとかで使い回すのがいい気がします。現状latestタグはないので、一旦stsgingタグとかでしょうか。:thinking:

**Comment by komtaki** [comment]
だいぶ時間が空いてしまいましたが、タイミングを見てElastic beanstalkのCNAME SWAPを使ってdockerコンテナにプラットフォームごと本番も切り替えたいです。そしたら現在のgiithubのジョブをいじるだけで、github上からデプロイできるようになります。

手順は下記のような感じでやれば、ダウンタイム無で切り替えられます。
https://aws.amazon.com/jp/premiumsupport/knowledge-center/decouple-rds-from-beanstalk/

https://dev.classmethod.jp/articles/beanstalk-cname-swap/

もしstagingだけで発現するエラーとかあれば、コンテナを調整するのでご教授いただけると助かります。:bow:

**Comment by komtaki** [comment]
@ayuki-joto 上記の流れで、対応しても問題ないでしょうか？

**Comment by komtaki** [comment]
承知しました。:+1:

**Comment by komtaki** [comment]
@ayuki-joto 

準備出来ました。MRとdecidim-appに作成したproduction環境の確認をお願いします。:bow:

台数、設定等できる限り現状の設定に合わせています。

**Comment by ayuki-joto** [comment]
@komtaki ありがとうございます！
環境の確認の件承知しました！

いくつか確認したいことがあります！

1. 今回のPRをマージした場合、今後masterへのpushが発生した際に本番にデプロイされるという認識ですがあっていますでしょうか？
2. 運用の際のオペレーションに関して、マイグレーションのロールバックなどはEC2内に入って行うような形でしょうか？別途このあたりこれまでと差が出る部分あれば教えていただきたいです！
3. DBを先日載せていただいた手法で保護→ebの環境を削除するの流れでいいでしょうか？

**Comment by komtaki** [comment]
@ayuki-joto 

>1. 今回のPRをマージした場合、今後masterへのpushが発生した際に本番にデプロイされるという認識ですがあっていますでしょうか？

上記のMRすでにご確認いただいているかと思いますが、tag pushされた時ですね。下記MRに含まれるDEPLOYMENT.mdの一部抜粋です。

>切り戻しを早くするため、masterマージの際、Dockerイメージは毎回buildします。
>
>パイプラインが通ったのを確認後、git上でデプロイしたいコミットに、v○○とタグを打ちます。
>タグはvから始まる必要があります。すぐにeb deployが実行されます。
>
> 例: v1.0.0

> 2.運用の際のオペレーションに関して、マイグレーションのロールバックなどはEC2内に入って行うような形でしょうか？別途このあたりこれまでと差が出る部分あれば教えていただきたいです！

一部変わるとすれば、ec2にはいったあと、`sudo docker exec` でコンテナに入る必要が出てくるくらいですかね。基本は大きく変わらないです。

> 3. DBを先日載せていただいた手法で保護→ebの環境を削除するの流れでいいでしょうか？

その通りです。DBの保護はすでに有効化しているので、上記の手順から省いてました。:sweat_drops:

**Comment by ayuki-joto** [comment]
@komtaki 
> 上記のMRすでにご確認いただいているかと思いますが、正確にはtag pushされた時ですね。MRに含まれるDEPLOYMENT.mdの一部抜粋です。

承知です！こちら見逃していたのでありがたいです！

>変わるのはセッションマネージャーからec2にはいったあと、sudo docker exec -it {コンテナID} sh でコンテナに入る必要が出てくるだけですかね。基本は変わらないです。

こちらも承知しました！

>その通りです。DBの保護はすでに有効化しているので、上記の手順から省いてました。

保護の有効化ありがとうございます！

**Comment by ayuki-joto** [comment]
#231
こちらの問題が解決次第環境切り替える作業に入ります！
#227 についてもこちらの対応次第でマージします！

**Comment by ayuki-joto** [comment]
@komtaki 
すみません。質問なのですが、cloud watchの方にrails本体のログが出ていないようなのですが、こちらはわざとでしょうか？
cloud watch周りの知見がないので教えていただきたいです！

**Comment by komtaki** [comment]
@ayuki-joto 

> cloud watchの方にrails本体のログが出ていないようなのですが、こちらはわざとでしょうか？

失礼しました。ファイルに出力されていたので、cloud watchに流れる対象から外れてました。
new_relicのログも合わせて、標準出力に流れるように修正しました。下記のロググループに流れています。 :bow:

/aws/elasticbeanstalk/production/var/log/eb-docker/containers/eb-current-app/stdouterr.log

**Comment by ayuki-joto** [comment]
@komtaki 
log対応ありがとうございました！確認できました！
また　#231 についても解決したので近日中に対応します！

**Comment by ayuki-joto** [comment]
@komtaki 
すみません、一点失念していたのですが、今回の環境に切り替える際に
#185 で対応していただいたcloud frontのドメイン関係の設定も切り替え必要になるかと思うのですが、どのように対応すればいいでしょうか？

**Comment by komtaki** [comment]
cloud frontはまだ何もしてないので、対応は不要です。このあと進めようと思ってます。

時間決めて、私がDNS切り替えますか？MRのマージはしてもらって（私もMRマージできるのですが、セルフマージはあまりよくないので。あとdevelopブランチとかmasterのフローがよくわかってないのもあり）

やろうと思えばドメイン単位で切り替えて、カナリアリリースみたいなことも出来ると思います。testが入っているドメインを先に切り替えて、しばらくして他のドメインも切り替えるのが安全ですかね。

**Comment by ayuki-joto** [comment]
@komtaki cloud front不要とのことで承知いたしました。

DNSの切り替えですが、明日の深夜に行う予定です！
ユーザーの混乱を避けるためにも一律で同時に切り替える予定です！
また作成していただいているMRについても、本日中ににマージ、検証する予定です！

**Comment by ayuki-joto** [comment]
テストのみ先に切り替えるは確かにありですね．
こちら側で完結しているもので検証します！
ありがとうございます！

**Comment by komtaki** [comment]
@ayuki-joto 

対応ありがとうございます。ではお言葉に甘えてよろしくおねがいします。:bow:

切り替えるはRoute53から、 `production2.eba...`のAレコードを`production.eba...`に全て変更するだけです。

ElasticBeanstalkの古い環境の削除は、私が来週対応します。DNS浸透まで時間がかかるので、すぐには消せません。

テストドメインをdockerランタイムの新環境に切り替えたら、連絡ください。最後に、ざっと私もさわって検証しておきたいです。:+1:

**Comment by ayuki-joto** [comment]
@komtaki 
環境の削除承知しました！
23時までには対応して連携いたします！

**Comment by komtaki** [comment]
ありがとうございます。

**Comment by ayuki-joto** [comment]
@komtaki 
デプロイの検証など完了しました！
https://codeforjapan.diycities.jp/
こちら新環境に切り替えたので確認してもらえればと思います！

**Comment by komtaki** [comment]
ありがとうございます。アカウント作成から一通り触ってみます。

**Comment by komtaki** [comment]
パラパラページめくりつつ、下記やってみました。特に異常なく、メールも来たし、cloud  watchにエラーログもないですね。

1.アカウント作成
2.ログイン
3.プロフィール画像アップロード&変更
4.メール設定変更
5.サインアウト

まだ時間があれば触ってみるつもりですが、パット見大丈夫そうです。

**Comment by ayuki-joto** [comment]
@komtaki 
ご確認ありがとうございます！

**Comment by komtaki** [comment]
@ayuki-joto 
予定通り今日このあと切り替えですね。お手数ですがよろしくお願いします。

もしなにかあれば、メンションください。明日の朝確認します。:bow:

**Comment by ayuki-joto** [comment]
予定通り変更いたしました。
こちらで確認している状態では特に問題ないですが、念の為確認お手隙の際に実施していただければ幸いです。

**Comment by komtaki** [comment]
@ayuki-joto 

対応ありがとうございます。

正常に切り替わっていることを確認しました。ただちょっとCPU使用率が前よりも高い気がします。以前のアプリとログを見比べてみたんですが、特に怪しい箇所は見当たらず。:sweat_drops:

杞憂かもしれませんが、awsからリソース面からもう少し調べてみます。私はnewrelic見れないので、newrelicからパフォーマンス観点で確認をお願いできますか？

**Comment by komtaki** [comment]
@ayuki-joto 
あと新しい環境だとsidekiqが動いていないですね。:sweat_drops:近日中に対応します。

一旦、旧環境で動いているので確認できたので、問題はないですかね？

**Comment by ayuki-joto** [comment]
@komtaki 
おっと、ということはqueueの処理になっていないということでしょか？

**Comment by komtaki** [comment]
キーが`secret_key_base`とか環境固有値に依存していなければ、queueを積む環境と、queueの処理を消化する環境が分かれてる気がします。ruby自体&sidekiqの処理にあまり詳しくないので、キーが依存しているかどうかはっきりと明言はできないのですが。

新環境では、おそらく動いてないですが、旧環境では'/app/log/sidekiq.log'にログが吐かれているので動いてます。

sidekiqを設定しているのはここなのですが、見落としてました。:sweat_drops:
https://github.com/codeforjapan/decidim-cfj/blob/master/deployments/.ebextensions/03_sidekiq.config#L7

調整自体は、2,3日でできると思います。

**Comment by komtaki** [comment]
codeforjapanとか、demoサイトで試してみたいのですが、どういう操作したらキューが積まれるかわかりますか？

**Comment by ayuki-joto** [comment]
@komtaki なるほど！僕も確認漏れていましたすみません...
queueはredisに積まれるであっています！
ということは一旦旧環境に戻した方が安全とかありますでしょうか...?

> codeforjapanとか、demoサイトで試してみたいのですが、どういう操作したらキューが積まれるかわかりますか？

こちらぱっと思いつくのがメール処理くらいなのですが最近そこも怪しいのではないかという話がでてたりするので一旦確認します

**Comment by komtaki** [comment]
確認ありがとうございます。確かに、mailersというのが入ってますね。

メールが全部キューで送付されているなら、codefeorjapanで動かした時に、メールちゃんときましたね。そしたら、queueを積む環境と、queueの処理を消化する環境が分かれてるだけで障害にはなってないので、戻さなくて大丈夫な気がしますね。

修正対応は急ぎますが。

**Comment by ayuki-joto** [comment]
productionのActiveJobは全部sidekiqに任せるような形になっているようです！
メールまわり僕も確認しましたが、コメントの通知などもきたので切り分けが難しいですね...

一旦どれかのインスタンスで、
`bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -e production `
こちら実行して様子見しようと思います！(数日はこれで乗り切れるかと期待してます)
修正対応またご連絡いただければと思います！

**Comment by komtaki** [comment]
> メールまわり僕も確認しましたが、コメントの通知などもきたので切り分けが難しいですね...

個人的には、切り分けは出来てると思ってました。はっきり新環境で積まれたキューが、旧環境でキューが消化されているログが出てるので。ちなみにどのあたりがわからない感じです？

docker環境では出来ないので、新環境ではなく別のインスタンスを立てるってことですよね？
やってもいいと思います。結局現状と同じなので、あまり意味はないようなきました。

> 一旦どれかのインスタンスで、
bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -e production
こちら実行して様子見しようと思います

修正は出来次第連絡します。:+1:

**Comment by komtaki** [comment]
私の説明が下手ですみません。:sweat_drops:

修正は急ぎます。:bow:

**Comment by ayuki-joto** [comment]
いえいえ！
僕の理解不足でした！

修正お手数おかけしますが、よろしくお願い致します！

**Comment by komtaki** [comment]
@ayuki-joto 

だいたいPRで来たのですが、railsのところでつまってます。rubyほぼ触ったことないので 💦 

stagingでメール送付される処理をしたとき、sidekiqがSMTPのlocalhost:25を見に行ってします。

環境変数として、SMTP_ADDRESS等は設定しました。Docker内でecho $SMTP_ADDRESSしたときに、正常にドメインが返ってきます。

https://github.com/codeforjapan/decidim-cfj/blob/develop/config/environments/production.rb#L83

https://github.com/codeforjapan/decidim-cfj/blob/develop/config/secrets.yml#L70

なので、railsのconfig/secrest.ymlがよまれてないように見えます。
sidekiq単体で動かしているので、railsの初期化がされてない？気がしますが、よくわからず。。

アドバイス頂けると助かります。:bow:

**Comment by ayuki-joto** [comment]
@komtaki 
遅くなってしまい申し訳ありません！

こちらまだ起こっている現象でしょうか？
railsの初期化という点があまりわかっていないのですが、sidekiqのコンテナでは設定した環境変数などは見れているのでしょうか？

一旦もろもろ検証したいのでマージしてstagingで触ってみるとかでしょうか...?

**Comment by ayuki-joto** [comment]
それと、PRのこちらの件
>sidekiqはメモリ使用量が多く、webサーバーのスケールとスケールのタイミングが異なる。アクセスが増えたからと言って、キューの処理量もそれに応じて、増えるわけではない。このレベルのサービスなら1プロセスで十分。
そのため、WEBサーバーと同じパッケージに入れるのは非効率的だと感じた。パフォーマンスを追求するならfargateとかに移行するべきだと思う。

こちらについても並行して検討しております！ありがとうございます！

**Comment by komtaki** [comment]
@ayuki-joto 

>こちらまだ起こっている現象でしょうか？
railsの初期化という点があまりわかっていないのですが、sidekiqのコンテナでは設定した環境変数などは見れているのでしょうか？

残念ながら、まだ解決しておりません。かなり頑張っているのですが。:sweat_drops:

rails 用とsidekiq用で、コンテナを2つに分けました。イメージ、環境変数は同じものを使用しています。

sidekiqのログには、production起動したと記述があるのですが、ホストやポートがデフォルトのままでaction mailerの設定がされない状態です。

sidekiq用のコンテナ内で、rails c -e productionして、ActionMailerで関数呼ぶとメールが送れます。なのでsidekiqの問題だと思うのですが、完全にはまってます。

https://qiita.com/kon_yu/items/570a14af3f91f867e6ba

**Comment by komtaki** [comment]
MRのは、余談なのであまり気にしないでください。

たしかにMRレビューしてもらって、問題がなければ、stagingで見てもらったほうが早そうです。お手好きの際にお願いします。:bow:

**Comment by komtaki** [comment]
>sidekiqのログには、production起動したと記述があるのですが、ホストやポートがデフォルトのままでaction mailerの設定がされない状態です。

おそらくですが、システム上の環境変数が、sidekiqプロセス上で上手く読めてない気がしています。RAIL_ENVが見えず、railsは開発者モードで起動しているような。。

**Comment by komtaki** [comment]
@ayuki-joto 

原因がわかりました！！！

組織ごとにsmtpの設定が出来るんですね。それにlocalhost 25で設定が入っていたからでした。おそらくfakerでデータを作成した時に自動で設定されたのだと思います。設定を消したらちゃんと送付されました。:sweat_drops:

どうりで、自分のMRのミスを探しても見つからないわけだ。。。

![キャプチャ](https://user-images.githubusercontent.com/39375566/120913486-74351600-c6d2-11eb-9285-71f7f9e37d92.JPG)

**Comment by ayuki-joto** [comment]
@komtaki 
あーーーこんな機能ありましたね！
失念しておりました。申し訳ありません。
レビューしましたので、確認していただければと思います！

**Comment by komtaki** [comment]
@ayuki-joto 

レビューありがとうございます。コメントしました。

問題なければ、stagingマージと本番反映をお願いします。

**Comment by komtaki** [comment]
@ayuki-joto 

> ただちょっとCPU使用率が前よりも高い気がします。以前のアプリとログを見比べてみたんですが、特に怪しい箇所は見当たらず。💦

少しこちら調べてみました。

decidimのアプリの中で結構でかい/tmp/diffy-20210621***みたいなファイル2つに対してdiffを取るプロセスが実行され、IOに負荷がかかりCPUの大半を食ってますね。

ファイルの中身はHTMLぽい？設定変更した時とかに実行されるかんじでしょうか。

New RelicのAPMを入れられてると思いますが、これ何かご存じですか？

**Comment by komtaki** [comment]
@ayuki-joto 

リリースありがとうございます。sidekiqも動いており、メールも送られているので大丈夫そうですね。

1日経ったので、旧環境を1台にスケールダウンしました。タイミングを見て環境ごと削除します。

**Comment by komtaki** [comment]
手順通り旧環境を削除しました。特に問題はなさそうです。

何かあれば連絡をください。これで本イシューは終了ですかね?

**Comment by ayuki-joto** [comment]
@komtaki リリース遅くなり申し訳ありません！
ご対応ありがとうございます！

>時折decidimのアプリの中で結構でかい/tmp/diffy-20210620***みたいなファイル2つに対してdiffを取るプロセスが実行され、IOに負荷がかかりCPUの大半を食ってますね。 🤔
ファイルの中身はHTMLぽい？設定変更した時とかに実行されるかんじでしょうか。

こちらについては現在調査中なのですが、各ディベートを編集した際に生成されるバージョン管理機能の方で、負荷が高まりCPU使用率が跳ね上がる現象を確認しています！
DBのデータが問題ではないかとなっており現在DB方面調査中です！

> 何かあれば連絡をください。これで本イシューは終了ですかね?

問題ないと思っています！ありがとうございます！
