### ISSUE TITLE
提案タイトルの文字数制限を弱めにする（本格対応）

### ISSUE THREAD

**Issue by halsk** [codeforjapan/decidim-cfj#61]
## 改善詳細 / Details of Improvement
- #23 で対応した暫定対応ではなく、メンテナンスしやすいような対応にする

## 期待する見せ方・挙動 / Expected behavior
- 本家でハードコードされてしまっている文字数制限を設定ファイルか何かに移せるようにできると良いですね

## 対象インスタンス / Instances

- 全て

**Comment by knsg16** [comment]
本格対応どうすればいいのか、一応Gitterの方でも質問してみました。
https://gitter.im/decidim/decidim#

**Comment by knsg16** [comment]
@halsk 
上記Gitterで確認して回答をいただくことができました。
本格対応する際には、自分たちでModuleを新たに作成する必要がありそうです。

> If you want to extend Decidim, the prefered way should be by having a Module. This is a Ruby on Rails Engine which provides ruby code (models, views, controllers, assets, etc). You can use it through multiple ways:

[Customize > Code](https://docs.decidim.org/en/customize/code/)より



decidim-barcelonaでは、以下のようにdecidim-debatesというmoduleを新たに自分たちで作成して拡張しているようなので、参考になりそうです。
https://github.com/AjuntamentdeBarcelona/decidim-barcelona/tree/c210b5338d7ba1338c9879627e081da1441f1946/decidim-debates

**Comment by takahashim** [comment]
確認ありがとうございます！　うーん、なるほど。
せっかくだから正攻法で、本家で対応してもらうのであれば、↓この辺の`component.settings`で設定可能なように変更してもらう（ためのpull requestを作る）、とかかなあと思っているのですが、ここで設定されている値を変更するにはどうするのかがいまいち分かっていません…。

https://github.com/decidim/decidim/blob/144dc20b12e2471156566123c5df3bda9df3655a/decidim-proposals/lib/decidim/proposals/component.rb#L24-L55

**Comment by takahashim** [comment]
と思ったら、管理画面で設定するんですね…！
「参加スペース」をクリック→スペースを選んでクリック→「コンポーネント」をクリック→設定したいコンポーネントを選んで「設定」をクリック、で変更できるようになるようです。

**Comment by knsg16** [comment]
@takahashim 
なるほど。管理画面で設定できるのですね。
調査ありがとうございます！

そうしたら、本家の方でPR作成して、管理画面でタイトルのminとmaxを設定できるような修正をしたほうがいいかもですね。
本家の方にissueを立てて議論してみます。

**Comment by takahashim** [comment]
この件ですが、本格対応の前に #23 の時の暫定対応の方がデグレードしてしまっているようでした…

* 関連 #495
