### ISSUE TITLE
引き落とした提案が表示されたままとなる

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#66]
## 改善詳細 / Details of Improvement
- 参加者側の提案を引き落とした場合でも、そのまま提案が表示されたままとなっている。 
- 引き落とされた提案を管理者側から削除したい
- 運用としては、参加者側からの提案は受け付けないこととしたいが、テキストで促すしかない

## スクリーンショットなど / Screenshot
![引き落とした提案](https://user-images.githubusercontent.com/40754081/97257250-b8b52500-1858-11eb-9d54-f0d2f70e5a46.png)

## 期待する見せ方・挙動 / Expected behavior
- 引き落とした提案を管理者側から削除する
- 引き落とした提案を見えなくする

## 対象インスタンス / Instances

- 全て
- 加古川市

**Comment by halsk** [comment]
@isaozz 「提案」コンポーネントは、基本、市民→市への提案を基本的な考え方としているようです。
また、思想的に、一度パブリックにしたものは削除できないようになっているようですね。
情報の透明性の観点からだと思います。

提案を受け付けない場合、ディベートコンポーネントを使うのはいかがでしょうか。
新規の内容は受け付けず、今の提案コンポーネントと同じ機能が利用できます。

**Comment by isaozz** [comment]
@halsk 「提案」コンポーネントはそういった意味合いのような気がしていました。
「ディベート」コンポーネントにデータを格納するようにしてみます。

**Comment by isaozz** [comment]
@halsk 「ディベート」ですと画像を貼り付けることができないですね。
HTMLタグなどが利用できるとありがたいです。

**Comment by halsk** [comment]
@isaozz というわけで、こちらは提案コンポーネントの仕様ということで、修正しない方向で良いでしょうか。
