### ISSUE TITLE
Dockerfile、docker-compose.yamlが存在しないバージョンを使用している

### ISSUE THREAD

**Issue by komtaki** [codeforjapan/decidim-cfj#7]
## 対象ドメイン/ The domain
- セットアップ時

## 起こっている問題 / The Problem
- dockerhub に存在しないバージョンを指しているため、コンテナのpullに失敗する

https://hub.docker.com/r/decidim/decidim/tags

0.23.0.devというバージョンはない

## スクリーンショット / Screenshot

```
PS C:\Users\taki\Dev\decidim-cfj> docker-compose up -d
Pulling app (decidim/decidim:0.23.0.dev)...
ERROR: manifest for decidim/decidim:0.23.0.dev not found: manifest unknown: manifest unknown
```

## 期待する見せ方・挙動 / Expected Behavior
- コンテナのpullに成功する

## 起こっている問題の再現手段 / Steps to Reproduce
1. `git clone git@github.com:codeforjapan/decidim-cfj.git`
2. `cd decidim-cfj`
3. `git checkout -b master origin/master`
4. `docker-compose pull`

## 動作環境・ブラウザ / Environment
- Windows

**Comment by halsk** [comment]
Docker では検証していないので、可能なら修正いただけると助かります！
取り急ぎ、加古川市で使いたいのは `release/0.23-stable` です。

**Comment by komtaki** [comment]
承知しました。 👍 

現状、0.23のリリースが完了しておらず、dockerで該当のヴァージョンが出ていないです。
なので、latestで追いかけて、出たらversion固定でいいのかなと思います。

他に2か所くらい直したら、ローカルで動いているように見えました。正しい挙動を知らないので、雰囲気ですが。笑
