### ISSUE TITLE
新規登録時の文言の変更

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#71]
## 改善詳細 / Details of Improvement
- 新規登録の画面において「氏名」を「ニックネームに」、 「ニックネーム」を「アカウントID」に合わせていただけないでしょうか。
- また、「生年」と書かれてあるところを「生年（西暦）」としていただけないでしょうか。
- 「参加者の設定 - マイアカウント」も同様です。

## スクリーンショットなど / Screenshot
![スクリーンショット 2020-10-28 6 29 59](https://user-images.githubusercontent.com/40754081/97364738-d1b8e700-18e7-11eb-855a-2ae8fe8a8b45.png)

![スクリーンショット 2020-10-28 6 36 08](https://user-images.githubusercontent.com/40754081/97364820-f2813c80-18e7-11eb-9077-de0663cd6cb8.png)

## 期待する見せ方・挙動 / Expected behavior
- できるだけユーザー側の混乱がでないようにしたいです。

## 対象インスタンス / Instances

- 全て
- 加古川市

**Comment by halsk** [comment]
Crowdin 側では変更してありますので、本日反映します。
