### ISSUE TITLE
翻訳に関する総合Issue ２

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#74]
## 改善詳細 / Details of Improvement
- ディベートにおけるフィルタリング部分「原点」「オフィシャル」「Citizens」「グループ」「私のアクティビティ」「私の議論」の意味合いがよくわかりませんでした。

## スクリーンショットなど / Screenshot
![フィルタリング](https://user-images.githubusercontent.com/40754081/97404783-fd64bd00-1939-11eb-878f-ad71626a4097.png)

## 期待する見せ方・挙動 / Expected behavior
- 赤枠部を非表示にするのもよいかもしれません。
## 対象インスタンス / Instances

- 全て
- 加古川市

**Comment by isaozz** [comment]
投稿に対する「いいね」ボタンにカーソルを持ってくると「このコメントに同意します」となっていますが、「そう思わない」ボタンにカーソルを持ってくると「このコメントに合意しない」となっています。
「このコメントに同意しません」にしていただけないでしょうか。

**Comment by isaozz** [comment]
パスワードの桁数が短い場合のコメントが、「短すぎます,ユニークな文字が十分ではありません」と表示されています。
「パスワードが短すぎます。」でいかがでしょうか。

**Comment by isaozz** [comment]
参加者の設定 - 通知の設定において、「誰からでもダイレクトメッセージを受信する」を「ダイレクトメッセージを受信する」としてください。

**Comment by isaozz** [comment]
参加者の設定 - 通知の設定において、「誰からでもダイレクトメッセージを受信する」の下にある「私は彼らに従わない場合でも、誰でも私にダイレクトメッセージを送信することを許可します」を「参加者からのメッセージを受信する」としてください。

**Comment by halsk** [comment]
原点→起案者
オフィシャル→事務局
Citizens→一般参加者
私のアクティビティ→参加したもの

> 短すぎます,ユニークな文字が十分ではありません
