### ISSUE TITLE
入力例について

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#76]
## 改善詳細 / Details of Improvement
- 登録時に入力されるところに入力例があるとありがたいです。
- また、ニックネームには「投稿に表示される公表名。」とありますが、IDにも「投稿に表示される」旨を書いていただけないでしょうか。

## 対象インスタンス / Instances

- 全て
- 加古川市

**Comment by takahashim** [comment]
@isaozz 各項目について、おすすめの入力例の文言はありますか？　具体例があると修正が捗るかと思います。

**Comment by isaozz** [comment]
アカウントIDの下に「加古川市市民参加型合意形成プラットフォームでの別名」とありますが、「本人を識別するための任意のアルファベットを入力してください。」にしていただき、その下に
「表示名とアカウントIDが投稿に表示されます。例）加古川太郎@kako」としていただくのはどうでしょうか。

**Comment by takahashim** [comment]
ありがとうございます！

![issue76](https://user-images.githubusercontent.com/10401/97590712-40aa5300-1a42-11eb-88d5-c31b9b4d79ce.png)

↑こういう感じにフォーム内の未入力時の文字（placeholder）も表示するのがよいでしょうか（ちょっと元々の設定だと色が薄いかも）

**Comment by isaozz** [comment]
@takahashim 
そうしていただけると非常にありがたいです。

**Comment by halsk** [comment]
@isaozz ここの表記は全てのインスタンスで使われるので、「加古川」と入るのは望ましくないです。
山田太郎ってのもありがちですが、存在しない名前で、ジェンダーレスな「共創 歩」とかはどうでしょう

**Comment by isaozz** [comment]
@halsk その表現が良いかと思います。ありがとうございます。
