### ISSUE TITLE
職業欄について

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#78]
## 改善詳細 / Details of Improvement
- 新規登録時の性別欄と職業欄のスペースをもう少し広げていただくことは可能でしょうか。

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 対象インスタンス / Instances

- 全て
- 加古川市

**Comment by halsk** [comment]
![image](https://user-images.githubusercontent.com/16509/97430444-3f065f80-195c-11eb-9299-f54316557227.png)

性別欄と職業欄のスペースをもう少し広げる、とはどういう意味でしょうか。
性別欄と職業欄の間のスペースを

**Comment by isaozz** [comment]
わかりにくくてすいません。
性別のその他の下に職業があるので、見逃してしまうようです。
その他の下にスペースを設けていただけると助かります。

![スクリーンショット 2020-10-28 22 00 15](https://user-images.githubusercontent.com/40754081/97439099-1769c400-1969-11eb-9a85-0dd426cf4ffd.png)

**Comment by takahashim** [comment]
性別・職業どちらも `<div class="field">`〜`</div>`でくくっているので揃いそうなものですが、たしかにここは詰まって見えますね。fieldsetを追加しても変わらなさそうでした。

職業欄というよりもradio buttonがきれいに表示されないみたいです（テキスト入力は勝手に1remのマージンがつく模様）。個別に指定した方がいいかもしれません。
