### ISSUE TITLE
Facebookからの登録について

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#79]
## 改善詳細 / Details of Improvement
- Facebookから登録した場合、属性情報を入力することなく登録することができます。

## 期待する見せ方・挙動 / Expected behavior
- どこで個人を特定するかという考え方の整理が必要かと思われます。

## 対象インスタンス / Instances

- 全て
- 加古川市

**Comment by takahashim** [comment]
なるほど…！ Facebookからだとsign_upを完全に飛ばしてアカウントを作ってしまうんですね。
Decidim::Devise::OmniauthRegistrationsControllerのcreateメソッドを上書きして、OmniauthRegistrationForm・CreateOmniauthRegistrationの代わりのFormとCommandを実装するのがいいのでしょうか。

**Comment by takahashim** [comment]
このissueですが、Facebookからの登録自体に介入するのは難しいようなので、

* Facebookからは属性情報がなくても登録自体は完了する（＝今の登録フローは変更なし）
* 登録フローとは別に、ログインしているときに（毎回）属性情報の有無を調べて、属性情報が登録されていない場合はアカウント設定ページにredirectする

という対応方針を考えています。
